#!/usr/bin/env python3
"""
HTTP Requests Scraper — Dyson India (www.dyson.in), Magento 2 / Adobe Commerce.

Two-phase architecture:
  Phase 1 — discover PDP URLs from the purifiers listing (shared-module
            pagination via src.listing_discovery).
  Phase 2 — extract fields from each PDP (rich SSR JSON-LD Product + DOM
            price box), via the src.http_fetch proxy-aware fetch ladder.

Generated by Code Writer Agent for Universal Ecommerce Scraper.
Adapted from templates/requests_scraper.py for dyson.in.

Usage:
    python3 scraper_draft.py                    # Phase 1 discovery + full Phase 2
    python3 scraper_draft.py --sample           # Phase 2 on first 5 input URLs
    python3 scraper_draft.py --input urls.json  # explicit input file
    python3 scraper_draft.py --urls url1 url2   # URLs as CLI arguments
"""

import argparse
import json
import logging
import os
import re
import sys
import time
from datetime import datetime, timezone
from html import unescape
from typing import Optional
from urllib.parse import urljoin

import requests  # noqa: F401 -- drafts' Phase-2 helpers commonly need it
from bs4 import BeautifulSoup

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))

# ═══════════════════════════════════════════════════════════════════════════════
# CONFIGURATION - Update these values
# ═══════════════════════════════════════════════════════════════════════════════

SITE_NAME = "Dyson India"
SITE_URL = "https://www.dyson.in"
PLATFORM = "magento2_adobe_commerce_custom_theme"
SCRAPING_METHOD = "http_requests"
SITE_SLUG = "dyson-in"

# Promoted listing from navigation_analysis. NOTE (live-probed): this page is an
# editorial landing whose product rows are client-rendered, so it selects ZERO
# product anchors under direct HTTP; PRODUCT_LISTING_URLS below adds the
# deeper catalog page (/shop-all-air-purifiers) that the landing itself links
# to, so discovery has a second, product-bearing listing shape to walk.
PRODUCT_LISTING_URL = "https://www.dyson.in/air-treatment/purifiers"
SRC_URL = "https://www.dyson.in/air-treatment/purifiers"
PAGE_PARAM_NAME = "p"
# Multi-listing enumeration: landing (promoted) + the real catalog grid.
# [dyson.in] The grid URL carries Magento's server-side limit param: when the
# category block renders server-side, ?product_list_limit=all puts the whole
# catalog on page 1 (zero extra requests). When the grid hydrates client-side
# (live probe: 0 anchors either way) the param is inert — same shell, so
# discovery costs one extra fetch and loses nothing.
PRODUCT_LISTING_URLS = [
    "https://www.dyson.in/air-treatment/purifiers",
    "https://www.dyson.in/air-treatment/shop-all-air-purifiers?product_list_limit=all",
]
# Offset-style pagination (SFCC `start`, Algolia-style offsets): when
# OFFSET_MODE is True the page param carries (page-1)*PAGE_SIZE instead of
# the page number — e.g. ?start=0&sz=48, ?start=48&sz=48, ... code_writer
# sets PAGE_SIZE / EXTRA_PAGE_PARAMS from navigation_analysis.pagination.
PAGE_SIZE = None
OFFSET_MODE = False
# Extra query params merged into every listing page URL (e.g. {"sz": 48}).
EXTRA_PAGE_PARAMS: dict = {}
DELAY_BETWEEN_REQUESTS = 1.5
# Safety cap on listing pagination (None = unlimited). Set high per the
# "FULL extraction" contract — paginating until exhaustion, not an arbitrary cap.
MAX_PAGES = None
# Fail-fast wall-clock deadline for Phase 1 discovery.
DISCOVERY_DEADLINE_SECONDS = 300
# One-shot re-enumeration delay when Phase 1 ends with ZERO discovered URLs.
EMPTY_DISCOVERY_RETRY_DELAY_S = 45

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
}

# ── HTTP FETCH — SHARED MODULE, NOT YOURS TO REIMPLEMENT (CRITICAL) ──────────
# code_writer: keep the import + wiring below VERBATIM. Do NOT write your own
# fetch loop and do NOT drop the proxy ladder because analysis said "direct
# works" — Akamai-class sites allow the first hits, then challenge LATER runs
# (job-58 birkenstock: tester 5/5 PASS; execution minutes later got 200-wrapped
# challenge pages, zero links, and the ladder had been stripped so there was
# nothing to escalate to → 0 items). The module also carries the persistent
# session (cookies round-trip — a bare requests.get() is a cookieless one-shot
# that re-raises the bot score on every hit) and the soft-block proxy-tier
# mechanism the shared discovery module drives. Full rationale: src/http_fetch.py.
from src.http_fetch import create_fetch_page
from src.page_analysis import phase2_instant_fail

fetch_page = create_fetch_page(delay_s=DELAY_BETWEEN_REQUESTS, headers=HEADERS)

# ── LISTING DISCOVERY — SHARED MODULE, NOT YOURS TO REIMPLEMENT (CRITICAL) ───
# code_writer: keep the import + the main() call VERBATIM. The pagination
# loop, the soft-block proxy-ladder escalation, the JSON-LD ItemList
# fallback, and the zero-URL retry live in src/listing_discovery.py
# (job-65 citybeach: the inline loop was rewritten and the escalation branch
# deleted — the draft still EMITTED the soft_block_escalations counter, so
# it looked instrumented, but no code path could ever increment it; the
# execution-window soft block had no trigger and the job finalized 0 items).
# The ONLY discovery code you adapt is _extract_listing_links below, plus
# the data constants.
from src.listing_discovery import discover_listing_urls_with_retry

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
TIMESTAMP = datetime.now(timezone.utc).strftime("%Y-%m-%d_%H%M%S_%f")
OUTPUT_FILE = os.path.join(SCRIPT_DIR, f"output_{TIMESTAMP}_{os.getpid()}.json")
INPUT_FILE = os.path.join(SCRIPT_DIR, "input_urls.json")
LOG_FILE = os.path.join(os.path.dirname(SCRIPT_DIR), "logs", f"{SITE_SLUG}.log")

# ═══════════════════════════════════════════════════════════════════════════════
# LOGGING
# ═══════════════════════════════════════════════════════════════════════════════

os.makedirs(os.path.dirname(LOG_FILE), exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[
        logging.FileHandler(LOG_FILE),
        logging.StreamHandler(),
    ],
)
logger = logging.getLogger(__name__)


# ═══════════════════════════════════════════════════════════════════════════════
# HELPERS
# ═══════════════════════════════════════════════════════════════════════════════

def clean_html(html_str: str) -> str:
    if not html_str:
        return ""
    text = re.sub(r"<[^>]+>", " ", html_str)
    text = unescape(text)
    return re.sub(r"\s+", " ", text).strip()


def make_absolute_url(url: str, base: str = SITE_URL) -> str:
    if not url:
        return ""
    if url.startswith("http"):
        return url
    if url.startswith("//"):
        # Protocol-relative: only keep the // when the next segment is a
        # plausible netloc (contains a dot) — "/product/123" paths that leak a
        # leading // would otherwise become https://product/123.
        tail = url[2:]
        head = tail.split("/", 1)[0]
        if "." in head:
            return f"https:{url}"
        return urljoin(base, "/" + tail)
    return urljoin(base, url)


# ── FIELD NORMALIZERS — inline on purpose, NOT a src import ──────────────────

def _norm_price(value) -> Optional[str]:
    """Strip currency symbols/whitespace from a price.

    "£1,234.56" → "1234.56", "1.234,56 €" → "1234.56", 24.99 (a JSON-LD
    number) → "24.99". Returns None when no digits are present — an
    unparseable price is EMPTY, never zero (0 would read as a real product
    priced at nothing). The currency stays in its own ``currency`` field.
    """
    if value is None:
        return None
    cleaned = re.sub(r"[^\d.,-]", "", str(value).strip())
    if not re.search(r"\d", cleaned):
        return None
    if "," in cleaned and "." in cleaned:
        # Both separators present: whichever comes LAST is the decimal one.
        if cleaned.rfind(",") > cleaned.rfind("."):
            cleaned = cleaned.replace(".", "").replace(",", ".")
        else:
            cleaned = cleaned.replace(",", "")
    elif "," in cleaned:
        # "1,234" (grouping) vs "1,5" (decimal comma): a comma followed by
        # exactly three digits is grouping, anything else is a decimal comma.
        cleaned = re.sub(r",(?=\d{3}(?:\D|$))", "", cleaned).replace(",", ".")
    return cleaned


def _norm_availability(value) -> Optional[str]:
    """Normalize availability to ``in_stock`` / ``out_of_stock``.

    Accepts the schema.org URI form, InStock / In Stock / in_stock / Available
    and their negatives. Anything unrecognised passes through lowercased —
    availability is never invented (an unknown state is data, not an error).
    """
    if value is None:
        return None
    if isinstance(value, bool):
        return "in_stock" if value else "out_of_stock"
    text = str(value).strip().lower()
    if not text:
        return None
    if "://" in text:  # e.g. http://schema.org/InStock
        text = text.rsplit("/", 1)[-1]
    compact = text.replace("-", "_").replace(" ", "")
    if compact in ("in_stock", "instock", "available"):
        return "in_stock"
    if compact in ("out_of_stock", "outofstock", "unavailable", "sold_out", "soldout"):
        return "out_of_stock"
    return text


# ═══════════════════════════════════════════════════════════════════════════════
# EXTRACTION - dyson.in selectors (Magento 2 / Adobe Commerce custom theme)
# ═══════════════════════════════════════════════════════════════════════════════

# PDP URL shape on www.dyson.in. Anchor + embedded-config candidates MUST match
# one of these to count as product links. Two live shapes exist:
#   3-segment: /air-treatment/purifiers/purifier-cool-pc2-de-nox-white-gold
#   2-segment: /purifier-cool-pc2-de-nox-white-gold   (JSON-LD offers.url /
#              link[rel=canonical] form — short utility pages are excluded by
#              the 16-char slug floor and the negative filter below)
PDP_URL_RE = re.compile(
    r"^https?://(?:www\.)?dyson\.in/"
    r"(?:"
    r"(?:air-treatment|hair-care|vacuums|floor-care|lighting|wearables|accessories|shop-all[^/]*)"
    r"/[a-z0-9][a-z0-9-]*/[a-z0-9][a-z0-9-]{8,}"
    r"|"
    r"[a-z0-9][a-z0-9-]{15,}"
    r")(?:\?.*)?$"
)
# Anything landing on a listing/utility rail is never a product page.
PDP_URL_NEGATIVE_RE = re.compile(
    r"(?:/overview|/research|/accessories?(?:/|$)|/compare|/support|/faq"
    r"|/warranty|/register|/login|/account|/cart|/checkout|/blog|/story"
    r"|/guide|/newsroom|/terms|/privacy|/-recertified|/demo"
    r"|-filter-research|/shop-all-air-purifiers)"
)

# The verbatim job URL: a known-good PDP used as a discovery safety net.
ANCHOR_PRODUCT_URL = (
    "https://www.dyson.in/air-treatment/purifiers/purifier-cool-pc2-de-nox-white-gold"
)


def _looks_like_pdp(url: str) -> bool:
    if not PDP_URL_RE.search(url):
        return False
    if PDP_URL_NEGATIVE_RE.search(url):
        return False
    return True


def _collect_candidate_urls(soup: BeautifulSoup) -> list:
    """Every http(s) URL string appearing ANYWHERE in the page — anchors,
    buttons, data attributes, inline scripts, JSON-LD, iframe srcs. Magento's
    CSR grids keep their card config in embedded JSON islands, so a
    DOM-anchor-only sweep selects 0 links on this site (probed live)."""
    urls = []
    for a in soup.find_all("a"):
        href = a.get("href") or ""
        if href.startswith("http"):
            urls.append(href)
        elif href.startswith("/"):
            urls.append(urljoin(SITE_URL, href))
    for el in soup.find_all(True):
        for attr in ("data-url", "data-href", "data-product-url", "data-link"):
            val = el.get(attr)
            if val and val.startswith("/"):
                urls.append(urljoin(SITE_URL, val))
    for script in soup.find_all("script"):
        if script.get("type") in ("application/ld+json", "application/json"):
            continue  # handled separately below / by the shared ItemList fallback
        txt = script.string or ""
        if "dyson.in" not in txt and "/air-treatment" not in txt:
            continue
        for m in re.finditer(r'https?://[A-Za-z0-9.-]*dyson\.in/[^"\'\\\s<>)]+', txt):
            urls.append(m.group(0).rstrip(".,;"))
    return urls


def _extract_jsonld_products(soup: BeautifulSoup) -> list:
    """All Product-typed JSON-LD nodes (the site ships one per PDP)."""
    products = []
    for script in soup.find_all("script", type="application/ld+json"):
        raw = script.string or script.get_text() or ""
        if not raw.strip():
            continue
        try:
            data = json.loads(raw)
        except (json.JSONDecodeError, TypeError):
            continue
        nodes = data if isinstance(data, list) else [data]
        for node in nodes:
            if not isinstance(node, dict):
                continue
            if "Product" in (node.get("@type") if isinstance(node.get("@type"), list) else [node.get("@type")]):
                products.append(node)
    return products


def extract_jsonld(soup: BeautifulSoup) -> Optional[dict]:
    """Single Product JSON-LD node for this PDP (first match)."""
    products = _extract_jsonld_products(soup)
    return products[0] if products else None


def extract_product_from_page(soup: BeautifulSoup, url: str, status_code: int, src_url: str) -> dict:
    product = {
        "id": 0,
        "title": "",
        "price": "",
        "availability": "",
        "original_price": "",
        "currency": "",
        "url": url,
        "src_url": src_url,
        "location": "",
        "status_code": status_code,
        "scraped_at": datetime.now(timezone.utc).isoformat(),
        "remarks": "",
    }

    jsonld = extract_jsonld(soup)

    # ── Soft-404 detection — BEFORE field extraction ────────────────────────
    # ( Magento serves HTTP 200 for dead PDPs. )
    page_text = ""
    h1_el = soup.find("h1")
    h1_text = h1_el.get_text(strip=True) if h1_el else ""
    title_tag = soup.title.get_text(strip=True) if soup.title else ""
    try:
        body = soup.find("body")
        page_text = body.get_text(" ", strip=True) if body else ""
    except Exception:
        page_text = ""
    soft404 = False
    soft404_reason = ""
    if jsonld is None:
        # No Product JSON-LD anywhere: either a soft-404 shell or a non-PDP.
        if re.search(r"not\s*found|no\s*longer\s*available|unavailable|discontinued",
                     f"{title_tag} {h1_text}", re.I):
            soft404 = True
            soft404_reason = "Soft 404: no Product JSON-LD + 'not found' page title"
        else:
            soft404 = True
            soft404_reason = "Soft 404: no Product JSON-LD on page"
    elif re.search(r"not\s*found|no\s*longer\s*available|discontinued",
                   f"{title_tag} {h1_text}", re.I):
        soft404 = True
        soft404_reason = "Soft 404: page title/H1 says not found/discontinued"
    if soft404:
        product["remarks"] = soft404_reason
        return product

    offers = jsonld.get("offers", {}) or {}
    if isinstance(offers, list):
        offers = offers[0] if offers else {}

    # Title
    product["title"] = (jsonld.get("name") or "").strip() or (h1_text or title_tag.split(" | ")[0]).strip()

    # Price — JSON-LD first (authoritative), DOM price box as fallback.
    price_raw = offers.get("price", "")
    product["price"] = _norm_price(price_raw) or ""
    if not product["price"]:
        price_el = soup.select_one(".price-box .price-final_price .price")
        if not price_el:
            price_el = soup.select_one('[data-price-type="finalPrice"] .price')
        if price_el:
            product["price"] = _norm_price(price_el.get_text(strip=True)) or ""

    # Original price — only when a LOWER current price exists (sale state).
    # [dyson.in probed] This catalogue currently renders NO oldPrice nodes, so
    # this is future-proofing, not a live selector: guard every read.
    original_candidates = []
    for sel in ('[data-price-type="oldPrice"] .price', ".price-box .old-price .price"):
        el = soup.select_one(sel)
        if el:
            original_candidates.append(_norm_price(el.get_text(strip=True)))
    original_candidates = [c for c in original_candidates if c]
    if original_candidates and product["price"]:
        try:
            if max(float(c) for c in original_candidates) > float(product["price"]):
                product["original_price"] = max(original_candidates, key=float)
        except (TypeError, ValueError):
            pass

    # Currency — JSON-LD first, ₹/Rs lead as DOM fallback.
    product["currency"] = (offers.get("priceCurrency") or "").strip()
    if not product["currency"]:
        price_el = soup.select_one(".price-box .price-final_price .price")
        text = price_el.get_text(strip=True) if price_el else ""
        if text.startswith("₹") or "Rs" in text[:4]:
            product["currency"] = "INR"
    if not product["currency"]:
        product["currency"] = "INR"  # dyson.in catalog is INR-only

    # Availability — JSON-LD Offer.availability (schema.org URI), DOM fallback.
    product["availability"] = _norm_availability(offers.get("availability"))
    if not product["availability"]:
        if soup.select_one(".product__action__add-to-cart-notifyme"):
            product["availability"] = "out_of_stock"
        elif soup.select_one("#product-addtocart-button"):
            product["availability"] = "in_stock"

    # Description — meta description (JSON-LD description is EMPTY on this site).
    meta_desc = soup.select_one('meta[name="description"]')
    product["description"] = (
        meta_desc.get("content", "").strip() if meta_desc else ""
    )

    # Brand / SKU — JSON-LD (not rendered in the DOM on this theme).
    brand = jsonld.get("brand") or {}
    if isinstance(brand, dict):
        product["brand"] = (brand.get("name") or "").strip()
    elif isinstance(brand, str):
        product["brand"] = brand.strip()
    product["sku"] = (jsonld.get("sku") or "").strip()

    # Images — JSON-LD image array ONLY (Adobe Dynamic Media CDN), scoped to
    # the PDP's own primary images: never nav/hero/related thumbs. Plain
    # DOM-gallery scraping here would drag in client-rendered slick-carousel
    # clones (duplicate srcs) and off-product rails, so JSON-LD is the safe
    # product-gallery source on this theme.
    image_urls = []
    raw_images = jsonld.get("image")
    if isinstance(raw_images, str):
        raw_images = [raw_images]
    if isinstance(raw_images, list):
        for img in raw_images:
            abs_img = make_absolute_url(str(img))
            if not abs_img.startswith("http"):
                continue
            low = abs_img.lower()
            if any(bad in low for bad in (
                "/brand.assets/", "/emoji/", "/flags/", "/icon", "/navigation/",
                "logo", "banner", "placeholder", "sprite",
            )):
                continue
            if abs_img not in image_urls:
                image_urls.append(abs_img)
    product["images"] = image_urls[:15]

    # Category — derive from the URL path (this theme renders no breadcrumbs).
    path_parts = [p for p in url.split("://", 1)[-1].split("/", 1)]
    path = "/" + (path_parts[1] if len(path_parts) > 1 else "")
    product["category"] = " > ".join(
        p.replace("-", " ").strip().title()
        for p in path.strip("/").split("/")
        if p
    )

    return product


# ═══════════════════════════════════════════════════════════════════════════════
# DISCOVERY - adapt ONLY the callback below; the loop itself is the shared module
# ═══════════════════════════════════.-- (see banner) ──────────────────────────

# CSS selector matching THIS site's product anchors on a listing page. Kept as
# a module-level constant so the shared module's logging/diagnostics reference
# it; the real harvest is the deep scan in _extract_listing_links (this site's
# product grids are client-rendered — anchors alone select 0 links, probed).
PRODUCT_LINK_SELECTOR = (
    "a[href*='/air-treatment/'], a[href*='/hair-care/'], a[href*='/vacuums/'], "
    "a[href*='/lighting/'], a[href*='/shop-all']"
)
# Optional compiled regex a candidate URL must match to count as a product
# link. Applied to anchors in _extract_listing_links AND — via url_filter — to
# JSON-LD ItemList candidates inside the shared module.
PRODUCT_URL_RE = PDP_URL_RE


def _extract_listing_links(soup: BeautifulSoup) -> list:
    """The ONLY site-adaptable discovery code: this page's product URLs.

    Contract: return a list of ABSOLUTE urls (dupes fine — the shared module
    dedupes). Return [] when the page carries no product links; NEVER raise.
    An empty result makes the module do exactly one of two things before it
    gives up: check the page's JSON-LD ItemList (hidden-SSR listings embed
    their item set there even when the visible grid hydrates client-side),
    or escalate the proxy tier (200-but-zero-links soft-block signature).

    dyson.in specifics (live-probed): BOTH catalog pages
    (/air-treatment/purifiers landing and /air-treatment/shop-all-air-purifiers
    grid) are client-rendered shells under direct HTTP — the product data
    lives in embedded config islands, not <a href> markup. So this callback
    deep-scans every anchor, data-* URL, and inline script for PDP-shaped
    URLs, filtered by the site's PDP pattern.
    """
    # # Code Writer adapted: dyson.in deep-scan discovery (CSR catalog pages)
    urls = _collect_candidate_urls(soup)

    # PDP-shaped candidates only (regex is the same one shared discovery
    # applies to JSON-LD ItemList candidates, so anchor and ItemList paths
    # stay shape-consistent).
    found = set()
    for u in urls:
        absolute = make_absolute_url(u)
        if _looks_like_pdp(absolute):
            found.add(absolute.rstrip("/"))

    # Known-good safety net: the verbatim job URL is a PDP on this site; if
    # its listing/rail mentions it anywhere (e.g. as a relatedProducts target),
    # pin it into the result set even if the pattern mis-fires on a variant
    # spelling.
    if ANCHOR_PRODUCT_URL in " ".join(urls) or ANCHOR_PRODUCT_URL in str(soup):
        found.add(ANCHOR_PRODUCT_URL)

    return sorted(found)


# ═════════════════════════════════════════════════════════ only-adapt ─────────
# INPUT HANDLING
# ═══════════════════════════════════════════════════════════════════════════════

def load_urls_from_file(filepath: str) -> list:
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data.get("urls", [])


def save_urls_to_file(filepath: str, urls: list) -> None:
    # [job-77] A 0-URL discovery must not DESTROY an existing seed file.
    if not urls and os.path.exists(filepath):
        logger.warning(f"Refusing to overwrite {filepath} with an empty URL list")
        return
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump({"urls": urls}, f, indent=2, ensure_ascii=False)
    logger.info(f"Saved {len(urls)} URLs to {filepath}")


# ═══════════════════════════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════════════════════════

# ── CLI CONTRACT — keep every line below when adapting ───────────────────────
# The pipeline launches this scraper with EXACTLY these names. A flag missing
# from the argparse below is STRIPPED at launch and discovery silently falls
# back to the seed file (input_urls.json). Same for the SCRAPER_LISTING_URL
# env read in main(). ADD flags if you need them; NEVER remove or rename:
#   --fresh-discovery  always (execution)     --listing-url  navigation/list_page
#   --query            search_term            --input/--sample/--limit  testing
#   --discover-only    Phase-1 probe          (+ SCRAPER_LISTING_URL env read)
# Source of truth: webapp/agents/constants.py
# ──────────────────────────────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser(description=f"HTTP scraper for {SITE_NAME}")
    parser.add_argument("--sample", action="store_true", help="Scrape only 5 products")
    parser.add_argument("--limit", type=int, default=None, help="Max products to scrape")
    parser.add_argument("--input", type=str, default=None, help="Path to input URLs JSON file")
    parser.add_argument("--urls", nargs="+", default=None, help="Product URLs as arguments")
    parser.add_argument(
        "--discover-only",
        action="store_true",
        help="Run Phase 1 discovery only; emit discovery_coverage, skip Phase 2 extraction",
    )
    parser.add_argument(
        "--fresh-discovery",
        action="store_true",
        help="Ignore any discovery cache and re-run Phase 1 (accepted as a no-op here: "
        "requests_scraper has no checkpoint file to skip)",
    )
    parser.add_argument(
        "--listing-url",
        type=str,
        default=None,
        help="Listing/category page to discover product URLs from (overrides PRODUCT_LISTING_URLS)",
    )
    parser.add_argument(
        "--no-proxy",
        action="store_true",
        help="Force direct HTTP, no proxy (this site verified direct-OK; accepted as a "
        "no-op here: src.http_fetch defaults to tier 0 = none)",
    )
    args = parser.parse_args()

    if args.input:
        # [job-60 zquiet] The runner's CWD is not the scraper's directory.
        args.input = os.path.join(SCRIPT_DIR, args.input)

    start_time = time.time()

    logger.info("=" * 80)
    logger.info(f"Starting scraper for {SITE_NAME}")
    logger.info(f"Site: {SITE_URL}")
    logger.info(f"Listing URL: {PRODUCT_LISTING_URL}")
    logger.info(f"Output: {OUTPUT_FILE}")
    logger.info("=" * 80)

    if args.fresh_discovery:
        logger.info(
            "--fresh-discovery accepted (no-op: requests_scraper has no "
            "discovered_urls_checkpoint.json to ignore; input_urls.json is rewritten on every discovery)"
        )
    if args.no_proxy:
        logger.info(
            "--no-proxy accepted (no-op: src.http_fetch ladder starts at tier 0 = "
            "direct; this site's access recipe is proxy tier none)"
        )

    product_urls = []
    discovered_urls_raw = 0
    ran_phase1 = False
    skipped_reason: Optional[str] = None
    discovery_meta: dict = {"stop_reason": "skipped", "max_pages_hit": False}

    # Shared-module discovery config (data, not code — see the import banner).
    _discovery_cfg = {
        "page_param": PAGE_PARAM_NAME,
        "page_size": PAGE_SIZE,
        "offset_mode": OFFSET_MODE,
        "extra_page_params": EXTRA_PAGE_PARAMS,
        "url_filter": PRODUCT_URL_RE,
        "max_pages": MAX_PAGES,
        "deadline_s": DISCOVERY_DEADLINE_SECONDS,
        "retry_delay_s": EMPTY_DISCOVERY_RETRY_DELAY_S,
    }

    # Phase 1: URL discovery (or load from input).
    # F6 DETERMINISTIC DISCOVERY GATE (env-var): run_execution injects
    # SCRAPER_LISTING_URL because the LLM-adapted argparse may drop
    # --listing-url/--fresh-discovery (the CLI-contract guard then strips
    # them). Without this gate the seed-file branch below ALWAYS wins (the
    # seed file exists — run_execution stages input_urls.json) and discovery
    # never runs (prod 285: 1 item from 4 seeds; pagination dead). In-place
    # [:] mutation so LLM-copied drafts that alias the list stay coherent.
    _env_listing = os.environ.get("SCRAPER_LISTING_URL", "").strip()
    if _env_listing:
        PRODUCT_LISTING_URLS[:] = [_env_listing]
        logger.info("Env gate: SCRAPER_LISTING_URL set — forcing Phase 1 discovery on %s",
                    _env_listing[:80])
    elif args.listing_url:
        # CLI listing override (--listing-url): same role as the env gate.
        PRODUCT_LISTING_URLS[:] = [args.listing_url]
        logger.info("--listing-url set — Phase 1 discovery on %s", args.listing_url[:80])

    if args.discover_only or _env_listing or args.listing_url:
        logger.info("Discovery mode (%s): running Phase 1, skipping Phase 2 extraction",
                    "env-gate" if _env_listing else ("--listing-url" if args.listing_url else "--discover-only"))
        product_urls, discovery_meta = discover_listing_urls_with_retry(
            fetch_page, PRODUCT_LISTING_URLS, _extract_listing_links,
            **_discovery_cfg,
        )
        discovered_urls_raw = len(product_urls)
        ran_phase1 = True
        save_urls_to_file(INPUT_FILE, product_urls)
    elif args.urls:
        product_urls = args.urls
        skipped_reason = "url_list_mode"
    elif args.input:
        product_urls = load_urls_from_file(args.input)
        skipped_reason = "url_list_mode"
    elif os.path.exists(INPUT_FILE):
        logger.info(f"Loading previously discovered URLs from {INPUT_FILE}")
        product_urls = load_urls_from_file(INPUT_FILE)
        skipped_reason = "checkpoint_loaded"
    else:
        logger.info("No input_urls.json found. Discovering products from listing page...")
        product_urls, discovery_meta = discover_listing_urls_with_retry(
            fetch_page, PRODUCT_LISTING_URLS, _extract_listing_links,
            **_discovery_cfg,
        )
        discovered_urls_raw = len(product_urls)
        ran_phase1 = True
        save_urls_to_file(INPUT_FILE, product_urls)

    # Raw discovered count is captured BEFORE any sample/limit slicing.
    if not ran_phase1:
        discovered_urls_raw = len(product_urls)

    # Sample/limit only apply when Phase 2 extraction will run.
    if not args.discover_only:
        if args.sample:
            product_urls = product_urls[:5]
        if args.limit:
            product_urls = product_urls[: args.limit]

    logger.info(f"Total products to scrape: {len(product_urls)}")

    results = []
    failed = 0

    if not args.discover_only:
        # Phase 2: extract fields from each discovered item page.
        phase2_start = time.monotonic()
        for i, url in enumerate(product_urls):
            result = fetch_page(url)
            if result:
                soup, status_code = result
                product = extract_product_from_page(soup, url, status_code, SRC_URL)
                product["id"] = i + 1
                # Emission filter (ported from playwright_scraper): a row with
                # NO substantive field beyond the boilerplate keys is a page
                # that rendered nothing — shipping it as a product poisons the
                # item count every downstream gate reads.
                _BK = {"url", "src_url", "scraped_at", "status_code", "remarks", "id", "title"}
                if any(v for k, v in product.items() if k not in _BK):
                    results.append(product)
                else:
                    logger.warning(f"No substantive data extracted from: {url}")
                    failed += 1
            else:
                logger.error(f"Failed to fetch: {url}")
                failed += 1

            if (i + 1) % 25 == 0:
                percent = ((i + 1) / len(product_urls)) * 100
                logger.info(f"Progress: [{i + 1} / {len(product_urls)}] ({percent:.1f}%)")
    else:
        logger.info("--discover-only: skipping Phase 2 extraction (results list left empty)")

    # Mechanical "fetch actually happened" detector (template verbatim).
    phase2_instant = False
    if not args.discover_only and product_urls:
        phase2_elapsed = time.monotonic() - phase2_start
        phase2_instant = phase2_instant_fail(
            phase2_elapsed, len(product_urls), DELAY_BETWEEN_REQUESTS
        )
        if phase2_instant:
            logger.warning(
                "PHASE2 INSTANT FAIL: %s items in %.2fs (< %.2fs floor at "
                "delay=%ss) — fetches never actually happened",
                len(product_urls), phase2_elapsed,
                len(product_urls) * DELAY_BETWEEN_REQUESTS * 0.5,
                DELAY_BETWEEN_REQUESTS,
            )

    # discovery_coverage block — contract §1. Always emitted.
    if ran_phase1:
        stop_reason = discovery_meta.get("stop_reason", "no_next_link")
    else:
        stop_reason = "skipped"

    discovery_coverage = {
        "stop_reason": stop_reason,
        "found": len(results),
        "discovered_urls": discovered_urls_raw,
        "expected_total": None,
        "dimensions_iterated": 0,
        "dimensions_total": 0,
        "max_pages_hit": discovery_meta.get("max_pages_hit", False),
        "ran_phase1": ran_phase1,
        "skipped_reason": skipped_reason,
        "soft_block_escalations": discovery_meta.get("soft_block_escalations", 0),
        "retried_empty_discovery": discovery_meta.get("retried_empty_discovery", False),
        "jsonld_fallback_pages": discovery_meta.get("jsonld_fallback_pages", 0),
        "phase2_instant_fail": phase2_instant,
    }

    output = {
        "site": {
            "name": SITE_NAME,
            "url": SITE_URL,
            "platform": PLATFORM,
            "scraping_method": SCRAPING_METHOD,
            "scraped_at": datetime.now(timezone.utc).isoformat(),
        },
        "products": results,
        "metadata": {
            "phase": "discovery" if args.discover_only else "extraction",
            "scraping_duration_seconds": round(time.time() - start_time, 2),
            "failed_products": failed,
            "rate_limit_delay": DELAY_BETWEEN_REQUESTS,
            "discovered_urls": discovered_urls_raw,
            "discovery_coverage": discovery_coverage,
        },
    }

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(output, f, indent=2, ensure_ascii=False)

    logger.info("=" * 80)
    logger.info("DISCOVERY COMPLETE (--discover-only)" if args.discover_only else "EXTRACTION COMPLETE")
    logger.info(f"Total: {len(results)}, Failed: {failed}")
    logger.info(
        f"Discovery coverage: stop_reason={stop_reason}, found={len(results)}, "
        f"discovered_urls={discovered_urls_raw}, ran_phase1={ran_phase1}, "
        f"skipped_reason={skipped_reason}"
    )
    logger.info(f"Duration: {round(time.time() - start_time, 2)}s")
    logger.info(f"Output: {OUTPUT_FILE}")
    logger.info("=" * 80)


if __name__ == "__main__":
    main()
