# Generated by Django 5.2.15 on 2026-06-06 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('product_url', models.URLField(blank=True, default='')),
                ('currency', models.CharField(blank=True, default='', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('waiting_approval', 'Waiting for Approval'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('opencode_session_id', models.CharField(blank=True, default='', max_length=100)),
                ('site_name', models.CharField(blank=True, default='', max_length=200)),
                ('platform', models.CharField(blank=True, default='', max_length=100)),
                ('scraping_method', models.CharField(blank=True, default='', max_length=100)),
                ('product_count', models.IntegerField(default=0)),
                ('output_file', models.CharField(blank=True, default='', max_length=500)),
                ('site_folder', models.CharField(blank=True, default='', max_length=500)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_type', models.CharField(choices=[('re_scrape', 'Re-scrape Confirmation'), ('confidence', 'Low Confidence Warning'), ('mechanism', 'Scraping Mechanism Choice'), ('field_coverage', 'Low Field Coverage'), ('validation', 'Validation Retry/Fail'), ('field_confirm', 'Field Confirmation'), ('execution', 'Execution Approval'), ('skill_update', 'Skill File Update')], max_length=30)),
                ('question', models.TextField(blank=True, default='')),
                ('response_data', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('opencode_permission_id', models.CharField(blank=True, default='', max_length=100)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='scraper.scrapejob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('site_analysis', 'Site Analysis'), ('product_analysis', 'Product Analysis'), ('code_generation', 'Code Generation'), ('testing', 'Testing'), ('field_confirmation', 'Field Confirmation'), ('execution', 'Execution'), ('cleanup', 'Cleanup'), ('skill_learning', 'Skill Learning')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='scraper.scrapejob')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
