# Generated by Django 5.2.15 on 2026-06-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_sessionlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sessionlog',
            new_name='scraper_ses_job_id_090268_idx',
            old_name='sessionlog_job_seq_idx',
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='product_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
