# Generated by Django 5.2.15 on 2026-06-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_rename_sessionlog_job_seq_idx_scraper_ses_job_id_090268_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapejob',
            name='full_extraction',
            field=models.BooleanField(default=False),
        ),
    ]
