# Generated by Django 5.2.15 on 2026-06-08 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_langgraph_remove_opencode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(max_length=100)),
                ('tool_name', models.CharField(max_length=200)),
                ('tool_call_id', models.CharField(blank=True, default='', max_length=200)),
                ('call_seq', models.IntegerField(default=0)),
                ('args_summary', models.TextField(blank=True, default='')),
                ('result_summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_call_logs', to='scraper.scrapejob')),
            ],
            options={
                'ordering': ['call_seq'],
                'indexes': [models.Index(fields=['job', 'call_seq'], name='scraper_too_job_id_a54dde_idx'), models.Index(fields=['job', 'agent'], name='scraper_too_job_id_6568b3_idx')],
            },
        ),
    ]
