# Generated by Django 5.2.15 on 2026-06-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_toolcalllog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('slug', models.CharField(blank=True, default='', max_length=200)),
                ('platform', models.CharField(blank=True, default='', max_length=100)),
                ('scraping_method', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(default='new', max_length=20)),
                ('product_count', models.IntegerField(default=0)),
                ('fields_extracted', models.JSONField(default=list)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tracked Site',
                'ordering': ['-created_at'],
            },
        ),
    ]
