# Generated by Django 5.2.15 on 2026-06-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_trackedsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253)),
                ('proxy_tier', models.CharField(default='none', max_length=20)),
                ('method', models.CharField(max_length=50)),
                ('status_code', models.IntegerField(default=0)),
                ('page_title', models.CharField(blank=True, default='', max_length=500)),
                ('cached_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Probe Cache',
                'verbose_name_plural': 'Probe Cache',
                'ordering': ['-cached_at'],
                'constraints': [models.UniqueConstraint(fields=('domain', 'proxy_tier'), name='probe_cache_unique_domain_tier')],
            },
        ),
    ]
