# Generated by Django 5.2.15 on 2026-06-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_probecache'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='probecache',
            name='probe_cache_unique_domain_tier',
        ),
        migrations.RemoveField(
            model_name='probecache',
            name='page_title',
        ),
        migrations.RemoveField(
            model_name='probecache',
            name='proxy_tier',
        ),
        migrations.RemoveField(
            model_name='probecache',
            name='status_code',
        ),
        migrations.AddField(
            model_name='probecache',
            name='needs_akamai_bypass',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='probecache',
            name='domain',
            field=models.CharField(db_index=True, max_length=253, unique=True),
        ),
    ]
