# Generated by Django 5.2.15 on 2026-06-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_remove_probecache_probe_cache_unique_domain_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='probecache',
            name='captcha_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('waiting_approval', 'Waiting for Approval'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('captcha_blocked', 'Captcha Blocked')], default='pending', max_length=20),
        ),
    ]
