# Generated by Django 5.2.15 on 2026-06-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0010_probecache_captcha_detected_alter_scrapejob_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('slug', models.CharField(blank=True, default='', max_length=200)),
                ('sample_url', models.URLField(blank=True, default='', max_length=1000)),
                ('input_urls', models.JSONField(blank=True, default=list)),
                ('currency', models.CharField(blank=True, default='', max_length=10)),
                ('platform', models.CharField(blank=True, default='', max_length=100)),
                ('scraping_method', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(default='new', max_length=20)),
                ('product_count', models.IntegerField(default=0)),
                ('fields_extracted', models.JSONField(blank=True, default=list)),
                ('has_scraper', models.BooleanField(default=False)),
                ('default_scraper_path', models.CharField(blank=True, default='', max_length=500)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='TrackedSite',
        ),
        migrations.AlterField(
            model_name='step',
            name='phase',
            field=models.CharField(choices=[('accessibility_check', 'Accessibility Check'), ('site_analysis', 'Site Analysis'), ('product_analysis', 'Product Analysis'), ('code_generation', 'Code Generation'), ('testing', 'Testing'), ('field_confirmation', 'Field Confirmation'), ('execution', 'Execution'), ('cleanup', 'Cleanup'), ('skill_learning', 'Skill Learning')], max_length=50),
        ),
    ]
