# Generated by Django 5.2.15 on 2026-06-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0011_site_delete_trackedsite_alter_step_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapejob',
            name='auto_queued',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='step',
            name='phase',
            field=models.CharField(choices=[('accessibility_check', 'Accessibility Check'), ('site_analysis', 'Site Analysis'), ('product_analysis', 'Product Analysis'), ('scraper_analysis', 'Scraper Analysis'), ('code_generation', 'Code Generation'), ('testing', 'Testing'), ('field_confirmation', 'Field Confirmation'), ('execution', 'Execution'), ('cleanup', 'Cleanup'), ('skill_learning', 'Skill Learning')], max_length=50),
        ),
    ]
