# Generated by Django 5.2.15 on 2026-06-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0012_scrapejob_auto_queued_alter_step_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapejob',
            name='input_mode',
            field=models.CharField(choices=[('url_list', 'URL List'), ('list_page', 'List Page'), ('navigation', 'Navigation'), ('search_term', 'Search Term')], default='url_list', max_length=15),
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='page_type',
            field=models.CharField(default='product', max_length=30),
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='search_criteria',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='site',
            name='output_schema',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='site',
            name='site_type',
            field=models.CharField(choices=[('shopping', 'Shopping'), ('articles', 'Articles'), ('jobs', 'Jobs'), ('forum', 'Forum'), ('general', 'General')], default='shopping', max_length=20),
        ),
    ]
