# Generated by Django 5.2.15 on 2026-06-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0013_scrapejob_input_mode_scrapejob_page_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='phase',
            field=models.CharField(choices=[('accessibility_check', 'Accessibility Check'), ('site_analysis', 'Site Analysis'), ('content_analysis', 'Content Analysis'), ('product_analysis', 'Product Analysis'), ('scraper_analysis', 'Scraper Analysis'), ('code_generation', 'Code Generation'), ('testing', 'Testing'), ('field_confirmation', 'Field Confirmation'), ('execution', 'Execution'), ('cleanup', 'Cleanup'), ('skill_learning', 'Skill Learning')], max_length=50),
        ),
    ]
