# Generated by Django 5.2.15 on 2026-06-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0014_alter_step_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='phase',
            field=models.CharField(choices=[('accessibility_check', 'Accessibility Check'), ('site_analysis', 'Site Analysis'), ('navigation_explore', 'Navigation Explore'), ('navigation_synthesize', 'Navigation Synthesis'), ('navigation_analysis', 'Navigation Analysis'), ('content_analysis', 'Content Analysis'), ('product_analysis', 'Product Analysis'), ('scraper_analysis', 'Scraper Analysis'), ('code_generation', 'Code Generation'), ('testing', 'Testing'), ('field_confirmation', 'Field Confirmation'), ('execution', 'Execution'), ('cleanup', 'Cleanup'), ('skill_learning', 'Skill Learning')], max_length=50),
        ),
    ]
