# Generated by Django 5.2.15 on 2026-06-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0015_navigation_phases_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPlayground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(choices=[('site_analyzer', 'Site Analyzer'), ('navigation_explore', 'Navigation Explore'), ('navigation_synthesize', 'Navigation Synthesize'), ('product_analyzer', 'Product Analyzer'), ('scraper_analyzer', 'Scraper Analyzer'), ('code_writer', 'Code Writer'), ('code_tester', 'Code Tester'), ('cleanup', 'Cleanup')], max_length=50)),
                ('prompt', models.TextField(help_text='Custom prompt for the agent')),
                ('url', models.CharField(blank=True, default='', help_text='Target URL (optional)', max_length=500)),
                ('site_slug', models.CharField(blank=True, default='', help_text='Site slug for workspace scoping', max_length=100)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('output_summary', models.TextField(blank=True, default='')),
                ('output_artifacts', models.JSONField(blank=True, default=list, help_text='Files written by the agent')),
                ('tool_call_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Agent Playground Run',
                'verbose_name_plural': 'Agent Playground',
                'ordering': ['-created_at'],
            },
        ),
    ]
