# Generated by Django 5.2.15 on 2026-06-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0016_agent_playground'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentplayground',
            name='search_criteria',
            field=models.CharField(blank=True, default='', help_text='Search criteria for navigation agents (optional)', max_length=200),
        ),
    ]
