# Generated by Django 5.2.15 on 2026-07-06 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0019_contenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('superseded', 'Superseded (job ended)')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('waiting_approval', 'Waiting for Approval'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('captcha_blocked', 'Captcha Blocked'), ('akamai_blocked', 'Akamai Blocked')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, default='', max_length=200)),
                ('site_slug', models.CharField(blank=True, default='', max_length=200)),
                ('url', models.URLField(blank=True, default='', max_length=1000)),
                ('job_source_id', models.CharField(blank=True, default='', max_length=200)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('company', models.CharField(blank=True, default='', max_length=300)),
                ('location', models.CharField(blank=True, default='', max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('salary', models.CharField(blank=True, default='', max_length=300)),
                ('job_type', models.CharField(blank=True, default='', max_length=100)),
                ('employment_type', models.CharField(blank=True, default='', max_length=100)),
                ('posted_date', models.DateField(blank=True, db_index=True, null=True)),
                ('valid_through', models.DateField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('scrape_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='scraper.scrapejob')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='scraper.site')),
            ],
            options={
                'ordering': ['-posted_date', '-scraped_at'],
                'indexes': [models.Index(fields=['posted_date'], name='scraper_job_posted__1d5361_idx'), models.Index(fields=['company'], name='scraper_job_company_4510af_idx'), models.Index(fields=['location'], name='scraper_job_locatio_422d1d_idx'), models.Index(fields=['site_slug'], name='scraper_job_site_sl_4d718d_idx')],
            },
        ),
    ]
