# Generated by Django 5.2.15 on 2026-07-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0020_joblisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='interrupt_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
