# Generated by Django 5.2.16 on 2026-07-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0021_approval_interrupt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='interrupt_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200),
        ),
    ]
