# Generated by Django 5.2.16 on 2026-07-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0022_approval_interrupt_id_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='resume_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='approval',
            name='resume_value',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
