# Generated by Django 5.2.16 on 2026-07-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0023_approval_resume_watchdog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joblisting',
            options={'ordering': ['-scraped_at', '-posted_date']},
        ),
        migrations.AddField(
            model_name='joblisting',
            name='date_posted_reliable',
            field=models.BooleanField(default=True),
        ),
    ]
