# Generated by Django 5.2.17 on 2026-08-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0031_scrapejob_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapejob',
            name='schema_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
