# Generated by Django 5.2.17 on 2026-08-24 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0032_scrapejob_schema_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapejob',
            name='created_via',
            field=models.CharField(choices=[('intake', 'Intake UI'), ('api', 'Partner API')], default='intake', max_length=10),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='search_criteria',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='url',
            field=models.URLField(max_length=1000),
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(db_index=True, max_length=8)),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_key', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobCallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('secret', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=10)),
                ('disabled_reason', models.TextField(blank=True, default='')),
                ('last_failure', models.TextField(blank=True, default='')),
                ('delivered_count', models.IntegerField(default=0)),
                ('last_delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='callback', to='scraper.scrapejob')),
            ],
        ),
        migrations.CreateModel(
            name='EventOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=26, unique=True)),
                ('event_type', models.CharField(max_length=50)),
                ('dedupe_key', models.CharField(blank=True, default='', max_length=100)),
                ('payload', models.JSONField()),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('leased', 'Leased'), ('delivered', 'Delivered'), ('permanently_failed', 'Permanently failed')], default='pending', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbox_events', to='scraper.scrapejob')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbox_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'next_attempt_at'], name='scraper_eve_state_fc8beb_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('job', 'event_type', 'dedupe_key'), name='uniq_outbox_dedupe')],
            },
        ),
    ]
