# Generated by Django 5.2.17 on 2026-09-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0036_scrapejob_redispatch_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapejob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('waiting_approval', 'Waiting for Approval'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('captcha_blocked', 'Captcha Blocked'), ('akamai_blocked', 'Akamai Blocked'), ('browser_unavailable', 'Browser Service Unavailable')], default='pending', max_length=20),
        ),
    ]
