#!/usr/bin/env python3
"""
API Scraper for Frank Body (frankbody.com) — Shopify product JSON endpoints.

Phase 1 discovery paginates the Shopify listing JSON
(/collections/{handle}/products.json via the promoted listing, self-healing
to the full-catalog /products.json on zero yield). Phase 2 fetches each
item's /products/{handle}.json payload — decimal-string price + price_currency.

NOTE: the analyzer-captured /api/unstable/graphql.json endpoint is dead
without a query string (bare GET -> {"message": "No query string was
present"}); the standard unauthenticated Shopify endpoints were verified
live and are used instead.

Generated by Code Writer Agent for Universal Ecommerce Scraper.

Usage:
    python3 scraper_draft.py                    # reads input_urls.json from same folder
    python3 scraper_draft.py --input urls.json  # explicit input file
    python3 scraper_draft.py --urls url1 url2   # URLs as CLI arguments
    python3 scraper_draft.py --fresh-discovery  # re-paginate the listing API
"""

import argparse
import json
import logging
import os
import re
import sys
import time
from datetime import datetime, timezone
from typing import Optional
from urllib.parse import urljoin, urlparse

import requests

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from src.proxy import ProxyConfig  # noqa: F401  (tier ladder lives in src.http_fetch now)

# ═══════════════════════════════════════════════════════════════════════════════
# CONFIGURATION
# ═══════════════════════════════════════════════════════════════════════════════

SITE_NAME = "Frank Body"
SITE_URL = "https://frankbody.com"
PLATFORM = "shopify"
SCRAPING_METHOD = "internal_api"
SITE_SLUG = "frankbody-com"

# Code Writer adapted: Shopify listing JSON replaces the dead graphql endpoint.
# CATALOG_ENDPOINT is the zero-yield self-heal target (rule 5).
API_BASE_URL = "https://frankbody.com"
CATALOG_ENDPOINT = "/products.json"
DEFAULT_LISTING_URL = "https://frankbody.com/collections/deodorants"
API_PRODUCTS_ENDPOINT = CATALOG_ENDPOINT  # resolved per-run by _set_listing_endpoint()
ACTIVE_LISTING_URL = DEFAULT_LISTING_URL
API_KEY = None
API_HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Accept": "application/json",
    "Content-Type": "application/json",
}
if API_KEY:
    API_HEADERS["Authorization"] = f"Bearer {API_KEY}"

PAGINATION_TYPE = "page"  # Shopify listing JSON: ?limit=N&page=M
PAGE_SIZE = 250  # Shopify's MAX page size — full extraction, no item cap
DELAY_BETWEEN_REQUESTS = 1.0
MAX_RETRIES = 3

# Code Writer adapted: /products/{handle} is the canonical item URL shape.
PRODUCT_HANDLE_RE = re.compile(r"/products/([a-z0-9-]+)")

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

# Code Writer adapted: the shared soft-block BYTE FLOOR is calibrated for HTML
# listing bodies ("no real listing is that small") and mis-fires on legitimately
# small JSON API payloads — measured live: a clean 200 for a single-variant
# Shopify /products/{handle}.json is ~4.6KB, which tripped `under_min_bytes`
# and would have burned the whole proxy ladder against a no-anti-bot site
# (exactly the wave-20 damage class the module docstring documents). The env
# is read per call, so pinning it to "0" for this process disables ONLY the
# size heuristic; the ladder, retries, hard-block escalation and fingerprint
# tier all stay. Challenge shapes remain caught for free: a challenge body is
# HTML and fails json.loads inside fetch_json -> honest None.
os.environ["SCRAPER_SOFT_BLOCK_MIN_BYTES"] = "0"

# Unique per process: a second-resolution timestamp collides when two runs
# of this draft start in the same second (job-71 popsockets — the discovery
# run's empty products array overwrote the passing extraction result).
TIMESTAMP = datetime.now(timezone.utc).strftime("%Y-%m-%d_%H%M%S_%f")
OUTPUT_FILE = os.path.join(SCRIPT_DIR, f"output_{TIMESTAMP}_{os.getpid()}.json")
INPUT_FILE = os.path.join(SCRIPT_DIR, "input_urls.json")
LOG_FILE = os.path.join(os.path.dirname(SCRIPT_DIR), "logs", f"{SITE_SLUG}.log")

# ═══════════════════════════════════════════════════════════════════════════════
# LOGGING
# ═══════════════════════════════════════════════════════════════════════════════

os.makedirs(os.path.dirname(LOG_FILE), exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[
        logging.FileHandler(LOG_FILE),
        logging.StreamHandler(),
    ],
)
logger = logging.getLogger(__name__)

proxy_config = ProxyConfig.get_instance()


# ═══════════════════════════════════════════════════════════════════════════════
# INPUT HANDLING
# ═══════════════════════════════════════════════════════════════════════════════

def load_urls_from_file(filepath: str) -> list[str]:
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data.get("urls", [])


def save_urls_to_file(filepath: str, urls: list[str]) -> None:
    # [job-77] A 0-URL discovery must not DESTROY an existing seed file: the
    # adoreme execution discovered 0 under a PDP listing and left a 16-byte
    # {"urls": []} as the site's canonical input_urls.json. Skip the empty
    # overwrite when a seed already exists; a non-empty refresh still writes.
    if not urls and os.path.exists(filepath):
        logger.warning(f"Refusing to overwrite {filepath} with an empty URL list")
        return
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump({"urls": urls}, f, indent=2, ensure_ascii=False)
    logger.info(f"Saved {len(urls)} URLs to {filepath}")


# ═══════════════════════════════════════════════════════════════════════════════
# API FUNCTIONS
# ═══════════════════════════════════════════════════════════════════════════════

def fetch_api(endpoint: str, params: Optional[dict] = None):
    """Phase-1 API fetch — rides the SAME shared ladder as Phase 2 [T1.3].

    ``_get_fetch_json`` carries ``detect_soft_block`` + real tier escalation
    on one persistent session. Returns the parsed payload, a SoftBlock
    signal (challenge served as 200 — falsy on purpose), or None when every
    tier failed. Falls back to a bare GET only when the image predates the
    module.
    """
    url = f"{API_BASE_URL}{endpoint}"
    try:
        return _get_fetch_json()(url, params=params)
    except ImportError:
        logger.warning("src.http_fetch unavailable — falling back to a bare GET")
        try:
            response = requests.get(url, params=params, headers=API_HEADERS, timeout=15)
            response.raise_for_status()
            return response.json()
        except Exception as e:
            logger.error(f"API request failed: {e}")
            return None


# ── FIELD NORMALIZERS — inline on purpose, NOT a src import ──────────────────
# Drafts execute in the browser-service image: a NEW src import would ImportError
# there until that image is rebuilt, so the ~25 lines live in each python-side
# template verbatim (playwright/UC normalize in-page via JS and don't need them).

def _norm_price(value) -> Optional[float]:
    """Strip currency symbols/whitespace from a price.

    "£1,234.56" → 1234.56 (a float), "1.234,56 €" → 1234.56, 24.99 (a
    JSON-LD number) → 24.99. Returns None when no digits are present — an
    unparseable price is EMPTY, never zero (0 would read as a real product
    priced at nothing). The currency stays in its own ``currency`` field.
    """
    if value is None:
        return None
    cleaned = re.sub(r"[^\d.,-]", "", str(value).strip())
    if not re.search(r"\d", cleaned):
        return None
    if "," in cleaned and "." in cleaned:
        # Both separators present: whichever comes LAST is the decimal one.
        if cleaned.rfind(",") > cleaned.rfind("."):
            cleaned = cleaned.replace(".", "").replace(",", ".")
        else:
            cleaned = cleaned.replace(",", "")
    elif "," in cleaned:
        # "1,234" (grouping) vs "1,5" (decimal comma): a comma followed by
        # exactly three digits is grouping, anything else is a decimal comma.
        cleaned = re.sub(r",(?=\d{3}(?:\D|$))", "", cleaned).replace(",", ".")
    try:
        return float(cleaned)
    except ValueError:
        return None


def _norm_availability(value) -> Optional[str]:
    """Normalize availability to ``in_stock`` / ``out_of_stock``.

    Accepts the schema.org URI form, InStock / In Stock / in_stock / Available
    and their negatives. Anything unrecognised passes through lowercased —
    availability is never invented (an unknown state is data, not an error).
    """
    if value is None:
        return None
    if isinstance(value, bool):
        return "in_stock" if value else "out_of_stock"
    text = str(value).strip().lower()
    if not text:
        return None
    if "://" in text:  # e.g. http://schema.org/InStock
        text = text.rsplit("/", 1)[-1]
    compact = text.replace("-", "_").replace(" ", "")
    if compact in ("in_stock", "instock", "available"):
        return "in_stock"
    if compact in ("out_of_stock", "outofstock", "unavailable", "sold_out", "soldout"):
        return "out_of_stock"
    return text


def _product_handle(url: str) -> str:
    """Code Writer adapted: extract the Shopify handle from any product URL."""
    m = PRODUCT_HANDLE_RE.search(url or "")
    return m.group(1) if m else ""


def _set_listing_endpoint(listing_url: str) -> str:
    """Code Writer adapted: resolve the Phase-1 Shopify JSON endpoint from the
    listing URL (--listing-url / SCRAPER_LISTING_URL / promoted default).
    A /collections/{handle} listing maps to its products.json; anything else
    falls back to the full-catalog /products.json."""
    global API_PRODUCTS_ENDPOINT, ACTIVE_LISTING_URL
    listing = (listing_url or "").strip() or DEFAULT_LISTING_URL
    ACTIVE_LISTING_URL = listing
    path = urlparse(listing).path or "/"
    m = re.search(r"/collections/([a-z0-9-]+)", path)
    if m:
        endpoint = f"/collections/{m.group(1)}/products.json"
    elif path.endswith("products.json"):
        endpoint = path
    else:
        endpoint = CATALOG_ENDPOINT
    API_PRODUCTS_ENDPOINT = endpoint
    return endpoint


def transform_api_product(api_product: dict, index: int, src_url: str) -> dict:
    """Code Writer adapted: Frank Body (Shopify) field map — user-requested
    fields ONLY (product name, price, currency, availability) + bookkeeping.

    PRIMARY (.json): variants[*].price is a decimal STRING in major units
    ('18.00') — run through _norm_price, multi-variant products aggregate to
    min(variants[*].price). Currency is the payload's price_currency ('AUD',
    verified live). Availability: in_stock when ANY variant is sellable.
    """
    data = api_product if isinstance(api_product, dict) else {}
    product = data.get("product") or data  # .json wraps in {"product": ...}; .js is flat
    variants = product.get("variants") or []

    prices: list[float] = []
    currency = ""
    any_sellable: Optional[bool] = None
    for v in variants:
        if not isinstance(v, dict):
            continue
        p = _norm_price(v.get("price"))
        if p is not None:
            prices.append(p)
        if not currency:
            currency = str(v.get("price_currency") or v.get("currency") or "").strip().upper()
        # Code Writer adapted: this store's .json omits the `available` boolean,
        # so sellability falls back to Shopify's own availability rule — a
        # variant is sellable when its inventory is UNTRACKED (no
        # inventory_management), its policy is 'continue' (sell when out of
        # stock), or tracked stock is > 0. An explicit boolean, when present,
        # wins for that variant.
        if isinstance(v.get("available"), bool):
            sellable: Optional[bool] = v["available"]
        else:
            tracked = v.get("inventory_management") not in (None, "", "null")
            qty = v.get("inventory_quantity")
            sellable = (
                not tracked
                or str(v.get("inventory_policy") or "").lower() == "continue"
                or (isinstance(qty, (int, float)) and qty > 0)
            )
        if sellable is not None:
            any_sellable = bool(any_sellable) or bool(sellable)
    price = min(prices) if prices else _norm_price(product.get("price"))
    if not currency:
        currency = str(product.get("price_currency") or product.get("currency") or "").strip().upper()
    if any_sellable is None and isinstance(product.get("available"), bool):
        any_sellable = product["available"]
    availability = _norm_availability(any_sellable)

    handle = product.get("handle") or _product_handle(src_url)
    url = urljoin(SITE_URL, f"/products/{handle}") if handle else (product.get("url") or src_url)

    return {
        "id": index,
        "title": (product.get("title") or "").strip(),
        # Symbol-free numeric price: baking "$" into the field makes every
        # downstream numeric comparison (and currency inference) wrong.
        "price": price,
        "currency": currency,
        "availability": availability,
        "url": url,
        "src_url": src_url,
        "status_code": 200,
        "scraped_at": datetime.now(timezone.utc).isoformat(),
        "remarks": "",
    }


def transform_api_jobs(raw_jobs: list[dict], src_url: str = "") -> list[dict]:
    """JOB boards: map raw API items to standard job fields using the GENERIC
    resolver in ``src.job_fields``.  Do NOT hardcode site-specific field names —
    ``map_jobs`` infers each field's source path (title, company, location,
    description, salary, job_type, posted_date, apply_url, requirements) by
    coverage over the batch, so the SAME code works across job platforms.
    Use this in place of ``transform_api_product`` when scraping job postings.
    """
    from src.job_fields import map_jobs

    if not raw_jobs:
        return []
    jobs = map_jobs(sample_items=raw_jobs, raw_items=raw_jobs)
    now = datetime.now(timezone.utc).isoformat()
    for idx, j in enumerate(jobs, start=1):
        j.setdefault("id", idx)
        if src_url:
            j.setdefault("src_url", src_url)
        j.setdefault("status_code", 200)
        j.setdefault("scraped_at", now)
        j.setdefault("remarks", "")
    return jobs


def fetch_all_products_via_api() -> tuple[list[str], list[dict]]:
    all_products = []
    offset = 0
    cursor = None
    page = 1

    # [T0.5] Why discovery stopped — emitted as metadata.discovery_coverage
    # so the tester's coverage gate and the execution-time strategy+tier
    # recycle can tell an anti-bot wall from a genuine catalog end.
    # Vocabulary matches the FAIL-class set the gates know:
    #   empty_first_page — a 200 challenge wall yielded zero items (job-58)
    #   navigate_error   — the ladder was exhausted / transport failure
    #   no_next_link     — normal exhaustion (short page / total / cursor end)
    global _DISCOVERY_META, API_PRODUCTS_ENDPOINT
    _DISCOVERY_META = {
        "stop_reason": "no_next_link",
        "ran_phase1": True,
        "skipped_reason": "",
        "discovered_urls": 0,
        "pages_fetched": 0,
        "soft_block_escalations": 0,
        "max_pages_hit": False,
    }

    logger.info(
        f"Discovering via {API_BASE_URL}{API_PRODUCTS_ENDPOINT} "
        f"(listing: {ACTIVE_LISTING_URL})"
    )

    while True:
        if PAGINATION_TYPE == "offset":
            params = {"limit": PAGE_SIZE, "offset": offset}
        elif PAGINATION_TYPE == "page":
            params = {"limit": PAGE_SIZE, "page": page}
        elif PAGINATION_TYPE == "cursor":
            params = {"limit": PAGE_SIZE, "cursor": cursor} if cursor else {"limit": PAGE_SIZE}
        else:
            params = {"limit": PAGE_SIZE}

        logger.info(f"Fetching API page {page}: {API_PRODUCTS_ENDPOINT}")
        result = fetch_api(API_PRODUCTS_ENDPOINT, params=params)

        # fetch_api contract [T1.3]: (payload, status) on success, SoftBlock
        # on a challenge-served-as-200, None when every tier failed.
        if isinstance(result, SoftBlock):
            logger.error(
                f"Discovery page {page}: challenge served as 200 "
                f"({getattr(result, 'reason', '?')}) — every ladder tier "
                f"returned a challenge"
            )
            _DISCOVERY_META["soft_block_escalations"] += 1
            # A wall yielding zero items is the job-58 shape, not a
            # catalog end — only page 1's wall sets the zero-URL reason.
            if page == 1:
                _DISCOVERY_META["stop_reason"] = "empty_first_page"
            break
        if not result:
            logger.error(f"Discovery page {page}: every ladder tier failed")
            if page == 1:
                _DISCOVERY_META["stop_reason"] = "navigate_error"
            break

        data = result[0]
        _DISCOVERY_META["pages_fetched"] = page

        if not data:
            break

        products = data.get("products", []) or data.get("items", []) or data.get("data", [])
        if isinstance(data, list):
            products = data

        for raw in products:
            all_products.append(raw)

        logger.info(f"Page {page}: {len(products)} products (total: {len(all_products)})")

        # Stop when a page is short (exhausted) OR we've hit the API's reported total.
        if len(products) < PAGE_SIZE:
            break
        total = (
            data.get("totalCount") or data.get("total_count") or data.get("count")
            or data.get("total") or data.get("totalResults") or data.get("totalJobs")
        )
        if isinstance(total, int) and total > 0 and len(all_products) >= total:
            break

        if PAGINATION_TYPE == "cursor":
            cursor = data.get("next_cursor") or data.get("cursor")
            if not cursor:
                break
        elif PAGINATION_TYPE == "offset":
            offset += PAGE_SIZE
        # page-based: single increment below (do NOT increment twice)
        page += 1

    # Code Writer adapted: Shopify rows carry a `handle`, not a `url` — build
    # canonical absolute /products/{handle} URLs via urljoin (never string
    # concatenation onto a base path).
    urls: list[str] = []
    seen: set[str] = set()
    for p in all_products:
        row = p if isinstance(p, dict) else {}
        handle = row.get("handle") or _product_handle(row.get("url", "") or "")
        if not handle:
            continue
        u = urljoin(SITE_URL, f"/products/{handle}")
        if u in seen:
            continue
        seen.add(u)
        urls.append(u)
    _DISCOVERY_META["discovered_urls"] = len(urls)

    # Zero-yield self-heal: a missing/empty collection endpoint must not end
    # the run at 0 item URLs — retry ONCE against the full-catalog endpoint.
    if not urls and API_PRODUCTS_ENDPOINT != CATALOG_ENDPOINT:
        logger.warning(
            f"0 item URLs from {API_BASE_URL}{API_PRODUCTS_ENDPOINT} — "
            f"retrying once with {CATALOG_ENDPOINT}"
        )
        API_PRODUCTS_ENDPOINT = CATALOG_ENDPOINT
        return fetch_all_products_via_api()

    return urls, all_products


# [wave-15 3.4] Per-item fetch closure — ONE per process (the Session must
# persist across items for cookie continuity, job-58).
_FETCH_JSON = None

# [T0.5] Phase-1 discovery outcome, filled by fetch_all_products_via_api and
# emitted as metadata.discovery_coverage (the block the tester's coverage
# gate and the execution-time recycle read).
_DISCOVERY_META: dict = {
    "stop_reason": "skipped",
    "ran_phase1": False,
    "skipped_reason": "seeded_input",
    "discovered_urls": 0,
    "pages_fetched": 0,
    "soft_block_escalations": 0,
    "max_pages_hit": False,
}

try:  # guarded: the browser-service image may predate src.http_fetch
    from src.http_fetch import SoftBlock  # noqa: E402
except ImportError:  # pragma: no cover
    class SoftBlock:  # type: ignore[no-redef]
        """Image predates the shared module — no signal can ever occur."""

        def __init__(self, *a, **k):
            self.reason = "unavailable"

        def __bool__(self):
            return False


def _get_fetch_json():
    global _FETCH_JSON
    if _FETCH_JSON is None:
        from src.http_fetch import create_fetch_json

        _FETCH_JSON = create_fetch_json(
            delay_s=DELAY_BETWEEN_REQUESTS, headers=API_HEADERS
        )
    return _FETCH_JSON


def _product_json_url(url: str) -> str:
    """Code Writer adapted: map a product page URL to its .json endpoint."""
    if url.endswith(".json") and "/products/" in url:
        return url
    handle = _product_handle(url)
    if not handle:
        return url  # let the fetch fail loudly and be logged
    return urljoin(SITE_URL, f"/products/{handle}.json")


def _product_js_url(url: str) -> str:
    """Code Writer adapted: the .js fallback endpoint for the same handle."""
    if url.endswith(".json") and "/products/" in url:
        return url[: -len(".json")] + ".js"
    handle = _product_handle(url)
    if not handle:
        return url
    return urljoin(SITE_URL, f"/products/{handle}.js")


def _fetch_json_or_none(url: str):
    """Code Writer adapted: one ladder fetch -> (payload, status) | None.

    Every HTTP call rides the shared ladder (proxy path preserved); the bare
    GET exists only when the execution image predates src.http_fetch.
    """
    try:
        return _get_fetch_json()(url)
    except ImportError:
        logger.warning("src.http_fetch unavailable — falling back to a bare GET")
    except Exception as e:
        logger.error(f"Request failed for {url}: {e}")
        return None
    try:
        response = requests.get(url, headers=API_HEADERS, timeout=15)
        response.raise_for_status()
        return (response.json(), response.status_code)
    except Exception as e:
        logger.error(f"Request failed for {url}: {e}")
        return None


def _record_from_payload(data, status: int, src_url: str, api_url: str = "") -> Optional[dict]:
    """Code Writer adapted: map a fetched payload to the output record.

    .json shape: {"product": {...}} — decimals + price_currency, used as-is.
    .js shape (FALLBACK): flat object, price in CENTS — divide by 100 before
    mapping; .js exposes NO currency, so that stays empty and is noted.
    """
    if not isinstance(data, dict):
        return None
    product = data.get("product")
    if isinstance(product, dict) and product:
        record = transform_api_product(data, 0, src_url)
        record["status_code"] = status
        # Code Writer adapted: if .json yielded no derivable availability, top
        # up from the flat .js endpoint for the same handle (its `available`
        # boolean is verified on this store).
        if record.get("availability") is None and api_url:
            js_result = _fetch_json_or_none(_product_js_url(api_url))
            if isinstance(js_result, (tuple, list)) and len(js_result) == 2:
                js = js_result[0] if isinstance(js_result[0], dict) else {}
                if isinstance(js.get("available"), bool):
                    record["availability"] = _norm_availability(js["available"])
        return record
    if data.get("title"):  # flat .js payload
        js = dict(data)
        for key in ("price", "price_min", "price_max"):
            if isinstance(js.get(key), int):
                js[key] = round(js[key] / 100.0, 2)
        for v in js.get("variants") or []:
            if isinstance(v, dict) and isinstance(v.get("price"), int):
                v["price"] = round(v["price"] / 100.0, 2)
        record = transform_api_product({"product": js}, 0, src_url)
        record["status_code"] = status
        if not record.get("currency"):
            record["remarks"] = "currency absent on .js fallback payload"
        return record
    return None


def scrape_product(url: str, src_url: str) -> Optional[dict]:
    """Phase-2 item fetch: GET /products/{handle}.json (field map PRIMARY).

    Falls back to /products/{handle}.js (price in CENTS -> /100) when the
    .json endpoint yields nothing. No payload from either endpoint is a soft
    404 — the item is logged and dropped, never fabricated.
    """
    try:
        time.sleep(DELAY_BETWEEN_REQUESTS)
        api_url = _product_json_url(url)
        result = _fetch_json_or_none(api_url)
        if isinstance(result, SoftBlock):
            logger.error(f"Challenge served for {url} ({getattr(result, 'reason', '?')})")
            return None
        if not result:
            result = _fetch_json_or_none(_product_js_url(url))
        if isinstance(result, SoftBlock):
            logger.error(f"Challenge served for {url} ({getattr(result, 'reason', '?')})")
            return None
        if not result:
            logger.warning(f"Soft 404: product not found ({url}) — no JSON from .json/.js")
            return None
        data, status = result
        record = _record_from_payload(data, status, src_url, api_url=api_url)
        if record is None:
            logger.warning(
                f"Soft 404: product not found ({url}) — HTTP {status} payload had no product"
            )
            return None
        return record
    except Exception as e:
        logger.error(f"Failed to scrape {url}: {e}")
        return None


# ═══════════════════════════════════════════════════════════════════════════════
# OUTPUT BUILDERS
# ═══════════════════════════════════════════════════════════════════════════════

def _build_output(results: list, failed: int, start_time: float, phase: str,
                  discovered_raw: int) -> dict:
    """Code Writer adapted: single output builder (extraction + discovery-only)
    with the coverage block the tester's gates read."""
    return {
        "site": {
            "name": SITE_NAME,
            "url": SITE_URL,
            "platform": PLATFORM,
            "scraping_method": SCRAPING_METHOD,
            "scraped_at": datetime.now(timezone.utc).isoformat(),
        },
        "products": results,
        "metadata": {
            # job-76 myhouse: lets every consumer tell a discovery artifact
            # (URL stubs, no fields) from an extraction result.
            "phase": phase,
            "scraping_duration_seconds": round(time.time() - start_time, 2),
            "failed_products": failed,
            "rate_limit_delay": DELAY_BETWEEN_REQUESTS,
            "discovered_urls": discovered_raw,
            "pages_fetched": _DISCOVERY_META.get("pages_fetched", 0),
            "total_discovered": _DISCOVERY_META.get("discovered_urls", 0),
            # [T0.5] Always emitted so the gates read a uniform schema
            # regardless of which path produced the output.
            "discovery_coverage": {
                **_DISCOVERY_META,
                "found": len(results),
            },
        },
    }


def _write_output(output: dict) -> None:
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(output, f, indent=2, ensure_ascii=False)


# ═══════════════════════════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════════════════════════

# ── CLI CONTRACT — keep every line below when adapting ───────────────────────
# The pipeline launches this scraper with EXACTLY these names. A flag missing
# from the argparse below is STRIPPED at launch and discovery silently falls
# back to the seed file (input_urls.json). ADD flags if you need them; NEVER
# remove or rename:
#   --fresh-discovery  the ONLY discovery trigger for the api family (execution
#                      always passes it) — there is NO listing page; discovery
#                      IS the API. SCRAPER_LISTING_URL / SCRAPER_FORCE_DISCOVERY
#                      are the env gates.
#   --discover-only    discovery flag: Phase 1 MUST run and re-discover.
#   --listing-url      discovery flag: listing/collection URL to discover from.
#   --input/--sample/--limit  testing
# Source of truth: webapp/agents/constants.py
# ──────────────────────────────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser(description=f"API scraper for {SITE_NAME}")
    parser.add_argument("--sample", action="store_true", help="Scrape only 5 products")
    parser.add_argument("--limit", type=int, default=None, help="Max products to scrape")
    parser.add_argument("--input", type=str, default=None, help="Path to input URLs JSON file")
    parser.add_argument("--urls", nargs="+", default=None, help="Product URLs as arguments")
    parser.add_argument("--fresh-discovery", action="store_true",
                        help="Bypass input_urls.json and rediscover via API pagination")
    # Code Writer adapted: hard-contract discovery flags for this list_page job.
    parser.add_argument("--discover-only", action="store_true",
                        help="Run Phase 1 discovery only: re-discover, save URLs, skip extraction")
    parser.add_argument("--listing-url", type=str, default=None,
                        help="Listing/collection URL to discover from (falls back to SCRAPER_LISTING_URL)")
    parser.add_argument("--no-proxy", action="store_true",
                        help="Force direct HTTP (no proxy tiers) — already the default for this site")
    args = parser.parse_args()

    if args.input:
        # [job-60 zquiet] The runner's CWD is not the scraper's directory
        # (the tester passes `--input input_urls.json` while CWD=/app), so a
        # relative seed-file value must resolve against the scraper's own
        # directory. os.path.join passes absolute paths through untouched.
        args.input = os.path.join(SCRIPT_DIR, args.input)

    # HARD CONTRACT: env listing read BEFORE the seed-file gate — execution
    # sets SCRAPER_LISTING_URL, not a CLI flag. It selects the Phase-1
    # endpoint (collection products.json) and forces fresh discovery.
    _env_listing = os.environ.get("SCRAPER_LISTING_URL", "").strip()
    _resolved = _set_listing_endpoint(args.listing_url or _env_listing)

    start_time = time.time()

    logger.info("=" * 80)
    logger.info(f"Starting API scraper for {SITE_NAME}")
    logger.info(f"Site: {SITE_URL}")
    logger.info(f"API: {API_BASE_URL}{API_PRODUCTS_ENDPOINT} (listing: {ACTIVE_LISTING_URL})")
    if args.no_proxy:
        logger.info("--no-proxy: direct HTTP only (no proxy tiers) — default for this site")
    logger.info(f"Output: {OUTPUT_FILE}")
    logger.info("=" * 80)

    product_urls = []
    raw_products = []
    src_url = f"{API_BASE_URL}{API_PRODUCTS_ENDPOINT}"
    _from_seed = False

    # F6: run_execution always passes --fresh-discovery for nav jobs; declaring
    # it here means the CLI-contract guard passes it through (declared flags
    # are never stripped) and the seed-file branch can't suppress API
    # pagination. --discover-only is a discovery flag too: when passed, Phase 1
    # MUST run and re-discover regardless of any seed file [jobs 359/360].
    _force_fresh = (
        args.fresh_discovery
        or args.discover_only
        or bool(_env_listing)
        or bool(os.environ.get("SCRAPER_FORCE_DISCOVERY", "").strip())
    )
    if args.urls and not _force_fresh:
        product_urls = args.urls
        _from_seed = True
    elif args.input and not _force_fresh:
        product_urls = load_urls_from_file(args.input)
        _from_seed = True
    elif os.path.exists(INPUT_FILE) and not _force_fresh:
        product_urls = load_urls_from_file(INPUT_FILE)
        _from_seed = True
    else:
        logger.info(
            "Fresh discovery (%s): paginating Shopify listing JSON %s",
            "flag" if (args.fresh_discovery or args.discover_only) else "env",
            _resolved,
        )
        product_urls, raw_products = fetch_all_products_via_api()
        save_urls_to_file(INPUT_FILE, product_urls)
        # Re-resolve: the zero-yield self-heal may have switched the endpoint.
        src_url = f"{API_BASE_URL}{API_PRODUCTS_ENDPOINT}"
        # Code Writer adapted: decimal price + price_currency are verified ONLY
        # on the per-item /products/{handle}.json payload (listing rows carry
        # integer cents and no currency) — drop the rows so Phase 2 fetches
        # every item uniformly through scrape_product().
        raw_products = []

    # [T0.5] Raw pre-cut count — --sample/--limit truncate product_urls below,
    # and the coverage block must report what DISCOVERY found, not what
    # survived the sampling.
    discovered_urls_raw = len(product_urls)

    if args.discover_only:
        save_urls_to_file(INPUT_FILE, product_urls)
        output = _build_output([], 0, start_time, "discovery", discovered_urls_raw)
        _write_output(output)
        logger.info(
            f"Discovery-only complete: {discovered_urls_raw} URLs via "
            f"{API_BASE_URL}{API_PRODUCTS_ENDPOINT} -> {OUTPUT_FILE}"
        )
        return

    if args.sample:
        product_urls = product_urls[:5]
    if args.limit:
        product_urls = product_urls[: args.limit]

    logger.info(f"Total products to scrape: {len(product_urls)}")

    results = []
    failed = 0

    if raw_products and len(raw_products) == len(product_urls):
        for i, raw in enumerate(raw_products[: len(product_urls)]):
            try:
                product = transform_api_product(raw, i + 1, src_url)
                results.append(product)
            except Exception as e:
                logger.error(f"Error transforming product {i + 1}: {e}")
                failed += 1
    else:
        for i, url in enumerate(product_urls):
            try:
                # src_url discipline: seeded items carry their own URL;
                # discovered items carry the listing/API query URL.
                item_src = url if _from_seed else src_url
                product = scrape_product(url, item_src)
                if product and product.get("title") and (
                    product.get("price") is not None or product.get("availability")
                ):
                    product["id"] = i + 1
                    results.append(product)
                else:
                    # Output contract: drop items missing title + a core field
                    # (soft-404 stubs land here — logged, never emitted).
                    failed += 1
                    if product:
                        logger.warning(
                            f"Dropped {url}: {product.get('remarks') or 'missing title/price'}"
                        )
                    else:
                        logger.warning(f"Dropped {url}: fetch failed (possible soft 404)")
            except Exception as e:
                logger.error(f"Error processing {url}: {e}")
                failed += 1

            if (i + 1) % 25 == 0:
                percent = ((i + 1) / len(product_urls)) * 100
                logger.info(f"Progress: [{i + 1}/{len(product_urls)}] ({percent:.1f}%)")

    output = _build_output(results, failed, start_time, "extraction", discovered_urls_raw)
    _write_output(output)

    logger.info("=" * 80)
    logger.info("EXTRACTION COMPLETE")
    logger.info(f"Total: {len(results)}, Failed: {failed}")
    logger.info(f"Duration: {round(time.time() - start_time, 2)}s")
    logger.info(f"Output: {OUTPUT_FILE}")
    logger.info("=" * 80)


if __name__ == "__main__":
    main()
