#!/usr/bin/env python3
"""
Akamai Stealth Scraper Template

Uses the 3-layer Akamai bypass (TLS → Playwright stealth → UC Chrome)
for sites protected by Akamai Bot Manager.

Generated by Code Writer Agent for Universal Ecommerce Scraper.

Usage:
    python3 scraper.py                    # reads input_urls.json from same folder
    python3 scraper.py --input urls.json  # explicit input file
    python3 scraper.py --urls url1 url2     # URLs as CLI arguments
    python3 scraper.py --sample            # scrape only 5 products
"""

import argparse
import asyncio
import json
import logging
import os
import re
import sys
import time
from datetime import datetime, timezone
from html import unescape
from typing import Optional

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))

from src.akamai_bypass.config import build_akamai_config_from_proxy_tier
from src.akamai_bypass.orchestrator import AkamaiOrchestrator
from src.page_analysis import extract_jsonld

# ═══════════════════════════════════════════════════════════════════════════════
# CONFIGURATION - Update these values
# ═══════════════════════════════════════════════════════════════════════════════

SITE_NAME = "{SITE_NAME}"
SITE_URL = "{SITE_URL}"
PLATFORM = "{PLATFORM}"
SCRAPING_METHOD = "akamai_stealth"
SITE_SLUG = "{SITE_SLUG}"

PRODUCT_LISTING_URL = "{PRODUCT_LISTING_URL}"
SRC_URL = "{PRODUCT_LISTING_URL}"
DELAY_BETWEEN_REQUESTS = {DELAY_BETWEEN_REQUESTS}
PROXY_TIER = "{PROXY_TIER}"

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
TIMESTAMP = datetime.now(timezone.utc).strftime("%Y-%m-%d_%H%M%S")
OUTPUT_FILE = os.path.join(SCRIPT_DIR, f"output_{TIMESTAMP}.json")
INPUT_FILE = os.path.join(SCRIPT_DIR, "input_urls.json")
LOG_FILE = os.path.join(os.path.dirname(SCRIPT_DIR), "logs", f"{SITE_SLUG}.log")

# ═══════════════════════════════════════════════════════════════════════════════
# LOGGING
# ═══════════════════════════════════════════════════════════════════════════════

os.makedirs(os.path.dirname(LOG_FILE), exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[
        logging.FileHandler(LOG_FILE),
        logging.StreamHandler(),
    ],
)
logger = logging.getLogger(__name__)


# ═══════════════════════════════════════════════════════════════════════════════
# HELPERS
# ═══════════════════════════════════════════════════════════════════════════════

def clean_html(html_str: str) -> str:
    if not html_str:
        return ""
    text = re.sub(r"<[^>]+>", " ", html_str)
    text = unescape(text)
    return re.sub(r"\s+", " ", text).strip()


EXTRACT_PRODUCT_JS = """
(src_url) => {
    const product = {
        title: '',
        price: '',
        availability: '',
        original_price: '',
        currency: '',
        url: window.location.href,
        src_url: src_url || '',
        location: '',
        remarks: ''
    };

    const jsonldScripts = document.querySelectorAll('script[type="application/ld+json"]');
    let jsonld = null;
    for (const script of jsonldScripts) {
        try {
            const data = JSON.parse(script.textContent);
            if (data['@type'] === 'Product') { jsonld = data; break; }
            if (Array.isArray(data)) {
                for (const item of data) {
                    if (item['@type'] === 'Product') { jsonld = item; break; }
                }
            }
            if (jsonld) break;
        } catch(e) {}
    }

    product.title = jsonld?.name ||
        document.querySelector('{TITLE_SELECTOR}')?.textContent?.trim() || '';

    if (jsonld?.offers) {
        const offers = Array.isArray(jsonld.offers) ? jsonld.offers[0] : jsonld.offers;
        product.price = offers?.price || '';
        const highPrice = offers?.highPrice || '';
        if (highPrice && parseFloat(highPrice) > parseFloat(product.price || 0)) {
            product.original_price = highPrice;
        }
        product.currency = offers?.priceCurrency || 'USD';
        const avail = offers?.availability || '';
        product.availability = avail.includes('InStock') ? 'In Stock' : 'Out of Stock';
    } else {
        const priceEl = document.querySelector('{PRICE_SELECTOR}');
        product.price = priceEl?.textContent?.trim() || '';
        const origEl = document.querySelector('{ORIGINAL_PRICE_SELECTOR}');
        product.original_price = origEl?.textContent?.trim() || '';
        const stockEl = document.querySelector('{AVAILABILITY_SELECTOR}');
        if (stockEl) {
            const t = stockEl.textContent.toLowerCase();
            product.availability = t.includes('in stock') ? 'In Stock' : 'Out of Stock';
        }
    }

    return product;
}
"""

EXTRACT_PRODUCT_URLS_JS = """
() => {
    const links = document.querySelectorAll('{PRODUCT_LINK_SELECTOR}');
    const unique = new Set();
    links.forEach(a => {
        let href = a.getAttribute('href');
        if (href) {
            if (!href.startsWith('http')) {
                href = window.location.origin + href;
            }
            unique.add(href);
        }
    });
    return Array.from(unique);
}
"""


async def scrape_product(orchestrator: AkamaiOrchestrator, url: str, src_url: str, index: int) -> Optional[dict]:
    result = await orchestrator.probe(url)
    if not result or not result.get("html"):
        logger.error("Akamai bypass failed for %s", url[:100])
        return None

    html = result["html"]
    jsonld_blocks = extract_jsonld(html)
    product_data = {"title": "", "price": "", "availability": "", "original_price": "", "currency": ""}

    jsonld_product = None
    for block in jsonld_blocks:
        if block.get("@type") == "Product":
            jsonld_product = block
            break

    if jsonld_product:
        product_data["title"] = jsonld_product.get("name", "")
        offers = jsonld_product.get("offers", {})
        if isinstance(offers, list):
            offers = offers[0] if offers else {}
        product_data["price"] = str(offers.get("price", ""))
        product_data["currency"] = offers.get("priceCurrency", "USD")
        avail = offers.get("availability", "")
        product_data["availability"] = "In Stock" if "InStock" in avail else "Out of Stock"
        high_price = offers.get("highPrice", "")
        if high_price and product_data["price"]:
            try:
                if float(high_price) > float(product_data["price"]):
                    product_data["original_price"] = high_price
            except ValueError:
                pass

    return {
        "id": index,
        "title": product_data.get("title", ""),
        "price": product_data.get("price", ""),
        "availability": product_data.get("availability", ""),
        "original_price": product_data.get("original_price", ""),
        "currency": product_data.get("currency", ""),
        "url": url,
        "src_url": src_url,
        "location": "",
        "status_code": 200,
        "scraped_at": datetime.now(timezone.utc).isoformat(),
        "remarks": "",
    }


async def discover_product_urls(orchestrator: AkamaiOrchestrator) -> list[str]:
    result = await orchestrator.probe(PRODUCT_LISTING_URL)
    if not result or not result.get("html"):
        logger.error("Failed to load product listing: %s", PRODUCT_LISTING_URL)
        return []

    from playwright.sync_api import sync_playwright

    html = result["html"]
    pw = sync_playwright().start()
    browser = pw.chromium.launch(headless=True, args=["--no-sandbox"])
    page = browser.new_page()
    page.set_content(html)

    selector = "{PRODUCT_LINK_SELECTOR}"
    links = page.evaluate(f"""() => {{
        const links = document.querySelectorAll('{selector}');
        const unique = new Set();
        links.forEach(a => {{
            let href = a.getAttribute('href');
            if (href) {{
                if (!href.startsWith('http')) {{
                    href = window.location.origin + href;
                }}
                unique.add(href);
            }}
        }});
        return Array.from(unique);
    }}""")

    browser.close()
    pw.stop()
    return links or []


def load_urls_from_file(filepath: str) -> list[str]:
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data.get("urls", [])


def save_urls_to_file(filepath: str, urls: list[str]) -> None:
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump({"urls": urls}, f, indent=2, ensure_ascii=False)
    logger.info("Saved %d URLs to %s", len(urls), filepath)


# ═══════════════════════════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════════════════════════

async def main():
    parser = argparse.ArgumentParser(description=f"Akamai stealth scraper for {SITE_NAME}")
    parser.add_argument("--sample", action="store_true", help="Scrape only 5 products")
    parser.add_argument("--limit", type=int, default=None, help="Max products to scrape")
    parser.add_argument("--input", type=str, default=None, help="Path to input URLs JSON file")
    parser.add_argument("--urls", nargs="+", default=None, help="Product URLs as arguments")
    parser.add_argument("--proxy-tier", type=str, default=PROXY_TIER, help="Proxy tier: none/datacenter/residential")
    args = parser.parse_args()

    start_time = time.time()

    logger.info("=" * 80)
    logger.info("Starting Akamai stealth scraper for %s", SITE_NAME)
    logger.info("Site: %s", SITE_URL)
    logger.info("Proxy tier: %s", args.proxy_tier)
    logger.info("Output: %s", OUTPUT_FILE)
    logger.info("=" * 80)

    product_urls = []

    if args.urls:
        product_urls = args.urls
    elif args.input:
        product_urls = load_urls_from_file(args.input)
    elif os.path.exists(INPUT_FILE):
        product_urls = load_urls_from_file(INPUT_FILE)

    if args.sample:
        product_urls = product_urls[:5]
    if args.limit:
        product_urls = product_urls[:args.limit]

    config = build_akamai_config_from_proxy_tier(args.proxy_tier)
    config.headless = True
    orchestrator = AkamaiOrchestrator(config)

    if not product_urls:
        logger.info("No input URLs found. Discovering products via Akamai bypass...")
        product_urls = await discover_product_urls(orchestrator)
        save_urls_to_file(INPUT_FILE, product_urls)

    logger.info("Total products to scrape: %d", len(product_urls))

    results = []
    failed = 0

    for i, url in enumerate(product_urls):
        try:
            product = await scrape_product(orchestrator, url, SRC_URL, i + 1)
            if product and product.get("title"):
                results.append(product)
            else:
                logger.warning("No title extracted from: %s", url[:100])
                failed += 1
        except Exception as e:
            logger.error("Error processing %s: %s", url[:100], e)
            failed += 1

        if (i + 1) % 5 == 0:
            percent = ((i + 1) / len(product_urls)) * 100
            logger.info("Progress: [%d/%d] (%.1f%%)", i + 1, len(product_urls), percent)

        time.sleep(DELAY_BETWEEN_REQUESTS)

    output = {
        "site": {
            "name": SITE_NAME,
            "url": SITE_URL,
            "platform": PLATFORM,
            "scraping_method": SCRAPING_METHOD,
            "scraped_at": datetime.now(timezone.utc).isoformat(),
        },
        "products": results,
        "metadata": {
            "scraping_duration_seconds": round(time.time() - start_time, 2),
            "failed_products": failed,
            "rate_limit_delay": DELAY_BETWEEN_REQUESTS,
        },
    }

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(output, f, indent=2, ensure_ascii=False)

    logger.info("=" * 80)
    logger.info("EXTRACTION COMPLETE")
    logger.info("Total: %d, Failed: %d", len(results), failed)
    logger.info("Duration: %.2fs", time.time() - start_time)
    logger.info("Output: %s", OUTPUT_FILE)
    logger.info("=" * 80)


if __name__ == "__main__":
    asyncio.run(main())
