#!/usr/bin/env python3
"""
API Scraper Template

Uses internal API endpoints for ecommerce sites with JSON APIs.
Generated by Code Writer Agent for Universal Ecommerce Scraper.

The scraper reads input_urls.json from its own directory by default.
Can also accept URLs via --urls or --input flags.

Usage:
    python3 scraper.py                    # reads input_urls.json from same folder
    python3 scraper.py --input urls.json  # explicit input file
    python3 scraper.py --urls url1 url2     # URLs as CLI arguments
"""

import argparse
import json
import logging
import os
import re
import sys
import time
from datetime import datetime, timezone
from typing import Optional

import requests

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from src.proxy import ProxyConfig, should_warn_residential, warn_residential_usage

# ═══════════════════════════════════════════════════════════════════════════════
# CONFIGURATION - Update these values
# ═══════════════════════════════════════════════════════════════════════════════

SITE_NAME = "{SITE_NAME}"
SITE_URL = "{SITE_URL}"
PLATFORM = "{PLATFORM}"
SCRAPING_METHOD = "internal_api"
SITE_SLUG = "{SITE_SLUG}"

API_BASE_URL = "{API_BASE_URL}"
API_PRODUCTS_ENDPOINT = "{API_PRODUCTS_ENDPOINT}"
API_KEY = None
API_HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Accept": "application/json",
    "Content-Type": "application/json",
}
if API_KEY:
    API_HEADERS["Authorization"] = f"Bearer {API_KEY}"

PAGINATION_TYPE = "offset"
PAGE_SIZE = {PAGE_SIZE}  # use the API's MAX page size (e.g. 100-500) for full extraction; no item cap
DELAY_BETWEEN_REQUESTS = {DELAY_BETWEEN_REQUESTS}
MAX_RETRIES = 3

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
# Unique per process: a second-resolution timestamp collides when two runs
# of this draft start in the same second (job-71 popsockets — the discovery
# run's empty products array overwrote the passing extraction result).
TIMESTAMP = datetime.now(timezone.utc).strftime("%Y-%m-%d_%H%M%S_%f")
OUTPUT_FILE = os.path.join(SCRIPT_DIR, f"output_{TIMESTAMP}_{os.getpid()}.json")
INPUT_FILE = os.path.join(SCRIPT_DIR, "input_urls.json")
LOG_FILE = os.path.join(os.path.dirname(SCRIPT_DIR), "logs", f"{SITE_SLUG}.log")

# ═══════════════════════════════════════════════════════════════════════════════
# LOGGING
# ═══════════════════════════════════════════════════════════════════════════════

os.makedirs(os.path.dirname(LOG_FILE), exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[
        logging.FileHandler(LOG_FILE),
        logging.StreamHandler(),
    ],
)
logger = logging.getLogger(__name__)

proxy_config = ProxyConfig.get_instance()


# ═══════════════════════════════════════════════════════════════════════════════
# INPUT HANDLING
# ═══════════════════════════════════════════════════════════════════════════════

def load_urls_from_file(filepath: str) -> list[str]:
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data.get("urls", [])


def save_urls_to_file(filepath: str, urls: list[str]) -> None:
    # [job-77] A 0-URL discovery must not DESTROY an existing seed file: the
    # adoreme execution discovered 0 under a PDP listing and left a 16-byte
    # {"urls": []} as the site's canonical input_urls.json. Skip the empty
    # overwrite when a seed already exists; a non-empty refresh still writes.
    if not urls and os.path.exists(filepath):
        logger.warning(f"Refusing to overwrite {filepath} with an empty URL list")
        return
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump({"urls": urls}, f, indent=2, ensure_ascii=False)
    logger.info(f"Saved {len(urls)} URLs to {filepath}")


# ═══════════════════════════════════════════════════════════════════════════════
# API FUNCTIONS - CUSTOMIZE response parsing below
# ═══════════════════════════════════════════════════════════════════════════════

def fetch_api(endpoint: str, params: Optional[dict] = None) -> Optional[dict]:
    url = f"{API_BASE_URL}{endpoint}"
    ssl_verify = proxy_config.config.get("strategy", {}).get("ssl_verify", False)
    escalation = proxy_config.get_escalation_tier()

    for tier in ["none", *escalation]:
        if should_warn_residential(tier):
            warn_residential_usage(url)

        proxies = proxy_config.get_proxy_dict(tier) if tier != "none" else None
        max_retries = proxy_config.get_max_retries(tier) if tier != "none" else MAX_RETRIES
        cooldown = proxy_config.get_cooldown(tier) if tier != "none" else DELAY_BETWEEN_REQUESTS * 2

        for attempt in range(max_retries):
            try:
                time.sleep(DELAY_BETWEEN_REQUESTS)
                response = requests.get(url, params=params, headers=API_HEADERS, proxies=proxies, timeout=proxy_config.get_timeout(), verify=ssl_verify)
                if response.status_code == 200:
                    return response.json()
                if proxy_config.is_banned(response.status_code, response.text):
                    logger.warning(f"Ban detected ({response.status_code}) on tier '{tier}', escalating...")
                    break
                response.raise_for_status()
            except requests.RequestException as e:
                logger.error(f"API request failed (attempt {attempt + 1}/{max_retries}, tier={tier}): {e}")
                if attempt < max_retries - 1:
                    time.sleep(cooldown)
    return None


# ── FIELD NORMALIZERS — inline on purpose, NOT a src import ──────────────────
# Drafts execute in the browser-service image: a NEW src import would ImportError
# there until that image is rebuilt, so the ~25 lines live in each python-side
# template verbatim (playwright/UC normalize in-page via JS and don't need them).

def _norm_price(value) -> Optional[str]:
    """Strip currency symbols/whitespace from a price.

    "£1,234.56" → "1234.56", "1.234,56 €" → "1234.56", 24.99 (a JSON-LD
    number) → "24.99". Returns None when no digits are present — an
    unparseable price is EMPTY, never zero (0 would read as a real product
    priced at nothing). The currency stays in its own ``currency`` field.
    """
    if value is None:
        return None
    cleaned = re.sub(r"[^\d.,-]", "", str(value).strip())
    if not re.search(r"\d", cleaned):
        return None
    if "," in cleaned and "." in cleaned:
        # Both separators present: whichever comes LAST is the decimal one.
        if cleaned.rfind(",") > cleaned.rfind("."):
            cleaned = cleaned.replace(".", "").replace(",", ".")
        else:
            cleaned = cleaned.replace(",", "")
    elif "," in cleaned:
        # "1,234" (grouping) vs "1,5" (decimal comma): a comma followed by
        # exactly three digits is grouping, anything else is a decimal comma.
        cleaned = re.sub(r",(?=\d{3}(?:\D|$))", "", cleaned).replace(",", ".")
    return cleaned


def _norm_availability(value) -> Optional[str]:
    """Normalize availability to ``in_stock`` / ``out_of_stock``.

    Accepts the schema.org URI form, InStock / In Stock / in_stock / Available
    and their negatives. Anything unrecognised passes through lowercased —
    availability is never invented (an unknown state is data, not an error).
    """
    if value is None:
        return None
    if isinstance(value, bool):
        return "in_stock" if value else "out_of_stock"
    text = str(value).strip().lower()
    if not text:
        return None
    if "://" in text:  # e.g. http://schema.org/InStock
        text = text.rsplit("/", 1)[-1]
    compact = text.replace("-", "_").replace(" ", "")
    if compact in ("in_stock", "instock", "available"):
        return "in_stock"
    if compact in ("out_of_stock", "outofstock", "unavailable", "sold_out", "soldout"):
        return "out_of_stock"
    return text


def transform_api_product(api_product: dict, index: int, src_url: str) -> dict:
    """CUSTOMIZE: Update field mapping to match the target API response structure."""
    price = api_product.get("price", "") or ""
    return {
        "id": index,
        "title": api_product.get("title", "") or api_product.get("name", ""),
        # Symbol-free price: baking "$" into the field makes every downstream
        # numeric comparison (and currency inference) wrong.
        "price": _norm_price(price),
        "availability": _norm_availability(api_product.get("available", True)),
        "original_price": api_product.get("original_price", "") or api_product.get("compare_at_price", "") or api_product.get("highPrice", ""),
        "currency": api_product.get("currency", "USD"),
        "url": api_product.get("url", "") or "",
        "src_url": src_url,
        "location": "",
        "status_code": 200,
        "scraped_at": datetime.now(timezone.utc).isoformat(),
        "remarks": "",
    }


def transform_api_jobs(raw_jobs: list[dict], src_url: str = "") -> list[dict]:
    """JOB boards: map raw API items to standard job fields using the GENERIC
    resolver in ``src.job_fields``.  Do NOT hardcode site-specific field names —
    ``map_jobs`` infers each field's source path (title, company, location,
    description, salary, job_type, posted_date, apply_url, requirements) by
    coverage over the batch, so the SAME code works across job platforms.
    Use this in place of ``transform_api_product`` when scraping job postings.
    """
    from src.job_fields import map_jobs

    if not raw_jobs:
        return []
    jobs = map_jobs(sample_items=raw_jobs, raw_items=raw_jobs)
    now = datetime.now(timezone.utc).isoformat()
    for idx, j in enumerate(jobs, start=1):
        j.setdefault("id", idx)
        if src_url:
            j.setdefault("src_url", src_url)
        j.setdefault("status_code", 200)
        j.setdefault("scraped_at", now)
        j.setdefault("remarks", "")
    return jobs



def fetch_all_products_via_api() -> tuple[list[str], list[dict]]:
    all_products = []
    offset = 0
    cursor = None
    page = 1

    while True:
        if PAGINATION_TYPE == "offset":
            params = {"limit": PAGE_SIZE, "offset": offset}
        elif PAGINATION_TYPE == "page":
            params = {"limit": PAGE_SIZE, "page": page}
        elif PAGINATION_TYPE == "cursor":
            params = {"limit": PAGE_SIZE, "cursor": cursor} if cursor else {"limit": PAGE_SIZE}
        else:
            params = {"limit": PAGE_SIZE}

        logger.info(f"Fetching API page {page}: {API_PRODUCTS_ENDPOINT}")
        data = fetch_api(API_PRODUCTS_ENDPOINT, params=params)

        if not data:
            break

        products = data.get("products", []) or data.get("items", []) or data.get("data", [])
        if isinstance(data, list):
            products = data

        for raw in products:
            all_products.append(raw)

        logger.info(f"Page {page}: {len(products)} products (total: {len(all_products)})")

        # Stop when a page is short (exhausted) OR we've hit the API's reported total.
        if len(products) < PAGE_SIZE:
            break
        total = (
            data.get("totalCount") or data.get("total_count") or data.get("count")
            or data.get("total") or data.get("totalResults") or data.get("totalJobs")
        )
        if isinstance(total, int) and total > 0 and len(all_products) >= total:
            break

        if PAGINATION_TYPE == "cursor":
            cursor = data.get("next_cursor") or data.get("cursor")
            if not cursor:
                break
        elif PAGINATION_TYPE == "offset":
            offset += PAGE_SIZE
        # page-based: single increment below (do NOT increment twice)
        page += 1

    urls = [p.get("url", "") or p.get("handle", "") for p in all_products]
    urls = [u for u in urls if u]
    return urls, all_products


def scrape_product(url: str, src_url: str) -> Optional[dict]:
    try:
        time.sleep(DELAY_BETWEEN_REQUESTS)
        response = requests.get(url, headers=HEADERS, timeout=15)
        response.raise_for_status()
        data = response.json()
        return transform_api_product(data, 0, src_url)
    except Exception as e:
        logger.error(f"Failed to scrape {url}: {e}")
        return None


# ═══════════════════════════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════════════════════════

# ── CLI CONTRACT — keep every line below when adapting ───────────────────────
# The pipeline launches this scraper with EXACTLY these names. A flag missing
# from the argparse below is STRIPPED at launch and discovery silently falls
# back to the seed file (input_urls.json). ADD flags if you need them; NEVER
# remove or rename:
#   --fresh-discovery  the ONLY discovery trigger for the api family (execution
#                      always passes it) — there is NO listing page; discovery
#                      IS the API. SCRAPER_FORCE_DISCOVERY is the env gate.
#   --input/--sample/--limit  testing
# Source of truth: webapp/agents/constants.py
# ──────────────────────────────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser(description=f"API scraper for {SITE_NAME}")
    parser.add_argument("--sample", action="store_true", help="Scrape only 5 products")
    parser.add_argument("--limit", type=int, default=None, help="Max products to scrape")
    parser.add_argument("--input", type=str, default=None, help="Path to input URLs JSON file")
    parser.add_argument("--urls", nargs="+", default=None, help="Product URLs as arguments")
    parser.add_argument("--fresh-discovery", action="store_true",
                        help="Bypass input_urls.json and rediscover via API pagination")
    args = parser.parse_args()

    if args.input:
        # [job-60 zquiet] The runner's CWD is not the scraper's directory
        # (the tester passes `--input input_urls.json` while CWD=/app), so a
        # relative seed-file value must resolve against the scraper's own
        # directory. os.path.join passes absolute paths through untouched.
        args.input = os.path.join(SCRIPT_DIR, args.input)

    start_time = time.time()

    logger.info("=" * 80)
    logger.info(f"Starting API scraper for {SITE_NAME}")
    logger.info(f"Site: {SITE_URL}")
    logger.info(f"API: {API_BASE_URL}{API_PRODUCTS_ENDPOINT}")
    logger.info(f"Output: {OUTPUT_FILE}")
    logger.info("=" * 80)

    product_urls = []
    raw_products = []
    src_url = f"{API_BASE_URL}{API_PRODUCTS_ENDPOINT}"

    # F6: run_execution always passes --fresh-discovery for nav jobs; declaring
    # it here means the CLI-contract guard passes it through (declared flags
    # are never stripped) and the seed-file branch can't suppress API
    # pagination. SCRAPER_LISTING_URL is semantically wrong for this template
    # (no listing page — discovery IS the API), so the flag is the mechanism.
    _force_fresh = args.fresh_discovery or bool(
        os.environ.get("SCRAPER_FORCE_DISCOVERY", "").strip()
    )
    if args.urls and not _force_fresh:
        product_urls = args.urls
    elif args.input and not _force_fresh:
        product_urls = load_urls_from_file(args.input)
    elif os.path.exists(INPUT_FILE) and not _force_fresh:
        product_urls = load_urls_from_file(INPUT_FILE)
    else:
        logger.info("Fresh discovery (%s): paginating API for product URLs",
                    "flag" if args.fresh_discovery else "env")
        product_urls, raw_products = fetch_all_products_via_api()
        save_urls_to_file(INPUT_FILE, product_urls)

    if args.sample:
        product_urls = product_urls[:5]
    if args.limit:
        product_urls = product_urls[: args.limit]

    logger.info(f"Total products to scrape: {len(product_urls)}")

    results = []
    failed = 0

    if raw_products and len(raw_products) == len(product_urls):
        for i, raw in enumerate(raw_products[: len(product_urls)]):
            try:
                product = transform_api_product(raw, i + 1, src_url)
                results.append(product)
            except Exception as e:
                logger.error(f"Error transforming product {i + 1}: {e}")
                failed += 1
    else:
        for i, url in enumerate(product_urls):
            try:
                product = scrape_product(url, src_url)
                if product:
                    product["id"] = i + 1
                    results.append(product)
                else:
                    failed += 1
            except Exception as e:
                logger.error(f"Error processing {url}: {e}")
                failed += 1

            if (i + 1) % 25 == 0:
                percent = ((i + 1) / len(product_urls)) * 100
                logger.info(f"Progress: [{i + 1}/{len(product_urls)}] ({percent:.1f}%)")

    output = {
        "site": {
            "name": SITE_NAME,
            "url": SITE_URL,
            "platform": PLATFORM,
            "scraping_method": SCRAPING_METHOD,
            "scraped_at": datetime.now(timezone.utc).isoformat(),
        },
        "products": results,
        "metadata": {
            "scraping_duration_seconds": round(time.time() - start_time, 2),
            "failed_products": failed,
            "rate_limit_delay": DELAY_BETWEEN_REQUESTS,
        },
    }

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(output, f, indent=2, ensure_ascii=False)

    logger.info("=" * 80)
    logger.info("EXTRACTION COMPLETE")
    logger.info(f"Total: {len(results)}, Failed: {failed}")
    logger.info(f"Duration: {round(time.time() - start_time, 2)}s")
    logger.info(f"Output: {OUTPUT_FILE}")
    logger.info("=" * 80)


if __name__ == "__main__":
    main()
