#!/usr/bin/env python3
"""
Article Scraper Template

Uses requests + BeautifulSoup for static article/news/blog sites.
Generated by Code Writer Agent for Universal Ecommerce Scraper.

The scraper reads input_urls.json from its own directory by default.
Can also accept URLs via --urls or --input flags.

Usage:
    python3 scraper.py                    # reads input_urls.json from same folder
    python3 scraper.py --input urls.json  # explicit input file
    python3 scraper.py --urls url1 url2     # URLs as CLI arguments
"""

import argparse
import json
import logging
import os
import re
import sys
import time
from datetime import datetime, timezone
from html import unescape
from typing import Optional
from urllib.parse import urljoin

import requests
from bs4 import BeautifulSoup

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from src.proxy import ProxyConfig, should_warn_residential, warn_residential_usage

# ═══════════════════════════════════════════════════════════════════════════════
# CONFIGURATION - Update these values
# ═══════════════════════════════════════════════════════════════════════════════

SITE_NAME = "{SITE_NAME}"
SITE_URL = "{SITE_URL}"
PLATFORM = "{PLATFORM}"
SCRAPING_METHOD = "http_requests"
SITE_SLUG = "{SITE_SLUG}"

ARTICLE_LISTING_URL = "{LISTING_URL}"
SRC_URL = "{LISTING_URL}"
DELAY_BETWEEN_REQUESTS = {DELAY_BETWEEN_REQUESTS}
MAX_RETRIES = 3

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
}

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
TIMESTAMP = datetime.now(timezone.utc).strftime("%Y-%m-%d_%H%M%S")
OUTPUT_FILE = os.path.join(SCRIPT_DIR, f"output_{TIMESTAMP}.json")
INPUT_FILE = os.path.join(SCRIPT_DIR, "input_urls.json")
LOG_FILE = os.path.join(os.path.dirname(SCRIPT_DIR), "logs", f"{SITE_SLUG}.log")

# ═══════════════════════════════════════════════════════════════════════════════
# LOGGING
# ═══════════════════════════════════════════════════════════════════════════════

os.makedirs(os.path.dirname(LOG_FILE), exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[
        logging.FileHandler(LOG_FILE),
        logging.StreamHandler(),
    ],
)
logger = logging.getLogger(__name__)

proxy_config = ProxyConfig.get_instance()


# ═══════════════════════════════════════════════════════════════════════════════
# HELPERS
# ═══════════════════════════════════════════════════════════════════════════════

def clean_html(html_str: str) -> str:
    if not html_str:
        return ""
    text = re.sub(r"<[^>]+>", " ", html_str)
    text = unescape(text)
    return re.sub(r"\s+", " ", text).strip()


def make_absolute_url(url: str, base: str = SITE_URL) -> str:
    if not url:
        return ""
    if url.startswith("http"):
        return url
    if url.startswith("//"):
        return f"https:{url}"
    return urljoin(base, url)


def fetch_page(url: str) -> Optional[tuple[BeautifulSoup, int]]:
    ssl_verify = proxy_config.config.get("strategy", {}).get("ssl_verify", False)
    escalation = proxy_config.get_escalation_tier()

    for tier in ["none", *escalation]:
        if should_warn_residential(tier):
            warn_residential_usage(url)

        proxies = proxy_config.get_proxy_dict(tier) if tier != "none" else None
        max_retries = proxy_config.get_max_retries(tier) if tier != "none" else MAX_RETRIES
        cooldown = proxy_config.get_cooldown(tier) if tier != "none" else DELAY_BETWEEN_REQUESTS * 2

        for attempt in range(max_retries):
            try:
                time.sleep(DELAY_BETWEEN_REQUESTS)
                response = requests.get(url, headers=HEADERS, proxies=proxies, timeout=proxy_config.get_timeout(), verify=ssl_verify)
                if response.status_code == 200:
                    response.raise_for_status()
                    return BeautifulSoup(response.text, "html.parser"), response.status_code
                if proxy_config.is_banned(response.status_code, response.text):
                    logger.warning(f"Ban detected ({response.status_code}) on tier '{tier}', escalating...")
                    break
                response.raise_for_status()
                return BeautifulSoup(response.text, "html.parser"), response.status_code
            except requests.RequestException as e:
                logger.error(f"Failed to fetch {url} (attempt {attempt + 1}/{max_retries}, tier={tier}): {e}")
                if attempt < max_retries - 1:
                    time.sleep(cooldown)

    return None


# ═══════════════════════════════════════════════════════════════════════════════
# EXTRACTION - CUSTOMIZE selectors below
# ═══════════════════════════════════════════════════════════════════════════════

def extract_jsonld(soup: BeautifulSoup) -> Optional[dict]:
    article_types = ("Article", "NewsArticle", "BlogPosting", "TechArticle")
    for script in soup.find_all("script", type="application/ld+json"):
        try:
            data = json.loads(script.string)
            if isinstance(data, dict) and data.get("@type") in article_types:
                return data
            if isinstance(data, list):
                for item in data:
                    if isinstance(item, dict) and item.get("@type") in article_types:
                        return item
        except (json.JSONDecodeError, TypeError):
            continue
    return None


def extract_article_from_page(soup: BeautifulSoup, url: str, status_code: int, src_url: str) -> dict:
    article = {
        "id": 0,
        "title": "",
        "author": "",
        "publish_date": "",
        "content": "",
        "images": [],
        "tags": [],
        "category": "",
        "url": url,
        "src_url": src_url,
        "location": "",
        "status_code": status_code,
        "scraped_at": datetime.now(timezone.utc).isoformat(),
        "remarks": "",
    }

    jsonld = extract_jsonld(soup)

    # Title
    if jsonld:
        article["title"] = jsonld.get("headline", jsonld.get("name", ""))
    else:
        el = soup.select_one("{TITLE_SELECTOR}")
        article["title"] = el.get_text(strip=True) if el else (soup.title.string if soup.title else "")

    # Author
    if jsonld:
        author = jsonld.get("author", {})
        if isinstance(author, dict):
            article["author"] = author.get("name", "")
        elif isinstance(author, str):
            article["author"] = author
    else:
        author_el = soup.select_one("{AUTHOR_SELECTOR}")
        article["author"] = author_el.get_text(strip=True) if author_el else ""

    # Publish date
    if jsonld:
        article["publish_date"] = jsonld.get("datePublished", "")
    else:
        date_el = soup.select_one("{DATE_SELECTOR}")
        if date_el:
            date_attr = date_el.get("datetime", "") or date_el.get("content", "")
            article["publish_date"] = date_attr if date_attr else date_el.get_text(strip=True)

    # Content (main article body)
    if jsonld:
        article["content"] = jsonld.get("articleBody", "")
    else:
        content_el = soup.select_one("{CONTENT_SELECTOR}")
        if content_el:
            article["content"] = content_el.get_text(separator="\n", strip=True)

    # Images
    if jsonld:
        images = jsonld.get("image", [])
        if isinstance(images, str):
            images = [images]
        article["images"] = [img if isinstance(img, str) else img.get("url", "") for img in images if img]
    else:
        img_els = soup.select("{IMAGE_SELECTOR}")
        article["images"] = [make_absolute_url(img.get("src", img.get("data-src", ""))) for img in img_els if img.get("src") or img.get("data-src")]

    # Tags
    if jsonld:
        keywords = jsonld.get("keywords", "")
        if isinstance(keywords, str):
            article["tags"] = [k.strip() for k in keywords.split(",") if k.strip()]
        elif isinstance(keywords, list):
            article["tags"] = keywords
    else:
        tag_els = soup.select("{TAG_SELECTOR}")
        article["tags"] = [t.get_text(strip=True) for t in tag_els if t.get_text(strip=True)]

    # Category
    if jsonld:
        article["category"] = jsonld.get("articleSection", "")
    else:
        cat_el = soup.select_one("{CATEGORY_SELECTOR}")
        article["category"] = cat_el.get_text(strip=True) if cat_el else ""

    return article


# ═══════════════════════════════════════════════════════════════════════════════
# DISCOVERY
# ═══════════════════════════════════════════════════════════════════════════════

def discover_article_urls() -> list[str]:
    all_urls = []
    seen = set()
    page = 1

    while True:
        paginated_url = f"{ARTICLE_LISTING_URL}?page={page}"
        logger.info(f"Fetching listing page {page}: {paginated_url}")

        result = fetch_page(paginated_url)
        if not result:
            break

        soup, _ = result
        links = soup.select("{ARTICLE_LINK_SELECTOR}")
        for link in links:
            href = link.get("href", "")
            absolute_url = make_absolute_url(href)
            if absolute_url and absolute_url not in seen:
                seen.add(absolute_url)
                all_urls.append(absolute_url)

        logger.info(f"Page {page}: {len(links)} articles found (total: {len(all_urls)})")

        if len(links) == 0:
            break

        page += 1

    return all_urls


# ═══════════════════════════════════════════════════════════════════════════════
# INPUT HANDLING
# ═══════════════════════════════════════════════════════════════════════════════

def load_urls_from_file(filepath: str) -> list[str]:
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data.get("urls", [])


def save_urls_to_file(filepath: str, urls: list[str]) -> None:
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump({"urls": urls}, f, indent=2, ensure_ascii=False)
    logger.info(f"Saved {len(urls)} URLs to {filepath}")


# ═══════════════════════════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(description=f"Article scraper for {SITE_NAME}")
    parser.add_argument("--sample", action="store_true", help="Scrape only 5 articles")
    parser.add_argument("--limit", type=int, default=None, help="Max articles to scrape")
    parser.add_argument("--input", type=str, default=None, help="Path to input URLs JSON file")
    parser.add_argument("--urls", nargs="+", default=None, help="Article URLs as arguments")
    args = parser.parse_args()

    start_time = time.time()

    logger.info("=" * 80)
    logger.info(f"Starting article scraper for {SITE_NAME}")
    logger.info(f"Site: {SITE_URL}")
    logger.info(f"Listing URL: {ARTICLE_LISTING_URL}")
    logger.info(f"Output: {OUTPUT_FILE}")
    logger.info("=" * 80)

    article_urls = []

    if args.urls:
        article_urls = args.urls
    elif args.input:
        article_urls = load_urls_from_file(args.input)
    elif os.path.exists(INPUT_FILE):
        article_urls = load_urls_from_file(INPUT_FILE)
    else:
        logger.info("No input_urls.json found. Discovering articles from listing page...")
        article_urls = discover_article_urls()
        save_urls_to_file(INPUT_FILE, article_urls)

    if args.sample:
        article_urls = article_urls[:5]
    if args.limit:
        article_urls = article_urls[: args.limit]

    logger.info(f"Total articles to scrape: {len(article_urls)}")

    results = []
    failed = 0

    for i, url in enumerate(article_urls):
        result = fetch_page(url)
        if result:
            soup, status_code = result
            article = extract_article_from_page(soup, url, status_code, SRC_URL)
            article["id"] = i + 1
            results.append(article)
        else:
            logger.error(f"Failed to fetch: {url}")
            failed += 1

        if (i + 1) % 25 == 0:
            percent = ((i + 1) / len(article_urls)) * 100
            logger.info(f"Progress: [{i + 1}/{len(article_urls)}] ({percent:.1f}%)")

    output = {
        "site": {
            "name": SITE_NAME,
            "url": SITE_URL,
            "platform": PLATFORM,
            "scraping_method": SCRAPING_METHOD,
            "scraped_at": datetime.now(timezone.utc).isoformat(),
        },
        "articles": results,
        "metadata": {
            "scraping_duration_seconds": round(time.time() - start_time, 2),
            "failed_items": failed,
            "rate_limit_delay": DELAY_BETWEEN_REQUESTS,
        },
    }

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(output, f, indent=2, ensure_ascii=False)

    logger.info("=" * 80)
    logger.info("EXTRACTION COMPLETE")
    logger.info(f"Total: {len(results)}, Failed: {failed}")
    logger.info(f"Duration: {round(time.time() - start_time, 2)}s")
    logger.info(f"Output: {OUTPUT_FILE}")
    logger.info("=" * 80)


if __name__ == "__main__":
    main()
