#!/usr/bin/env python3
"""
Generic Content Scraper Template

Uses requests + BeautifulSoup for any web page content extraction.
Generated by Code Writer Agent for Universal Ecommerce Scraper.

The scraper reads input_urls.json from its own directory by default.
Can also accept URLs via --urls or --input flags.

Usage:
    python3 scraper.py                    # reads input_urls.json from same folder
    python3 scraper.py --input urls.json  # explicit input file
    python3 scraper.py --urls url1 url2     # URLs as CLI arguments
"""

import argparse
import json
import logging
import os
import re
import sys
import time
from datetime import datetime, timezone
from html import unescape
from typing import Optional
from urllib.parse import urljoin

import requests
from bs4 import BeautifulSoup

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from src.proxy import ProxyConfig, should_warn_residential, warn_residential_usage

# ═══════════════════════════════════════════════════════════════════════════════
# CONFIGURATION - Update these values
# ═══════════════════════════════════════════════════════════════════════════════

SITE_NAME = "{SITE_NAME}"
SITE_URL = "{SITE_URL}"
PLATFORM = "{PLATFORM}"
SCRAPING_METHOD = "http_requests"
SITE_SLUG = "{SITE_SLUG}"

SRC_URL = "{SRC_URL}"
DELAY_BETWEEN_REQUESTS = {DELAY_BETWEEN_REQUESTS}
MAX_RETRIES = 3

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
}

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
TIMESTAMP = datetime.now(timezone.utc).strftime("%Y-%m-%d_%H%M%S")
OUTPUT_FILE = os.path.join(SCRIPT_DIR, f"output_{TIMESTAMP}.json")
INPUT_FILE = os.path.join(SCRIPT_DIR, "input_urls.json")
LOG_FILE = os.path.join(os.path.dirname(SCRIPT_DIR), "logs", f"{SITE_SLUG}.log")

# ═══════════════════════════════════════════════════════════════════════════════
# LOGGING
# ═══════════════════════════════════════════════════════════════════════════════

os.makedirs(os.path.dirname(LOG_FILE), exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[
        logging.FileHandler(LOG_FILE),
        logging.StreamHandler(),
    ],
)
logger = logging.getLogger(__name__)

proxy_config = ProxyConfig.get_instance()


# ═══════════════════════════════════════════════════════════════════════════════
# HELPERS
# ═══════════════════════════════════════════════════════════════════════════════

def clean_html(html_str: str) -> str:
    if not html_str:
        return ""
    text = re.sub(r"<[^>]+>", " ", html_str)
    text = unescape(text)
    return re.sub(r"\s+", " ", text).strip()


def make_absolute_url(url: str, base: str = SITE_URL) -> str:
    if not url:
        return ""
    if url.startswith("http"):
        return url
    if url.startswith("//"):
        return f"https:{url}"
    return urljoin(base, url)


def fetch_page(url: str) -> Optional[tuple[BeautifulSoup, int]]:
    ssl_verify = proxy_config.config.get("strategy", {}).get("ssl_verify", False)
    escalation = proxy_config.get_escalation_tier()

    for tier in ["none", *escalation]:
        if should_warn_residential(tier):
            warn_residential_usage(url)

        proxies = proxy_config.get_proxy_dict(tier) if tier != "none" else None
        max_retries = proxy_config.get_max_retries(tier) if tier != "none" else MAX_RETRIES
        cooldown = proxy_config.get_cooldown(tier) if tier != "none" else DELAY_BETWEEN_REQUESTS * 2

        for attempt in range(max_retries):
            try:
                time.sleep(DELAY_BETWEEN_REQUESTS)
                response = requests.get(url, headers=HEADERS, proxies=proxies, timeout=proxy_config.get_timeout(), verify=ssl_verify)
                if response.status_code == 200:
                    response.raise_for_status()
                    return BeautifulSoup(response.text, "html.parser"), response.status_code
                if proxy_config.is_banned(response.status_code, response.text):
                    logger.warning(f"Ban detected ({response.status_code}) on tier '{tier}', escalating...")
                    break
                response.raise_for_status()
                return BeautifulSoup(response.text, "html.parser"), response.status_code
            except requests.RequestException as e:
                logger.error(f"Failed to fetch {url} (attempt {attempt + 1}/{max_retries}, tier={tier}): {e}")
                if attempt < max_retries - 1:
                    time.sleep(cooldown)

    return None


# ═══════════════════════════════════════════════════════════════════════════════
# EXTRACTION - CUSTOMIZE selectors below
# ═══════════════════════════════════════════════════════════════════════════════

def extract_jsonld(soup: BeautifulSoup) -> Optional[dict]:
    for script in soup.find_all("script", type="application/ld+json"):
        try:
            data = json.loads(script.string)
            if isinstance(data, dict):
                return data
            if isinstance(data, list):
                for item in data:
                    if isinstance(item, dict):
                        return item
        except (json.JSONDecodeError, TypeError):
            continue
    return None


def extract_metadata(soup: BeautifulSoup) -> dict:
    metadata = {}
    for meta in soup.find_all("meta"):
        name = meta.get("name", "") or meta.get("property", "")
        content = meta.get("content", "")
        if name and content:
            metadata[name] = content
    return metadata


def extract_page_content(soup: BeautifulSoup, url: str, status_code: int, src_url: str) -> dict:
    page = {
        "id": 0,
        "title": "",
        "content": "",
        "images": [],
        "metadata": {},
        "url": url,
        "src_url": src_url,
        "location": "",
        "status_code": status_code,
        "scraped_at": datetime.now(timezone.utc).isoformat(),
        "remarks": "",
    }

    jsonld = extract_jsonld(soup)

    # Title
    if jsonld:
        page["title"] = jsonld.get("headline", jsonld.get("name", ""))
    else:
        el = soup.select_one("{TITLE_SELECTOR}")
        page["title"] = el.get_text(strip=True) if el else (soup.title.string if soup.title else "")

    # Content (main content area)
    if jsonld:
        page["content"] = jsonld.get("articleBody", jsonld.get("description", ""))
    else:
        content_el = soup.select_one("{CONTENT_SELECTOR}")
        if content_el:
            page["content"] = content_el.get_text(separator="\n", strip=True)
        else:
            body = soup.find("body")
            if body:
                for tag in body.find_all(["script", "style", "nav", "header", "footer", "noscript"]):
                    tag.decompose()
                page["content"] = body.get_text(separator="\n", strip=True)

    # Images
    img_els = soup.select("{IMAGE_SELECTOR}")
    if img_els:
        page["images"] = [
            make_absolute_url(img.get("src", img.get("data-src", "")))
            for img in img_els
            if img.get("src") or img.get("data-src")
        ]
    elif jsonld:
        images = jsonld.get("image", [])
        if isinstance(images, str):
            images = [images]
        page["images"] = [img if isinstance(img, str) else img.get("url", "") for img in images if img]

    # Metadata
    page["metadata"] = extract_metadata(soup)

    return page


# ═══════════════════════════════════════════════════════════════════════════════
# INPUT HANDLING
# ═══════════════════════════════════════════════════════════════════════════════

def load_urls_from_file(filepath: str) -> list[str]:
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data.get("urls", [])


# ═══════════════════════════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(description=f"Generic content scraper for {SITE_NAME}")
    parser.add_argument("--sample", action="store_true", help="Scrape only 5 pages")
    parser.add_argument("--limit", type=int, default=None, help="Max pages to scrape")
    parser.add_argument("--input", type=str, default=None, help="Path to input URLs JSON file")
    parser.add_argument("--urls", nargs="+", default=None, help="Page URLs as arguments")
    args = parser.parse_args()

    start_time = time.time()

    logger.info("=" * 80)
    logger.info(f"Starting generic content scraper for {SITE_NAME}")
    logger.info(f"Site: {SITE_URL}")
    logger.info(f"Output: {OUTPUT_FILE}")
    logger.info("=" * 80)

    page_urls = []

    if args.urls:
        page_urls = args.urls
    elif args.input:
        page_urls = load_urls_from_file(args.input)
    elif os.path.exists(INPUT_FILE):
        page_urls = load_urls_from_file(INPUT_FILE)
    else:
        logger.error("No input_urls.json found and no URLs provided.")
        sys.exit(1)

    if args.sample:
        page_urls = page_urls[:5]
    if args.limit:
        page_urls = page_urls[: args.limit]

    logger.info(f"Total pages to scrape: {len(page_urls)}")

    results = []
    failed = 0

    for i, url in enumerate(page_urls):
        result = fetch_page(url)
        if result:
            soup, status_code = result
            page = extract_page_content(soup, url, status_code, SRC_URL)
            page["id"] = i + 1
            results.append(page)
        else:
            logger.error(f"Failed to fetch: {url}")
            failed += 1

        if (i + 1) % 25 == 0:
            percent = ((i + 1) / len(page_urls)) * 100
            logger.info(f"Progress: [{i + 1}/{len(page_urls)}] ({percent:.1f}%)")

    output = {
        "site": {
            "name": SITE_NAME,
            "url": SITE_URL,
            "platform": PLATFORM,
            "scraping_method": SCRAPING_METHOD,
            "scraped_at": datetime.now(timezone.utc).isoformat(),
        },
        "pages": results,
        "metadata": {
            "scraping_duration_seconds": round(time.time() - start_time, 2),
            "failed_items": failed,
            "rate_limit_delay": DELAY_BETWEEN_REQUESTS,
        },
    }

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(output, f, indent=2, ensure_ascii=False)

    logger.info("=" * 80)
    logger.info("EXTRACTION COMPLETE")
    logger.info(f"Total: {len(results)}, Failed: {failed}")
    logger.info(f"Duration: {round(time.time() - start_time, 2)}s")
    logger.info(f"Output: {OUTPUT_FILE}")
    logger.info("=" * 80)


if __name__ == "__main__":
    main()
