#!/usr/bin/env python3
"""
Job Posting Scraper Template

Uses requests + BeautifulSoup for job board/career sites.
Generated by Code Writer Agent for Universal Ecommerce Scraper.

The scraper reads input_urls.json from its own directory by default.
Can also accept URLs via --urls or --input flags.

Usage:
    python3 scraper.py                    # reads input_urls.json from same folder
    python3 scraper.py --input urls.json  # explicit input file
    python3 scraper.py --urls url1 url2     # URLs as CLI arguments
"""

import argparse
import json
import logging
import os
import re
import sys
import time
from datetime import datetime, timedelta, timezone
from html import unescape
from typing import Optional
from urllib.parse import parse_qsl, urlencode, urljoin, urlparse

import requests
from bs4 import BeautifulSoup

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from src.proxy import ProxyConfig, should_warn_residential, warn_residential_usage

# ═══════════════════════════════════════════════════════════════════════════════
# CONFIGURATION - Update these values
# ═══════════════════════════════════════════════════════════════════════════════

SITE_NAME = "{SITE_NAME}"
SITE_URL = "{SITE_URL}"
PLATFORM = "{PLATFORM}"
SCRAPING_METHOD = "http_requests"
SITE_SLUG = "{SITE_SLUG}"

JOB_LISTING_URL = "{LISTING_URL}"
SRC_URL = "{LISTING_URL}"
DELAY_BETWEEN_REQUESTS = {DELAY_BETWEEN_REQUESTS}
MAX_RETRIES = 3

# ═══════════════════════════════════════════════════════════════════════════════
# FILTER CONFIGURATION - populated from navigation_analysis.filters
# These control date-range and location filtering for job portals.
# Leave param/selector blank when the site does not expose that filter; the
# scraper then falls back to client-side filtering of extracted data.
# ═══════════════════════════════════════════════════════════════════════════════

# Filter mechanism: "url" (params in URL), "form" (form elements), "mixed", or "none"
FILTER_METHOD = "{FILTER_METHOD}"

# Date filter — default to last 7 days
DATE_FILTER_DAYS = 7
DATE_FILTER_PARAM = "{DATE_FILTER_PARAM}"        # URL param, e.g. "date_posted", "fromage"
DATE_FILTER_SELECTOR = "{DATE_FILTER_SELECTOR}"  # CSS selector for a form <select>/<input>

# Location filter — default to Alabama
LOCATION_FILTER_VALUE = "{LOCATION_FILTER_VALUE}"  # e.g. "Alabama", "AL"
LOCATION_FILTER_PARAM = "{LOCATION_FILTER_PARAM}"
LOCATION_FILTER_SELECTOR = "{LOCATION_FILTER_SELECTOR}"

# Category filter — empty means ALL categories/specialties
CATEGORY_FILTER_VALUE = ""
CATEGORY_FILTER_PARAM = "{CATEGORY_FILTER_PARAM}"
CATEGORY_FILTER_SELECTOR = "{CATEGORY_FILTER_SELECTOR}"

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
}

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
TIMESTAMP = datetime.now(timezone.utc).strftime("%Y-%m-%d_%H%M%S")
OUTPUT_FILE = os.path.join(SCRIPT_DIR, f"output_{TIMESTAMP}.json")
INPUT_FILE = os.path.join(SCRIPT_DIR, "input_urls.json")
LOG_FILE = os.path.join(os.path.dirname(SCRIPT_DIR), "logs", f"{SITE_SLUG}.log")

# ═══════════════════════════════════════════════════════════════════════════════
# LOGGING
# ═══════════════════════════════════════════════════════════════════════════════

os.makedirs(os.path.dirname(LOG_FILE), exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[
        logging.FileHandler(LOG_FILE),
        logging.StreamHandler(),
    ],
)
logger = logging.getLogger(__name__)

proxy_config = ProxyConfig.get_instance()


# ═══════════════════════════════════════════════════════════════════════════════
# HELPERS
# ═══════════════════════════════════════════════════════════════════════════════

def clean_html(html_str: str) -> str:
    if not html_str:
        return ""
    text = re.sub(r"<[^>]+>", " ", html_str)
    text = unescape(text)
    return re.sub(r"\s+", " ", text).strip()


def make_absolute_url(url: str, base: str = SITE_URL) -> str:
    if not url:
        return ""
    if url.startswith("http"):
        return url
    if url.startswith("//"):
        return f"https:{url}"
    return urljoin(base, url)


# ═══════════════════════════════════════════════════════════════════════════════
# FILTER HELPERS - date range + location filtering for job portals
# ═══════════════════════════════════════════════════════════════════════════════

# US state name → 2-letter code (for flexible location matching)
_US_STATES = {
    "alabama": "AL", "alaska": "AK", "arizona": "AZ", "arkansas": "AR",
    "california": "CA", "colorado": "CO", "connecticut": "CT", "delaware": "DE",
    "florida": "FL", "georgia": "GA", "hawaii": "HI", "idaho": "ID",
    "illinois": "IL", "indiana": "IN", "iowa": "IA", "kansas": "KS",
    "kentucky": "KY", "louisiana": "LA", "maine": "ME", "maryland": "MD",
    "massachusetts": "MA", "michigan": "MI", "minnesota": "MN", "mississippi": "MS",
    "missouri": "MO", "montana": "MT", "nebraska": "NE", "nevada": "NV",
    "new hampshire": "NH", "new jersey": "NJ", "new mexico": "NM", "new york": "NY",
    "north carolina": "NC", "north dakota": "ND", "ohio": "OH", "oklahoma": "OK",
    "oregon": "OR", "pennsylvania": "PA", "rhode island": "RI", "south carolina": "SC",
    "south dakota": "SD", "tennessee": "TN", "texas": "TX", "utah": "UT",
    "vermont": "VT", "virginia": "VA", "washington": "WA", "west virginia": "WV",
    "wisconsin": "WI", "wyoming": "WY", "district of columbia": "DC",
}


def build_filtered_url(base_url: str, days: int = None,
                       location: str = None, category: str = None) -> str:
    """Append filter parameters to a listing URL (URL-based filtering).

    Only applies params that are configured (non-empty) in the FILTER config.
    Preserves any existing query params on base_url.
    """
    parsed = urlparse(base_url)
    param_dict = dict(parse_qsl(parsed.query, keep_blank_values=True))

    if days is None:
        days = DATE_FILTER_DAYS
    if location is None:
        location = LOCATION_FILTER_VALUE
    if category is None:
        category = CATEGORY_FILTER_VALUE

    if days and DATE_FILTER_PARAM:
        param_dict[DATE_FILTER_PARAM] = str(days)
    if location and LOCATION_FILTER_PARAM:
        param_dict[LOCATION_FILTER_PARAM] = location
    if category and CATEGORY_FILTER_PARAM:
        param_dict[CATEGORY_FILTER_PARAM] = category

    new_query = urlencode(param_dict)
    url = f"{parsed.scheme}://{parsed.netloc}{parsed.path}"
    if new_query:
        url += f"?{new_query}"
    return url


def matches_location(location_str: str, target: str = None) -> bool:
    """Return True if a job's location matches the target.

    Flexible matching: accepts full state names ("Alabama"), 2-letter codes
    ("AL"), and partial city/state strings ("Birmingham, AL").  When target is
    empty/None, returns True (no location filter applied).
    """
    if target is None:
        target = LOCATION_FILTER_VALUE
    if not target:
        return True
    if not location_str:
        return False

    loc = location_str.lower()
    tgt = target.lower().strip()

    # Resolve target to a 2-letter state code: "alabama"→"AL", "al"→"AL"
    code = _US_STATES.get(tgt)
    is_code_input = len(tgt) == 2
    if not code and is_code_input:
        code = tgt.upper()

    # Boundary-aware match (case-insensitive) — handles "Birmingham, AL"
    if code:
        if re.search(
            r"(^|[\s,])" + re.escape(code) + r"([\s,]|$)", loc, re.IGNORECASE
        ):
            return True
        # If the target was itself a 2-letter code, only the boundary match
        # counts — a loose substring check would false-positive on words like
        # "Dallas" (contains "al").
        if is_code_input:
            return False

    # Loose substring match only for longer targets (state names, cities)
    if len(tgt) > 2 and tgt in loc:
        return True
    return False


def parse_posted_date(date_str: str) -> Optional[datetime]:
    """Parse a job posting date from many formats. Returns datetime or None.

    Handles ISO strings, common US formats, and relative phrases
    ("2 days ago", "today", "yesterday", "just posted").
    """
    if not date_str:
        return None
    s = str(date_str).strip()
    if not s:
        return None

    explicit_formats = [
        "%Y-%m-%d", "%Y-%m-%dT%H:%M:%S", "%Y-%m-%d %H:%M:%S",
        "%m/%d/%Y", "%m/%d/%y", "%B %d, %Y", "%b %d, %Y",
        "%d %B %Y", "%d %b %Y",
    ]
    for fmt in explicit_formats:
        try:
            return datetime.strptime(s, fmt)
        except ValueError:
            continue

    low = s.lower()
    now = datetime.now()
    if "today" in low or "just posted" in low or low == "just":
        return now
    if "yesterday" in low:
        return now - timedelta(days=1)

    m = re.search(r"(\d+)\s*(day|hour|week|month)s?\s*ago", low)
    if m:
        n = int(m.group(1))
        unit = m.group(2)
        if unit == "hour":
            return now - timedelta(hours=n)
        if unit == "day":
            return now - timedelta(days=n)
        if unit == "week":
            return now - timedelta(weeks=n)
        if unit == "month":
            return now - timedelta(days=n * 30)
    return None


def is_within_days(posted_date_str: str, max_days: int = None) -> bool:
    """Return True if a job's posted date is within max_days of now.

    If the date cannot be parsed, returns True (keep) so we don't silently drop
    jobs due to an unparseable date. Set max_days<=0 to disable the filter.
    """
    if max_days is None:
        max_days = DATE_FILTER_DAYS
    if not max_days or max_days <= 0:
        return True
    posted = parse_posted_date(posted_date_str)
    if posted is None:
        return True
    age_days = (datetime.now() - posted).days
    return age_days <= max_days


def fetch_page(url: str) -> Optional[tuple[BeautifulSoup, int]]:
    ssl_verify = proxy_config.config.get("strategy", {}).get("ssl_verify", False)
    escalation = proxy_config.get_escalation_tier()

    for tier in ["none", *escalation]:
        if should_warn_residential(tier):
            warn_residential_usage(url)

        proxies = proxy_config.get_proxy_dict(tier) if tier != "none" else None
        max_retries = proxy_config.get_max_retries(tier) if tier != "none" else MAX_RETRIES
        cooldown = proxy_config.get_cooldown(tier) if tier != "none" else DELAY_BETWEEN_REQUESTS * 2

        for attempt in range(max_retries):
            try:
                time.sleep(DELAY_BETWEEN_REQUESTS)
                response = requests.get(url, headers=HEADERS, proxies=proxies, timeout=proxy_config.get_timeout(), verify=ssl_verify)
                if response.status_code == 200:
                    response.raise_for_status()
                    return BeautifulSoup(response.text, "html.parser"), response.status_code
                if proxy_config.is_banned(response.status_code, response.text):
                    logger.warning(f"Ban detected ({response.status_code}) on tier '{tier}', escalating...")
                    break
                response.raise_for_status()
                return BeautifulSoup(response.text, "html.parser"), response.status_code
            except requests.RequestException as e:
                logger.error(f"Failed to fetch {url} (attempt {attempt + 1}/{max_retries}, tier={tier}): {e}")
                if attempt < max_retries - 1:
                    time.sleep(cooldown)

    return None


# ═══════════════════════════════════════════════════════════════════════════════
# EXTRACTION - CUSTOMIZE selectors below
# ═══════════════════════════════════════════════════════════════════════════════

def extract_jsonld(soup: BeautifulSoup) -> Optional[dict]:
    for script in soup.find_all("script", type="application/ld+json"):
        try:
            data = json.loads(script.string)
            if isinstance(data, dict) and data.get("@type") == "JobPosting":
                return data
            if isinstance(data, list):
                for item in data:
                    if isinstance(item, dict) and item.get("@type") == "JobPosting":
                        return item
        except (json.JSONDecodeError, TypeError):
            continue
    return None


def extract_job_from_page(soup: BeautifulSoup, url: str, status_code: int, src_url: str) -> dict:
    job = {
        "id": 0,
        "title": "",
        "company": "",
        "location": "",
        "salary": "",
        "description": "",
        "requirements": "",
        "job_type": "",
        "apply_url": "",
        "url": url,
        "src_url": src_url,
        "location_raw": "",
        "status_code": status_code,
        "scraped_at": datetime.now(timezone.utc).isoformat(),
        "remarks": "",
    }

    jsonld = extract_jsonld(soup)

    # Title
    if jsonld:
        job["title"] = jsonld.get("title", "")
    else:
        el = soup.select_one("{TITLE_SELECTOR}")
        job["title"] = el.get_text(strip=True) if el else ""

    # Company
    if jsonld:
        org = jsonld.get("hiringOrganization", {})
        if isinstance(org, dict):
            job["company"] = org.get("name", "")
        elif isinstance(org, str):
            job["company"] = org
    else:
        company_el = soup.select_one("{COMPANY_SELECTOR}")
        job["company"] = company_el.get_text(strip=True) if company_el else ""

    # Location
    if jsonld:
        loc = jsonld.get("jobLocation", {})
        if isinstance(loc, dict):
            address = loc.get("address", {})
            if isinstance(address, dict):
                parts = [address.get(p, "") for p in ("addressLocality", "addressRegion", "addressCountry")]
                job["location"] = ", ".join(p for p in parts if p)
    else:
        loc_el = soup.select_one("{LOCATION_SELECTOR}")
        job["location"] = loc_el.get_text(strip=True) if loc_el else ""

    # Salary
    if jsonld:
        salary = jsonld.get("baseSalary", {})
        if isinstance(salary, dict):
            val = salary.get("value", {})
            if isinstance(val, dict):
                min_v = val.get("minValue", "")
                max_v = val.get("maxValue", "")
                unit = salary.get("value", {}).get("unitText", "")
                if min_v and max_v:
                    job["salary"] = f"${min_v} - ${max_v} {unit}"
                elif min_v:
                    job["salary"] = f"${min_v} {unit}"
    else:
        salary_el = soup.select_one("{SALARY_SELECTOR}")
        job["salary"] = salary_el.get_text(strip=True) if salary_el else ""

    # Description
    if jsonld:
        job["description"] = jsonld.get("description", "")
    else:
        desc_el = soup.select_one("{DESCRIPTION_SELECTOR}")
        if desc_el:
            job["description"] = desc_el.get_text(separator="\n", strip=True)

    # Requirements
    if jsonld:
        quals = jsonld.get("qualifications", "")
        if isinstance(quals, str):
            job["requirements"] = quals
        elif isinstance(quals, list):
            job["requirements"] = "\n".join(str(q) for q in quals)
    else:
        req_el = soup.select_one("{REQUIREMENTS_SELECTOR}")
        if req_el:
            job["requirements"] = req_el.get_text(separator="\n", strip=True)

    # Job type
    if jsonld:
        emp_type = jsonld.get("employmentType", "")
        if isinstance(emp_type, str):
            job["job_type"] = emp_type
        elif isinstance(emp_type, list):
            job["job_type"] = ", ".join(emp_type)
    else:
        type_el = soup.select_one("{JOB_TYPE_SELECTOR}")
        job["job_type"] = type_el.get_text(strip=True) if type_el else ""

    # Apply URL
    apply_el = soup.select_one("{APPLY_URL_SELECTOR}")
    if apply_el:
        href = apply_el.get("href", "")
        job["apply_url"] = make_absolute_url(href)

    # Posted date (for date-range filtering)
    posted_raw = ""
    if jsonld:
        posted_raw = jsonld.get("datePosted", "") or jsonld.get("datePosted", "")
    if not posted_raw:
        pd_el = soup.select_one("{POSTED_DATE_SELECTOR}")
        if pd_el:
            posted_raw = pd_el.get_text(strip=True)
    job["posted_date"] = posted_raw
    parsed_dt = parse_posted_date(posted_raw)
    job["posted_date_parsed"] = parsed_dt.date().isoformat() if parsed_dt else ""

    return job


# ═══════════════════════════════════════════════════════════════════════════════
# DISCOVERY
# ═══════════════════════════════════════════════════════════════════════════════

def discover_job_urls(days: int = None, location: str = None,
                      category: str = None) -> list[str]:
    """Discover job URLs from the listing page, applying URL-based filters.

    When FILTER_METHOD is url/mixed and filter params are configured, the date
    and location params are appended to the listing URL so the site returns a
    pre-filtered result set. Pagination is followed until a page returns no
    new job links.
    """
    all_urls = []
    seen = set()
    page = 1

    # Apply URL-based filters to the base listing URL
    base = JOB_LISTING_URL
    if FILTER_METHOD in ("url", "mixed"):
        base = build_filtered_url(JOB_LISTING_URL, days=days, location=location, category=category)
        logger.info(f"Applied URL filters: {base}")

    while True:
        sep = "&" if "?" in base else "?"
        paginated_url = f"{base}{sep}page={page}"
        logger.info(f"Fetching listing page {page}: {paginated_url}")

        result = fetch_page(paginated_url)
        if not result:
            break

        soup, _ = result
        links = soup.select("{JOB_LINK_SELECTOR}")
        added_this_page = 0
        for link in links:
            href = link.get("href", "")
            absolute_url = make_absolute_url(href)
            if absolute_url and absolute_url not in seen:
                seen.add(absolute_url)
                all_urls.append(absolute_url)
                added_this_page += 1

        logger.info(f"Page {page}: {added_this_page} new jobs (total: {len(all_urls)})")

        if added_this_page == 0:
            break

        page += 1

    return all_urls


# ═══════════════════════════════════════════════════════════════════════════════
# INPUT HANDLING
# ═══════════════════════════════════════════════════════════════════════════════

def load_urls_from_file(filepath: str) -> list[str]:
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data.get("urls", [])


def save_urls_to_file(filepath: str, urls: list[str]) -> None:
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump({"urls": urls}, f, indent=2, ensure_ascii=False)
    logger.info(f"Saved {len(urls)} URLs to {filepath}")


# ═══════════════════════════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(description=f"Job scraper for {SITE_NAME}")
    parser.add_argument("--sample", action="store_true", help="Scrape only 5 jobs")
    parser.add_argument("--limit", type=int, default=None, help="Max jobs to scrape")
    parser.add_argument("--input", type=str, default=None, help="Path to input URLs JSON file")
    parser.add_argument("--urls", nargs="+", default=None, help="Job URLs as arguments")
    parser.add_argument("--days", type=int, default=DATE_FILTER_DAYS,
                        help="Max job age in days (default: last 7 days)")
    parser.add_argument("--location", type=str, default=LOCATION_FILTER_VALUE,
                        help="Location filter, e.g. 'Alabama' or 'AL'")
    # browser_service auto-appends --xvfb for browser-based scrapers; declare it
    # (ignored here) and use parse_known_args so any other injected runner flags
    # don't crash argparse on startup.
    parser.add_argument("--xvfb", action="store_true", help=argparse.SUPPRESS)
    args, _unknown = parser.parse_known_args()

    start_time = time.time()

    logger.info("=" * 80)
    logger.info(f"Starting job scraper for {SITE_NAME}")
    logger.info(f"Site: {SITE_URL}")
    logger.info(f"Listing URL: {JOB_LISTING_URL}")
    logger.info(f"Filter: last {args.days} days, location={args.location or '(all)'}")
    logger.info(f"Output: {OUTPUT_FILE}")
    logger.info("=" * 80)

    job_urls = []

    if args.urls:
        job_urls = args.urls
    elif args.input:
        job_urls = load_urls_from_file(args.input)
    elif os.path.exists(INPUT_FILE):
        job_urls = load_urls_from_file(INPUT_FILE)
    else:
        logger.info("No input_urls.json found. Discovering jobs from listing page...")
        job_urls = discover_job_urls(days=args.days, location=args.location)
        save_urls_to_file(INPUT_FILE, job_urls)

    if args.sample:
        job_urls = job_urls[:5]
    if args.limit:
        job_urls = job_urls[: args.limit]

    logger.info(f"Total jobs to scrape: {len(job_urls)}")

    results = []
    failed = 0
    skipped_filter = 0

    for i, url in enumerate(job_urls):
        result = fetch_page(url)
        if result:
            soup, status_code = result
            job = extract_job_from_page(soup, url, status_code, SRC_URL)
            job["id"] = i + 1

            # Client-side filtering (safety net — works regardless of filter mechanism)
            if not matches_location(job.get("location", ""), args.location):
                logger.info(f"Skipping (location '{job.get('location', '')}' != {args.location}): {url}")
                skipped_filter += 1
                continue
            if not is_within_days(job.get("posted_date", ""), args.days):
                logger.info(f"Skipping (older than {args.days}d, posted={job.get('posted_date', '')}): {url}")
                skipped_filter += 1
                continue

            results.append(job)
        else:
            logger.error(f"Failed to fetch: {url}")
            failed += 1

        if (i + 1) % 25 == 0:
            percent = ((i + 1) / len(job_urls)) * 100
            logger.info(f"Progress: [{i + 1}/{len(job_urls)}] ({percent:.1f}%)")

    output = {
        "site": {
            "name": SITE_NAME,
            "url": SITE_URL,
            "platform": PLATFORM,
            "scraping_method": SCRAPING_METHOD,
            "scraped_at": datetime.now(timezone.utc).isoformat(),
        },
        "jobs": results,
        "metadata": {
            "scraping_duration_seconds": round(time.time() - start_time, 2),
            "failed_items": failed,
            "skipped_by_filter": skipped_filter,
            "filters_applied": {
                "max_days": args.days,
                "location": args.location,
            },
            "rate_limit_delay": DELAY_BETWEEN_REQUESTS,
        },
    }

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(output, f, indent=2, ensure_ascii=False)

    logger.info("=" * 80)
    logger.info("EXTRACTION COMPLETE")
    logger.info(f"Total: {len(results)}, Failed: {failed}")
    logger.info(f"Duration: {round(time.time() - start_time, 2)}s")
    logger.info(f"Output: {OUTPUT_FILE}")
    logger.info("=" * 80)


if __name__ == "__main__":
    main()
