#!/usr/bin/env python3
"""
Navigation Scraper Template - Two-Phase Architecture

Phase 1: Navigate the site to discover item URLs (search, categories, pagination)
Phase 2: Scrape each discovered item page for structured data

Generated by Code Writer Agent for Universal Ecommerce Scraper.

Usage:
    python3 scraper.py --query "footwear sneakers"    # search mode
    python3 scraper.py --category-url "https://site.com/category/shoes"  # category mode
    python3 scraper.py --listing-url "https://site.com/shop"  # listing page mode
    python3 scraper.py --sample                       # scrape first 5 items only
    python3 scraper.py --limit 50                     # max 50 items
"""

import argparse
import json
import logging
import os
import sys
import time
from datetime import datetime, timezone
from typing import Optional

from playwright.sync_api import sync_playwright

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from src.proxy import build_proxy_url

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

# ═══════════════════════════════════════════════════════════════════════════════
# CONFIGURATION - Update these values based on navigation_analysis.json
# ═══════════════════════════════════════════════════════════════════════════════

SITE_NAME = "{SITE_NAME}"
SITE_URL = "{SITE_URL}"
PLATFORM = "{PLATFORM}"
SITE_SLUG = "{SITE_SLUG}"

# Phase 1: Navigation Configuration
SEARCH_URL_PATTERN = "{SEARCH_URL_PATTERN}"  # e.g. "https://site.com/search?q={query}"
SEARCH_BOX_SELECTOR = "{SEARCH_BOX_SELECTOR}"  # e.g. "input[type='search']"
SEARCH_SUBMIT_SELECTOR = "{SEARCH_SUBMIT_SELECTOR}"  # e.g. "button[type='submit']"
CATEGORY_URLS = {CATEGORY_URLS}  # list of category page URLs to crawl

# Phase 1: Pagination Configuration
PAGINATION_TYPE = "{PAGINATION_TYPE}"  # "next_button", "page_param", "infinite_scroll"
NEXT_BUTTON_SELECTOR = "{NEXT_BUTTON_SELECTOR}"  # e.g. "a.next-page"
PAGE_PARAM_NAME = "{PAGE_PARAM_NAME}"  # e.g. "page"
ITEMS_PER_PAGE = {ITEMS_PER_PAGE}  # page size (for offset-style pagination); null if unknown
MAX_PAGES = {MAX_PAGES}  # null for unlimited

# Phase 3 (JS-listing+pagination class fix): load-more pagination support.
# Ported from playwright_scraper.py (verified: +20 items/click on lw.com's
# Coveo listing, reaching ~3000 profiles). Navigation_scraper.py is the template
# code_writer actually uses for nav jobs (the playwright template was unreachable
# per the analysis); this ports the verified clicker into the reachable template.
MAX_DISCOVER_PAGES = 200

_LOAD_MORE_SELECTORS = [
    "[class*='load-more' i]", "[class*='loadMore' i]",
    "[class*='show-more' i]", "[class*='showMore' i]",
    "[class*='pager-next' i]", "[class*='pagerNext' i]",
    "button[aria-label*='more' i]", "a[aria-label*='next' i]",
    ".coveo-magicbox-load-more",
]


def _click_load_more(page) -> bool:
    """Click a visible+enabled load-more/show-more button if present.

    Returns True if clicked. Uses the 9-selector set from playwright_scraper.py
    (broad enough for Coveo, Algolia, React, Vue load-more patterns).
    """
    try:
        for sel in _LOAD_MORE_SELECTORS:
            btn = page.query_selector(sel)
            if btn and btn.is_visible() and btn.is_enabled():
                btn.click()
                return True
    except Exception:
        pass
    return False
TOTAL_COUNT_SELECTOR = "{TOTAL_COUNT_SELECTOR}"  # e.g. ".results-count"

# Coverage target: site-reported total item count (coverage_target.total_items
# from navigation_analysis). None when unknown → the discovery-coverage gate
# falls back to Tier 1 (stop_reason) only. code_writer may replace the None
# below with a concrete int when a trusted site-reported total exists.
COVERAGE_TARGET_TOTAL: Optional[int] = None

# Phase 1: Item Link Extraction
ITEM_CONTAINER_SELECTOR = "{ITEM_CONTAINER_SELECTOR}"  # e.g. ".product-grid"
ITEM_LINK_SELECTOR = "{ITEM_LINK_SELECTOR}"  # e.g. "a.product-link"
ITEM_URL_PATTERN = "{ITEM_URL_PATTERN}"  # e.g. r"/product/([^/]+)"

# Phase 2: Extraction Configuration (same as regular scraper)
SCRAPING_METHOD = "{SCRAPING_METHOD}"  # "playwright", "http_requests", etc.
PROXY_TIER = "{PROXY_TIER}"  # "none", "datacenter", "residential"
DELAY_BETWEEN_REQUESTS = {DELAY_BETWEEN_REQUESTS}
ROTATE_EVERY = 25  # relaunch the browser every N items/categories to avoid stealth-Chromium crashes under sustained load

# ── Checkpoint (B-core: resume after Chrome crash + service retry) ───────
# During Phase-1 discovery, discovered URLs are saved to a checkpoint file.
# If the scraper crashes (Chrome death → scraper_runner restarts Chrome +
# retries), the retry reads this file and skips re-discovery → resumes
# directly to Phase 2 (extraction). Generic: any navigation scraper.
# Path is SCRIPT_DIR (not cwd) so the checkpoint never leaks across sites
# when the working directory differs (contract §4 / L1).
_CHECKPOINT_PATH = os.path.join(SCRIPT_DIR, "discovered_urls_checkpoint.json")


def _write_checkpoint(urls: list[str]) -> None:
    """Save discovered URLs so a crash-retry can resume from here."""
    try:
        with open(_CHECKPOINT_PATH, "w") as f:
            json.dump({"urls": list(urls), "count": len(urls), "ts": time.time()}, f)
        logger.debug("Checkpoint: saved %d URLs to %s", len(urls), _CHECKPOINT_PATH)
    except Exception as exc:
        logger.warning("Checkpoint: write failed: %s", exc)


def _load_checkpoint() -> list[str]:
    """Load discovered URLs from a previous run's checkpoint (if any)."""
    try:
        if os.path.isfile(_CHECKPOINT_PATH):
            with open(_CHECKPOINT_PATH, "r") as f:
                data = json.load(f)
            urls = data.get("urls", [])
            if urls:
                logger.info("Checkpoint: RESUMING with %d URLs from %s", len(urls), _CHECKPOINT_PATH)
                return urls
    except Exception as exc:
        logger.warning("Checkpoint: load failed: %s", exc)
    return []
PAGE_LOAD_TIMEOUT = 30000
SRC_URL = SITE_URL

OUTPUT_KEY = "{OUTPUT_KEY}"  # "products", "articles", "jobs", etc.
CONTENT_TYPE = "{CONTENT_TYPE}"

CURRENCY = "{CURRENCY}" or "USD"

# Output filter: drop items that failed extraction (no title) or that lack any of
# the content type's core identifying fields. The broad discovery fallback can
# capture a few non-product pages (nav/category roots); this keeps the output
# clean. Derived from CONTENT_TYPE — generic, no site-specific field names.
_CONTENT_FILTER_FIELDS = {
    "product": ["price", "availability"],
    "article": ["author", "publish_date"],
    "job_posting": ["company", "location"],
    "forum_thread": ["author"],
    "serp": ["url", "snippet"],
    "page_content": [],
}
CORE_FILTER_FIELDS = _CONTENT_FILTER_FIELDS.get(CONTENT_TYPE, [])

# ═══════════════════════════════════════════════════════════════════════════════
# LOGGING
# ═══════════════════════════════════════════════════════════════════════════════

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)-5s [%(name)s] %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger(SITE_SLUG)


# ═══════════════════════════════════════════════════════════════════════════════
# PHASE 1: URL DISCOVERY
# ═══════════════════════════════════════════════════════════════════════════════

# ── Discovery-coverage signals (contract §1/§2) ────────────────────────
# A boolean `exhausted` is FORBIDDEN (H4): it cannot distinguish "genuinely
# exhausted" (short_page / no_new_items / no_next_link → PASS) from "gave up
# due to errors" (navigate_error → FAIL). We thread a `stop_reason` enum
# through every termination point so the gate can tell them apart.


def _new_discovery_state() -> dict:
    """Mutable accumulator for Phase-1 discovery-coverage signals.

    Default ``stop_reason`` is ``"no_next_link"`` (contract §2: the default when
    the loop completes without an explicit break). Each termination point
    overwrites it with the matching enum value via :func:`_set_stop_reason`.
    """
    return {
        "stop_reason": "no_next_link",
        "max_pages_hit": False,   # True only when a NON-None MAX_PAGES cap stopped the loop
        "dimensions_iterated": 0,
        "dimensions_total": 0,
    }


def _set_stop_reason(state: dict, reason: str) -> None:
    """Record why the discovery loop terminated.

    ``navigate_error`` is sticky (H4): once any phase gave up due to a fetch /
    block / rate-limit failure, it is preserved even if a later phase
    terminated normally — a single gave-up signal means the whole discovery is
    suspect and the gate must FAIL rather than PASS.
    """
    if state["stop_reason"] == "navigate_error" and reason != "navigate_error":
        return
    state["stop_reason"] = reason


def _discovery_goto(page, url: str, state: dict) -> bool:
    """Phase-1 page fetch for the discovery loop.

    Returns True on success; False on navigate failure (HTTP error, rate-limit
    429/502/503, gateway/5xx, timeout, or exception). On failure, sets the
    loop's ``stop_reason`` to ``"navigate_error"`` so the gate can distinguish
    a gave-up scraper from genuine exhaustion (H4 — the single most important
    distinction in the whole gate).
    """
    try:
        response = page.goto(url, timeout=PAGE_LOAD_TIMEOUT)
    except Exception as exc:
        logger.warning("Phase 1: navigate FAILED %s: %s", url[:80], exc)
        _set_stop_reason(state, "navigate_error")
        return False
    if response is None:
        logger.warning("Phase 1: navigate returned no response for %s", url[:80])
        _set_stop_reason(state, "navigate_error")
        return False
    status = getattr(response, "status", 0) or 0
    # Rate-limiting / gateway errors / server errors → gave up, NOT exhausted.
    if status in (429, 502, 503) or status >= 500:
        logger.warning("Phase 1: navigate HTTP %d on %s (rate-limit/block?)", status, url[:80])
        _set_stop_reason(state, "navigate_error")
        return False
    try:
        page.wait_for_load_state("domcontentloaded")
        time.sleep(8)
    except Exception as exc:
        logger.warning("Phase 1: load-wait failed %s: %s", url[:80], exc)
        _set_stop_reason(state, "navigate_error")
        return False
    return True


def _discover_urls_via_search(
    page,
    query: str,
    state: dict,
    max_pages: Optional[int] = None,
    limit: Optional[int] = None,
) -> list[str]:
    """Phase 1a: Discover item URLs by searching the site.

    Threads ``state`` (discovery-coverage signals) so every termination point
    records its ``stop_reason`` (contract §2). A ``navigate_error`` from
    :func:`_discovery_goto` is kept distinct from genuine exhaustion (H4).
    """
    search_url = SEARCH_URL_PATTERN.replace("{query}", query)
    logger.info("Phase 1: Searching for '%s' → %s", query, search_url)

    if not _discovery_goto(page, search_url, state):
        return []  # navigate_error already stamped

    all_urls: list[str] = _extract_item_links(page)

    current_page = 1
    while True:
        if max_pages and current_page >= max_pages:
            logger.info("Phase 1: Reached max_pages=%d", max_pages)
            state["max_pages_hit"] = True
            _set_stop_reason(state, "max_pages_hit")
            break
        if limit and len(all_urls) >= limit:
            logger.info("Phase 1: Reached limit=%d", limit)
            # No `limit_hit` enum exists (contract §2); a user cap is an
            # inconclusive termination, so it shares `max_pages_hit`. The
            # boolean above stays False — MAX_PAGES was not the cause.
            _set_stop_reason(state, "max_pages_hit")
            break

        # Phase 3: load-more pagination (Coveo/React/Vue load-more button).
        # Click the button + re-extract on the SAME page (no URL navigation).
        # Falls through to _get_next_page_url (page_param/next_button) if no
        # load-more button is found.
        if PAGINATION_TYPE in ("", "load_more", "infinite_scroll_tall"):
            if _click_load_more(page):
                page.wait_for_timeout(2500)
                new_urls = _extract_item_links(page)
                new_count = len(set(new_urls) - set(all_urls))
                logger.info(
                    "Phase 1: load-more click → %d new items (page %d)",
                    new_count, current_page + 1,
                )
                if new_count == 0:
                    _set_stop_reason(state, "no_new_items")
                    break
                all_urls.extend(new_urls)
                current_page += 1
                continue
            # No load-more button found → fall through to _get_next_page_url.

        next_url = _get_next_page_url(page, current_page + 1)
        if not next_url:
            logger.info("Phase 1: No more pages (page %d)", current_page)
            _set_stop_reason(state, "no_next_link")
            break

        logger.info("Phase 1: Navigating to page %d", current_page + 1)
        if not _discovery_goto(page, next_url, state):
            break  # navigate_error already stamped by _discovery_goto

        new_urls = _extract_item_links(page)
        new_count = len(set(new_urls) - set(all_urls))
        logger.info("Phase 1: Page %d → %d items (%d new)", current_page + 1, len(new_urls), new_count)

        if new_count == 0:
            logger.info("Phase 1: No new items on page %d, stopping", current_page + 1)
            _set_stop_reason(state, "no_new_items")
            break

        all_urls.extend(new_urls)
        current_page += 1

    unique_urls = list(dict.fromkeys(all_urls))
    if limit:
        unique_urls = unique_urls[:limit]
    logger.info("Phase 1: Discovered %d total item URLs", len(unique_urls))
    return unique_urls


def _discover_urls_via_category(
    page,
    category_url: str,
    state: dict,
    max_pages: Optional[int] = None,
    limit: Optional[int] = None,
) -> list[str]:
    """Phase 1b: Discover item URLs from a category page.

    Threads ``state`` (discovery-coverage signals) so every termination point
    records its ``stop_reason`` (contract §2). A ``navigate_error`` from
    :func:`_discovery_goto` is kept distinct from genuine exhaustion (H4).
    """
    logger.info("Phase 1: Browsing category → %s", category_url)

    if not _discovery_goto(page, category_url, state):
        return []  # navigate_error already stamped

    all_urls: list[str] = _extract_item_links(page)

    current_page = 1
    while True:
        if max_pages and current_page >= max_pages:
            state["max_pages_hit"] = True
            _set_stop_reason(state, "max_pages_hit")
            break
        if limit and len(all_urls) >= limit:
            _set_stop_reason(state, "max_pages_hit")  # cap → inconclusive (see search)
            break

        # Phase 3: load-more pagination (Coveo/React/Vue load-more button).
        # Click the button + re-extract on the SAME page (no URL navigation).
        # Falls through to _get_next_page_url (page_param/next_button) if no
        # load-more button is found.
        if PAGINATION_TYPE in ("", "load_more", "infinite_scroll_tall"):
            if _click_load_more(page):
                page.wait_for_timeout(2500)
                new_urls = _extract_item_links(page)
                new_count = len(set(new_urls) - set(all_urls))
                logger.info(
                    "Phase 1: load-more click → %d new items (page %d)",
                    new_count, current_page + 1,
                )
                if new_count == 0:
                    _set_stop_reason(state, "no_new_items")
                    break
                all_urls.extend(new_urls)
                current_page += 1
                continue
            # No load-more button found → fall through to _get_next_page_url.

        next_url = _get_next_page_url(page, current_page + 1)
        if not next_url:
            _set_stop_reason(state, "no_next_link")
            break

        logger.info("Phase 1: Category page %d", current_page + 1)
        if not _discovery_goto(page, next_url, state):
            break  # navigate_error already stamped by _discovery_goto

        new_urls = _extract_item_links(page)
        if not new_urls or not (set(new_urls) - set(all_urls)):
            _set_stop_reason(state, "no_new_items")
            break

        all_urls.extend(new_urls)
        current_page += 1

    unique_urls = list(dict.fromkeys(all_urls))
    if limit:
        unique_urls = unique_urls[:limit]
    logger.info("Phase 1: Discovered %d total item URLs from category", len(unique_urls))
    return unique_urls


def _extract_item_links(page) -> list[str]:
    """Extract item page URLs from a listing page."""
    links: list[str] = []
    try:
        containers = page.query_selector_all(ITEM_CONTAINER_SELECTOR)
        for container in containers:
            link_elements = container.query_selector_all(ITEM_LINK_SELECTOR)
            for link_el in link_elements:
                href = link_el.get_attribute("href") or ""
                if href:
                    if href.startswith("/"):
                        href = SITE_URL.rstrip("/") + href
                    links.append(href)
    except Exception as exc:
        logger.warning("Phase 1: Error extracting item links: %s", exc)

    if not links:
        try:
            link_elements = page.query_selector_all(ITEM_LINK_SELECTOR)
            for link_el in link_elements:
                href = link_el.get_attribute("href") or ""
                if href:
                    if href.startswith("/"):
                        href = SITE_URL.rstrip("/") + href
                    links.append(href)
        except Exception as exc:
            logger.warning("Phase 1: Fallback link extraction failed: %s", exc)

    # Robust final fallback: if selector-based extraction found too few links,
    # capture ALL same-domain anchor hrefs and keep only those that look like
    # item-detail pages (via the generic _is_product_url structural check — no
    # hardcoded token list). The primary card selectors above do the real work;
    # this only fires when they miss, and the soft-404 check + output filter
    # catch any non-item page that still slips through.
    if len(links) < 20:
        try:
            all_hrefs = page.eval_on_selector_all(
                "a[href]", "els => els.map(e => e.href)"
            )
            existing = set(links)
            for h in all_hrefs:
                if h in existing:
                    continue
                if not _is_product_url(h):
                    continue
                links.append(h)
                existing.add(h)
            logger.info(
                "Phase 1: robust fallback captured %d same-domain links", len(links)
            )
        except Exception as exc:
            logger.warning("Phase 1: robust link fallback failed: %s", exc)

    return links


def _is_product_url(href: str) -> bool:
    """Generic item-detail URL detector — no site-specific tokens.

    True for same-domain URLs whose path looks like a detail page (deep/long slug,
    usually carrying a numeric product code); False for shallow nav/category roots
    (``/women``, ``/sale``, ``/account``, locale roots like ``/en-us``). Structural
    floor only — code_writer may override it with a tighter per-site version (regex
    + slug list from product_analysis) when there's enough signal.
    """
    from urllib.parse import urlparse

    if not href:
        return False
    site_host = (urlparse(SITE_URL).hostname or "").lower()
    if site_host and site_host not in href.lower():
        return False
    path = urlparse(href).path.strip("/")
    if not path or len(path) < 6:
        return False
    segs = path.split("/")
    last = segs[-1]
    # shallow single-segment root with no digit → nav/category (e.g. /women, /sale)
    if len(segs) == 1 and len(last) < 12 and not any(c.isdigit() for c in last):
        return False
    return True


def _set_cascading_selects(page, ordered_fields) -> None:
    """Set form ``<select>`` fields in DEPENDENCY order (parent before child).

    Cascading/dependent dropdowns (Discipline→Specialty, Country→State,
    Category→Subcategory) repopulate the child's options when the parent
    changes — setting the parent AFTER the child wipes the child's selection.
    Each field: ``{"selector": "...", "value": "..."}``, ordered parent-first.
    A short sleep after each select lets the child repopulate before we set it.
    Safe even for independent selects (sleep is harmless; order is arbitrary).
    """
    for f in ordered_fields:
        try:
            page.select_option(f["selector"], str(f["value"]))
            time.sleep(0.5)
        except Exception as _e:
            logger.warning("select_option(%s, %s) failed: %s", f.get("selector"), f.get("value"), _e)


def _set_query_param(url: str, param: str, value) -> str:
    """Return ``url`` with the query ``param`` REPLACED (not appended).

    Using urllib.parse ensures we never produce duplicate params
    (``?pgNum=2&pgNum=3``) which servers resolve inconsistently and which
    caused pagination to re-fetch earlier pages. Generic for any param name.
    """
    from urllib.parse import urlparse, parse_qsl, urlencode, urlunparse

    p = urlparse(url)
    qs = [(k, v) for k, v in parse_qsl(p.query, keep_blank_values=True) if k != param]
    qs.append((param, str(value)))
    return urlunparse(p._replace(query=urlencode(qs)))


# Offset-style params (value = (page-1)*items_per_page, not the page number).
_OFFSET_PARAMS = {"offset", "start", "skip", "begin", "from"}


def _get_next_page_url(page, next_page_num: int) -> Optional[str]:
    """Determine the URL for the next page of results.

    PREFERRED: construct ``?{PAGE_PARAM_NAME}=N`` directly when a page param
    is known — deterministic, DOM-independent, immune to the first-match
    pitfall of clicking numbered pager links (``a[href*='pgNum']`` matches
    EVERY page link; the first is page 1 → re-fetching page 1 forever).
    Only fall back to SEMANTIC click selectors (``a[rel="next"]``) when no
    param is known or for cursor/infinite-scroll types.
    """
    # 1. CONSTRUCTION-FIRST whenever a page param is known (covers page_param
    #    AND unknown-type sites where PAGE_PARAM_NAME happened to be filled).
    if PAGE_PARAM_NAME and PAGE_PARAM_NAME not in ("", "{PAGE_PARAM_NAME}"):
        if PAGINATION_TYPE in ("page_param", "", None) or (
            PAGINATION_TYPE not in ("cursor", "infinite_scroll", "load_more")
        ):
            if PAGE_PARAM_NAME in _OFFSET_PARAMS:
                value = (next_page_num - 1) * (ITEMS_PER_PAGE or 25)
            else:
                value = next_page_num
            return _set_query_param(page.url, PAGE_PARAM_NAME, value)

    # 2. Explicit next-button (selector-driven) — only when declared.
    if PAGINATION_TYPE == "next_button" and NEXT_BUTTON_SELECTOR:
        try:
            btn = page.query_selector(NEXT_BUTTON_SELECTOR)
            if btn:
                href = btn.get_attribute("href") or ""
                if href:
                    if href.startswith("/"):
                        href = SITE_URL.rstrip("/") + href
                    return href
                try:
                    btn.click()
                    page.wait_for_load_state("domcontentloaded")
                    time.sleep(8)
                    if page.url:
                        return page.url
                except Exception:
                    pass
        except Exception:
            pass
        return None

    # 3. LAST RESORT: SEMANTIC next-button selectors (never substring-on-param).
    #    Cursor/infinite_scroll/unknown types land here. The discovery loop
    #    terminates on no-new-items, so this is bounded by MAX_PAGES + dedup.
    for sel in (
        'a[rel="next"]', 'a.next', 'li.next a', '[aria-label*="next" i]',
        'a:has-text("Next")', 'button:has-text("Next")',
    ):
        try:
            btn = page.query_selector(sel)
            if btn:
                href = btn.get_attribute("href") or ""
                if href:
                    if href.startswith("http"):
                        return href
                    return SITE_URL.rstrip("/") + (href if href.startswith("/") else "/" + href)
                btn.click()
                page.wait_for_load_state("domcontentloaded")
                time.sleep(8)
                if page.url:
                    return page.url
        except Exception:
            pass
    return None


# ═══════════════════════════════════════════════════════════════════════════════
# PHASE 2: ITEM EXTRACTION
# ═══════════════════════════════════════════════════════════════════════════════


def _extract_item_data(page, url: str, src_url: str) -> dict:
    """Phase 2: Extract structured data from a single item page.

    Customize this function based on content type and field selectors.
    """
    try:
        page.goto(url, timeout=PAGE_LOAD_TIMEOUT)
        page.wait_for_load_state("domcontentloaded")
        time.sleep(1)
    except Exception as exc:
        logger.error("Phase 2: Failed to load %s: %s", url[:80], exc)
        return _error_item(url, src_url, str(exc))

    item: dict = {
        "url": url,
        "src_url": src_url,
        "status_code": page.url and 200 or 0,
        "scraped_at": datetime.now(timezone.utc).isoformat(),
        "remarks": "",
    }

    try:
        json_ld_data = page.evaluate(
            "() => { "
            "  const scripts = document.querySelectorAll('script[type=\"application/ld+json\"]'); "
            "  return Array.from(scripts).map(s => { try { return JSON.parse(s.textContent); } catch(e) { return null; } }).filter(Boolean); "
            "}"
        )

        for block in json_ld_data:
            block_type = block.get("@type", "")
            if CONTENT_TYPE == "product" and block_type in ("Product",):
                item["title"] = block.get("name", "")
                offers = block.get("offers", {})
                if isinstance(offers, dict):
                    price = offers.get("price", "")
                    currency = offers.get("priceCurrency", CURRENCY)
                    item["price"] = f"{currency}{price}" if price else ""
                    item["availability"] = "In Stock"
                    avail = offers.get("availability", "")
                    if "OutOfStock" in avail or "SoldOut" in avail:
                        item["availability"] = "Out of Stock"
                elif isinstance(offers, list):
                    for offer in offers:
                        if isinstance(offer, dict):
                            price = offer.get("price", "")
                            currency = offer.get("priceCurrency", CURRENCY)
                            item["price"] = f"{currency}{price}" if price else ""
                            break
                item["currency"] = block.get("offers", {}).get("priceCurrency", CURRENCY) if isinstance(block.get("offers"), dict) else CURRENCY
                item["description"] = block.get("description", "")
                item["images"] = block.get("image", [])
                if isinstance(item["images"], str):
                    item["images"] = [item["images"]]
                break

            elif CONTENT_TYPE == "article" and block_type in ("Article", "NewsArticle", "BlogPosting"):
                item["title"] = block.get("headline", block.get("name", ""))
                author = block.get("author", {})
                if isinstance(author, dict):
                    item["author"] = author.get("name", "")
                elif isinstance(author, list) and author:
                    item["author"] = author[0].get("name", "")
                item["publish_date"] = block.get("datePublished", "")
                item["content"] = block.get("articleBody", "")
                item["images"] = block.get("image", [])
                if isinstance(item["images"], str):
                    item["images"] = [item["images"]]
                break

            elif CONTENT_TYPE == "job_posting" and block_type == "JobPosting":
                item["title"] = block.get("title", "")
                org = block.get("hiringOrganization", {})
                item["company"] = org.get("name", "") if isinstance(org, dict) else ""
                loc = block.get("jobLocation", {})
                if isinstance(loc, dict):
                    addr = loc.get("address", {})
                    if isinstance(addr, dict):
                        item["location"] = addr.get("addressLocality", "")
                item["description"] = block.get("description", "")
                break

    except Exception as exc:
        logger.warning("Phase 2: JSON-LD extraction failed for %s: %s", url[:60], exc)

    if not item.get("title"):
        try:
            h1 = page.query_selector("h1")
            if h1:
                item["title"] = (h1.text_content() or "").strip()
        except Exception:
            pass

    return item


def _error_item(url: str, src_url: str, error: str) -> dict:
    return {
        "url": url,
        "src_url": src_url,
        "status_code": 0,
        "scraped_at": datetime.now(timezone.utc).isoformat(),
        "remarks": f"Error: {error[:200]}",
    }


def _browser_alive(page) -> bool:
    """Trivial probe — returns False if the page/context/browser has died.

    Stealth Chromium (CloakBrowser) can crash under sustained load (observed:
    dies after ~40-50 page loads on heavy anti-bot SPAs), surfacing as
    "Target page, context or browser has been closed" on the next goto. Because
    ``_extract_item_data`` catches goto errors internally, the outer loop would
    otherwise keep appending error-items for every remaining URL. This probe lets
    the loop detect the death and relaunch the browser. Generic.
    """
    try:
        page.evaluate("1")
        return True
    except Exception:
        return False


# ═══════════════════════════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════════════════════════


def main():
    parser = argparse.ArgumentParser(description=f"{SITE_NAME} Navigation Scraper")
    parser.add_argument("--query", type=str, help="Search query for navigation mode")
    parser.add_argument("--category-url", type=str, help="Category URL to crawl")
    parser.add_argument("--listing-url", type=str, help="Listing page URL to paginate")
    parser.add_argument("--sample", action="store_true", help="Scrape first 5 items only")
    parser.add_argument("--limit", type=int, default=None, help="Max items to scrape")
    parser.add_argument("--no-proxy", action="store_true", help="Disable proxy")
    parser.add_argument("--headless", action="store_true", default=True, help="Headless mode")
    # Discovery-coverage gate (contract §3):
    #   --discover-only   run Phase 1 to exhaustion, emit discovery_coverage, SKIP Phase 2
    #   --fresh-discovery ignore any existing checkpoint, run Phase 1 from scratch (H3)
    parser.add_argument("--discover-only", action="store_true",
                        help="Run Phase 1 discovery only; skip Phase 2 extraction")
    parser.add_argument("--fresh-discovery", action="store_true",
                        help="Ignore existing checkpoint; run Phase 1 from scratch")
    args = parser.parse_args()

    # F6 DETERMINISTIC DISCOVERY GATE (env-var): see http_navigation_scraper.
    _env_listing = os.environ.get("SCRAPER_LISTING_URL", "").strip()
    if _env_listing:
        args.listing_url = _env_listing
        args.fresh_discovery = True
        logger.info("Env gate: SCRAPER_LISTING_URL → --listing-url %s (fresh)",
                    _env_listing[:80])

    limit = 5 if args.sample else args.limit

    proxy_url = None
    if not args.no_proxy and PROXY_TIER != "none":
        proxy_url = build_proxy_url(PROXY_TIER)

    start_time = time.time()
    discovered_urls: list[str] = []
    items: list[dict] = []

    # Discovery-coverage accumulator (contract §1/§2). Threaded through every
    # Phase-1 termination point so the gate can tell genuine exhaustion apart
    # from a scraper that gave up (H4). `navigate_error` is sticky.
    discovery_state = _new_discovery_state()
    ran_phase1 = False
    skipped_reason: Optional[str] = None

    # B-core: check for checkpoint from a previous (crashed) run.
    # If found (and --fresh-discovery not passed), skip Phase 1 entirely and
    # resume at Phase 2 (extraction). --fresh-discovery ignores the checkpoint
    # so the execution phase doesn't silently reuse the test phase's URLs (H3).
    _checkpoint_urls = [] if args.fresh_discovery else _load_checkpoint()
    if _checkpoint_urls:
        discovered_urls = _checkpoint_urls
        skipped_reason = "checkpoint_loaded"
        logger.info("Phase 1: SKIPPED (resumed from checkpoint with %d URLs)", len(discovered_urls))

    with sync_playwright() as p:
        def _launch_browser():
            browser_args = []
            if proxy_url:
                browser_args.append(f"--proxy-server={proxy_url}")
            logger.debug("Phase 1: launching browser (proxy=%s, headless=%s)", bool(proxy_url), args.headless)
            b = p.chromium.launch(headless=args.headless, args=browser_args)
            ctx = b.new_context(
                viewport={"width": 1920, "height": 1080},
                user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
            )
            return b, ctx, ctx.new_page()

        browser, context, page = _launch_browser()

        # ── Phase 1: Discover URLs ───────────────────────────────────────
        if not discovered_urls:
            ran_phase1 = True
            if args.query:
                logger.info("Phase 1: discovering via search '%s'", args.query[:50])
                discovered_urls = _discover_urls_via_search(page, args.query, discovery_state, MAX_PAGES, limit)
                src_url_base = SEARCH_URL_PATTERN.replace("{query}", args.query)
            elif args.category_url:
                logger.info("Phase 1: discovering via category %s", args.category_url[:50])
                discovered_urls = _discover_urls_via_category(page, args.category_url, discovery_state, MAX_PAGES, limit)
                src_url_base = args.category_url
            elif args.listing_url:
                logger.info("Phase 1: discovering via listing %s", args.listing_url[:50])
                discovered_urls = _discover_urls_via_category(page, args.listing_url, discovery_state, MAX_PAGES, limit)
                src_url_base = args.listing_url
            else:
                logger.error("No --query, --category-url, or --listing-url provided")
                browser.close()
                sys.exit(1)
            logger.info("Phase 1: discovered %d URLs (pre-category)", len(discovered_urls))
            # B-core: checkpoint after initial discovery.
            _write_checkpoint(discovered_urls)
        else:
            src_url_base = args.query or args.category_url or args.listing_url or "(checkpoint)"

        # ── Phase 1b: Also discover from CATEGORY_URLS (dimension loop) ──
        # Each category is one "dimension" (contract §1: dimensions_iterated /
        # dimensions_total). Skipped under --sample (bounded test probe) or
        # when resuming from a checkpoint.
        if not args.sample and CATEGORY_URLS and not _checkpoint_urls:
            discovery_state["dimensions_total"] = len(CATEGORY_URLS)
            _existing = set(discovered_urls)
            _search_q = (args.query or "").lower()
            _cat_idx = 0
            for _cat_url in CATEGORY_URLS:
                if not isinstance(_cat_url, str) or _cat_url in _existing:
                    continue
                if _search_q and _search_q not in _cat_url.lower():
                    continue
                _cat_idx += 1
                try:
                    logger.info("Phase 1b [%d]: visiting category %s", _cat_idx, _cat_url[:60])
                    _cat_urls = _discover_urls_via_category(page, _cat_url, discovery_state, MAX_PAGES, limit)
                    _new = [u for u in _cat_urls if u not in _existing]
                    if _new:
                        discovered_urls.extend(_new)
                        _existing.update(_new)
                        logger.info("Phase 1b [%d]: %s -> %d new URLs (total %d)", _cat_idx, _cat_url[:40], len(_new), len(discovered_urls))
                    # B-core: checkpoint after each category (incremental progress).
                    _write_checkpoint(discovered_urls)
                except Exception as _cat_exc:
                    logger.warning("Phase 1b [%d]: category %s failed: %s", _cat_idx, _cat_url[:40], _cat_exc)

                # B-prevent: rotate browser every ROTATE_EVERY categories to
                # prevent Chrome death on long discovery (e.g. 200+ specialties).
                if _cat_idx > 0 and _cat_idx % ROTATE_EVERY == 0:
                    logger.info("Phase 1b [%d]: rotating browser (alive=%s)", _cat_idx, _browser_alive(page))
                    try:
                        browser.close()
                    except Exception:
                        pass
                    browser, context, page = _launch_browser()
                    time.sleep(3)

            discovery_state["dimensions_iterated"] = _cat_idx
            discovered_urls = list(dict.fromkeys(discovered_urls))
            if limit:
                discovered_urls = discovered_urls[:limit]
            # B-core: final checkpoint after all categories.
            _write_checkpoint(discovered_urls)
            logger.info("Phase 1 complete: %d total URLs discovered (%d/%d dimensions)",
                        len(discovered_urls), _cat_idx, len(CATEGORY_URLS))

        # Stamp skipped state when Phase 1 never ran (checkpoint resume).
        if not ran_phase1:
            _set_stop_reason(discovery_state, "skipped")

        # --discover-only (contract §3): Phase 1 ran; SKIP Phase 2 extraction.
        # The output's item list stays empty; the consumer reads discovered_urls
        # / stop_reason / dimensions_* from discovery_coverage. `found` is 0.
        if args.discover_only:
            logger.info("--discover-only: skipping Phase 2 extraction (discovery-only probe)")

        if not discovered_urls:
            # Discovery ran but found nothing (often navigate_error). Don't
            # sys.exit — we still emit output so the gate can see the failure.
            logger.warning("No item URLs discovered (stop_reason=%s)", discovery_state["stop_reason"])

        if discovered_urls and not args.discover_only:
            # ── Phase 2: Extract data from each URL ────────────────────
            logger.info("Phase 2: Extracting data from %d items", len(discovered_urls))
            total = len(discovered_urls)

            for i, url in enumerate(discovered_urls, 1):
                logger.info("Progress: [%d/%d] (%.1f%%", i, total, (i / total) * 100)
                logger.info("Scraping: %s", url[:100])

                # Detect a dead browser (stealth Chromium can crash under sustained
                # load) and relaunch before attempting the item, so one mid-run crash
                # doesn't fail every remaining URL. Proactively rotate the context
                # every ROTATE_EVERY items to release memory buildup.
                if (not _browser_alive(page)) or (i > 1 and (i - 1) % ROTATE_EVERY == 0):
                    if i > 1:
                        logger.warning("Phase 2: relaunching browser at item %d (alive=%s)", i, _browser_alive(page))
                        try:
                            browser.close()
                        except Exception:
                            pass
                        browser, context, page = _launch_browser()
                        time.sleep(3)

                try:
                    item = _extract_item_data(page, url, src_url_base)
                    items.append(item)
                except Exception as exc:
                    logger.error("Failed to extract %s: %s", url[:80], exc)
                    items.append(_error_item(url, src_url_base, str(exc)))

                if i < total:
                    time.sleep(DELAY_BETWEEN_REQUESTS)

        browser.close()

    # ── Write output ────────────────────────────────────────────────────
    # Output filter: drop extraction failures + items lacking any core field.
    _extra = [f for f in CORE_FILTER_FIELDS if f and f != "title"]
    _before = len(items)
    items = [it for it in items if it.get("title") and (not _extra or any(it.get(f) for f in _extra))]
    if len(items) != _before:
        logger.info("output filter: %d → %d items (dropped %d without core fields)", _before, len(items), _before - len(items))

    # Discovery-coverage block (contract §1). `found` is the POST-FILTER
    # extracted item count (0 when Phase 2 was skipped via --discover-only or
    # when discovery found nothing) — NOT raw len(discovered_urls).
    discovery_coverage = {
        "stop_reason": discovery_state["stop_reason"],
        "found": len(items),
        "discovered_urls": len(discovered_urls),
        "expected_total": COVERAGE_TARGET_TOTAL,
        "dimensions_iterated": discovery_state["dimensions_iterated"],
        "dimensions_total": discovery_state["dimensions_total"],
        "max_pages_hit": discovery_state["max_pages_hit"],
        "ran_phase1": ran_phase1,
        "skipped_reason": skipped_reason,
    }

    output = {
        "site": {
            "name": SITE_NAME,
            "url": SITE_URL,
            "platform": PLATFORM,
            "scraping_method": "playwright_navigation",
            "scraped_at": datetime.now(timezone.utc).isoformat(),
        },
        OUTPUT_KEY: items,
        "metadata": {
            "scraping_duration_seconds": round(time.time() - start_time, 1),
            "discovered_urls": len(discovered_urls),
            "extracted_items": len(items),
            "discovery_coverage": discovery_coverage,
        },
    }

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d_%H%M%S")
    output_filename = os.path.join(SCRIPT_DIR, f"output_{timestamp}.json")

    with open(output_filename, "w", encoding="utf-8") as f:
        json.dump(output, f, indent=2, ensure_ascii=False, default=str)

    logger.info(
        "Done: %d/%d items in %.1fs (stop_reason=%s) → %s",
        len([i for i in items if i.get("title")]),
        len(discovered_urls),
        time.time() - start_time,
        discovery_state["stop_reason"],
        output_filename,
    )


if __name__ == "__main__":
    main()
