#!/usr/bin/env python3
"""
Navigation Scraper Template - Two-Phase Architecture

Phase 1: Navigate the site to discover item URLs (search, categories, pagination)
Phase 2: Scrape each discovered item page for structured data

Generated by Code Writer Agent for Universal Ecommerce Scraper.

Usage:
    python3 scraper.py --query "footwear sneakers"    # search mode
    python3 scraper.py --category-url "https://site.com/category/shoes"  # category mode
    python3 scraper.py --listing-url "https://site.com/shop"  # listing page mode
    python3 scraper.py --sample                       # scrape first 5 items only
    python3 scraper.py --limit 50                     # max 50 items
"""

import argparse
import json
import logging
import os
import sys
import time
from datetime import datetime, timezone
from typing import Optional

from playwright.sync_api import sync_playwright

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from src.proxy import build_proxy_url

# ═══════════════════════════════════════════════════════════════════════════════
# CONFIGURATION - Update these values based on navigation_analysis.json
# ═══════════════════════════════════════════════════════════════════════════════

SITE_NAME = "{SITE_NAME}"
SITE_URL = "{SITE_URL}"
PLATFORM = "{PLATFORM}"
SITE_SLUG = "{SITE_SLUG}"

# Phase 1: Navigation Configuration
SEARCH_URL_PATTERN = "{SEARCH_URL_PATTERN}"  # e.g. "https://site.com/search?q={query}"
SEARCH_BOX_SELECTOR = "{SEARCH_BOX_SELECTOR}"  # e.g. "input[type='search']"
SEARCH_SUBMIT_SELECTOR = "{SEARCH_SUBMIT_SELECTOR}"  # e.g. "button[type='submit']"
CATEGORY_URLS = {CATEGORY_URLS}  # list of category page URLs to crawl

# Phase 1: Pagination Configuration
PAGINATION_TYPE = "{PAGINATION_TYPE}"  # "next_button", "page_param", "infinite_scroll"
NEXT_BUTTON_SELECTOR = "{NEXT_BUTTON_SELECTOR}"  # e.g. "a.next-page"
PAGE_PARAM_NAME = "{PAGE_PARAM_NAME}"  # e.g. "page"
MAX_PAGES = {MAX_PAGES}  # null for unlimited
TOTAL_COUNT_SELECTOR = "{TOTAL_COUNT_SELECTOR}"  # e.g. ".results-count"

# Phase 1: Item Link Extraction
ITEM_CONTAINER_SELECTOR = "{ITEM_CONTAINER_SELECTOR}"  # e.g. ".product-grid"
ITEM_LINK_SELECTOR = "{ITEM_LINK_SELECTOR}"  # e.g. "a.product-link"
ITEM_URL_PATTERN = "{ITEM_URL_PATTERN}"  # e.g. r"/product/([^/]+)"

# Phase 2: Extraction Configuration (same as regular scraper)
SCRAPING_METHOD = "{SCRAPING_METHOD}"  # "playwright", "http_requests", etc.
PROXY_TIER = "{PROXY_TIER}"  # "none", "datacenter", "residential"
DELAY_BETWEEN_REQUESTS = {DELAY_BETWEEN_REQUESTS}
PAGE_LOAD_TIMEOUT = 30000
SRC_URL = SITE_URL

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_KEY = "{OUTPUT_KEY}"  # "products", "articles", "jobs", etc.
CONTENT_TYPE = "{CONTENT_TYPE}"

CURRENCY = "{CURRENCY}" or "USD"

# ═══════════════════════════════════════════════════════════════════════════════
# LOGGING
# ═══════════════════════════════════════════════════════════════════════════════

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)-5s [%(name)s] %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger(SITE_SLUG)


# ═══════════════════════════════════════════════════════════════════════════════
# PHASE 1: URL DISCOVERY
# ═══════════════════════════════════════════════════════════════════════════════


def _discover_urls_via_search(
    page,
    query: str,
    max_pages: Optional[int] = None,
    limit: Optional[int] = None,
) -> list[str]:
    """Phase 1a: Discover item URLs by searching the site."""
    search_url = SEARCH_URL_PATTERN.replace("{query}", query)
    logger.info("Phase 1: Searching for '%s' → %s", query, search_url)

    page.goto(search_url, timeout=PAGE_LOAD_TIMEOUT)
    page.wait_for_load_state("networkidle")
    time.sleep(2)

    all_urls: list[str] = _extract_item_links(page)

    current_page = 1
    while True:
        if max_pages and current_page >= max_pages:
            logger.info("Phase 1: Reached max_pages=%d", max_pages)
            break
        if limit and len(all_urls) >= limit:
            logger.info("Phase 1: Reached limit=%d", limit)
            break

        next_url = _get_next_page_url(page, current_page + 1)
        if not next_url:
            logger.info("Phase 1: No more pages (page %d)", current_page)
            break

        logger.info("Phase 1: Navigating to page %d", current_page + 1)
        page.goto(next_url, timeout=PAGE_LOAD_TIMEOUT)
        page.wait_for_load_state("networkidle")
        time.sleep(2)

        new_urls = _extract_item_links(page)
        new_count = len(set(new_urls) - set(all_urls))
        logger.info("Phase 1: Page %d → %d items (%d new)", current_page + 1, len(new_urls), new_count)

        if new_count == 0:
            logger.info("Phase 1: No new items on page %d, stopping", current_page + 1)
            break

        all_urls.extend(new_urls)
        current_page += 1

    unique_urls = list(dict.fromkeys(all_urls))
    if limit:
        unique_urls = unique_urls[:limit]
    logger.info("Phase 1: Discovered %d total item URLs", len(unique_urls))
    return unique_urls


def _discover_urls_via_category(
    page,
    category_url: str,
    max_pages: Optional[int] = None,
    limit: Optional[int] = None,
) -> list[str]:
    """Phase 1b: Discover item URLs from a category page."""
    logger.info("Phase 1: Browsing category → %s", category_url)
    page.goto(category_url, timeout=PAGE_LOAD_TIMEOUT)
    page.wait_for_load_state("networkidle")
    time.sleep(2)

    all_urls: list[str] = _extract_item_links(page)

    current_page = 1
    while True:
        if max_pages and current_page >= max_pages:
            break
        if limit and len(all_urls) >= limit:
            break

        next_url = _get_next_page_url(page, current_page + 1)
        if not next_url:
            break

        logger.info("Phase 1: Category page %d", current_page + 1)
        page.goto(next_url, timeout=PAGE_LOAD_TIMEOUT)
        page.wait_for_load_state("networkidle")
        time.sleep(2)

        new_urls = _extract_item_links(page)
        if not new_urls or not (set(new_urls) - set(all_urls)):
            break

        all_urls.extend(new_urls)
        current_page += 1

    unique_urls = list(dict.fromkeys(all_urls))
    if limit:
        unique_urls = unique_urls[:limit]
    logger.info("Phase 1: Discovered %d total item URLs from category", len(unique_urls))
    return unique_urls


def _extract_item_links(page) -> list[str]:
    """Extract item page URLs from a listing page."""
    links: list[str] = []
    try:
        containers = page.query_selector_all(ITEM_CONTAINER_SELECTOR)
        for container in containers:
            link_elements = container.query_selector_all(ITEM_LINK_SELECTOR)
            for link_el in link_elements:
                href = link_el.get_attribute("href") or ""
                if href:
                    if href.startswith("/"):
                        href = SITE_URL.rstrip("/") + href
                    links.append(href)
    except Exception as exc:
        logger.warning("Phase 1: Error extracting item links: %s", exc)

    if not links:
        try:
            link_elements = page.query_selector_all(ITEM_LINK_SELECTOR)
            for link_el in link_elements:
                href = link_el.get_attribute("href") or ""
                if href:
                    if href.startswith("/"):
                        href = SITE_URL.rstrip("/") + href
                    links.append(href)
        except Exception as exc:
            logger.warning("Phase 1: Fallback link extraction failed: %s", exc)

    return links


def _get_next_page_url(page, next_page_num: int) -> Optional[str]:
    """Determine the URL for the next page of results."""
    if PAGINATION_TYPE == "next_button":
        try:
            btn = page.query_selector(NEXT_BUTTON_SELECTOR)
            if btn:
                href = btn.get_attribute("href") or ""
                if href:
                    if href.startswith("/"):
                        href = SITE_URL.rstrip("/") + href
                    return href
                # SPA-style: no href, click the element and return the new URL
                try:
                    btn.click()
                    page.wait_for_load_state("networkidle")
                    time.sleep(2)
                    new_url = page.url
                    if new_url:
                        return new_url
                except Exception:
                    pass
        except Exception:
            pass
        return None
    elif PAGINATION_TYPE == "page_param":
        current_url = page.url
        separator = "&" if "?" in current_url else "?"
        return f"{current_url}{separator}{PAGE_PARAM_NAME}={next_page_num}"
    return None


# ═══════════════════════════════════════════════════════════════════════════════
# PHASE 2: ITEM EXTRACTION
# ═══════════════════════════════════════════════════════════════════════════════


def _extract_item_data(page, url: str, src_url: str) -> dict:
    """Phase 2: Extract structured data from a single item page.

    Customize this function based on content type and field selectors.
    """
    try:
        page.goto(url, timeout=PAGE_LOAD_TIMEOUT)
        page.wait_for_load_state("networkidle")
        time.sleep(1)
    except Exception as exc:
        logger.error("Phase 2: Failed to load %s: %s", url[:80], exc)
        return _error_item(url, src_url, str(exc))

    item: dict = {
        "url": url,
        "src_url": src_url,
        "status_code": page.url and 200 or 0,
        "scraped_at": datetime.now(timezone.utc).isoformat(),
        "remarks": "",
    }

    try:
        json_ld_data = page.evaluate(
            "() => { "
            "  const scripts = document.querySelectorAll('script[type=\"application/ld+json\"]'); "
            "  return Array.from(scripts).map(s => { try { return JSON.parse(s.textContent); } catch(e) { return null; } }).filter(Boolean); "
            "}"
        )

        for block in json_ld_data:
            block_type = block.get("@type", "")
            if CONTENT_TYPE == "product" and block_type in ("Product",):
                item["title"] = block.get("name", "")
                offers = block.get("offers", {})
                if isinstance(offers, dict):
                    price = offers.get("price", "")
                    currency = offers.get("priceCurrency", CURRENCY)
                    item["price"] = f"{currency}{price}" if price else ""
                    item["availability"] = "In Stock"
                    avail = offers.get("availability", "")
                    if "OutOfStock" in avail or "SoldOut" in avail:
                        item["availability"] = "Out of Stock"
                elif isinstance(offers, list):
                    for offer in offers:
                        if isinstance(offer, dict):
                            price = offer.get("price", "")
                            currency = offer.get("priceCurrency", CURRENCY)
                            item["price"] = f"{currency}{price}" if price else ""
                            break
                item["currency"] = block.get("offers", {}).get("priceCurrency", CURRENCY) if isinstance(block.get("offers"), dict) else CURRENCY
                item["description"] = block.get("description", "")
                item["images"] = block.get("image", [])
                if isinstance(item["images"], str):
                    item["images"] = [item["images"]]
                break

            elif CONTENT_TYPE == "article" and block_type in ("Article", "NewsArticle", "BlogPosting"):
                item["title"] = block.get("headline", block.get("name", ""))
                author = block.get("author", {})
                if isinstance(author, dict):
                    item["author"] = author.get("name", "")
                elif isinstance(author, list) and author:
                    item["author"] = author[0].get("name", "")
                item["publish_date"] = block.get("datePublished", "")
                item["content"] = block.get("articleBody", "")
                item["images"] = block.get("image", [])
                if isinstance(item["images"], str):
                    item["images"] = [item["images"]]
                break

            elif CONTENT_TYPE == "job_posting" and block_type == "JobPosting":
                item["title"] = block.get("title", "")
                org = block.get("hiringOrganization", {})
                item["company"] = org.get("name", "") if isinstance(org, dict) else ""
                loc = block.get("jobLocation", {})
                if isinstance(loc, dict):
                    addr = loc.get("address", {})
                    if isinstance(addr, dict):
                        item["location"] = addr.get("addressLocality", "")
                item["description"] = block.get("description", "")
                break

    except Exception as exc:
        logger.warning("Phase 2: JSON-LD extraction failed for %s: %s", url[:60], exc)

    if not item.get("title"):
        try:
            h1 = page.query_selector("h1")
            if h1:
                item["title"] = (h1.text_content() or "").strip()
        except Exception:
            pass

    return item


def _error_item(url: str, src_url: str, error: str) -> dict:
    return {
        "url": url,
        "src_url": src_url,
        "status_code": 0,
        "scraped_at": datetime.now(timezone.utc).isoformat(),
        "remarks": f"Error: {error[:200]}",
    }


# ═══════════════════════════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════════════════════════


def main():
    parser = argparse.ArgumentParser(description=f"{SITE_NAME} Navigation Scraper")
    parser.add_argument("--query", type=str, help="Search query for navigation mode")
    parser.add_argument("--category-url", type=str, help="Category URL to crawl")
    parser.add_argument("--listing-url", type=str, help="Listing page URL to paginate")
    parser.add_argument("--sample", action="store_true", help="Scrape first 5 items only")
    parser.add_argument("--limit", type=int, default=None, help="Max items to scrape")
    parser.add_argument("--no-proxy", action="store_true", help="Disable proxy")
    parser.add_argument("--headless", action="store_true", default=True, help="Headless mode")
    args = parser.parse_args()

    limit = 5 if args.sample else args.limit

    proxy_url = None
    if not args.no_proxy and PROXY_TIER != "none":
        proxy_url = build_proxy_url(PROXY_TIER)

    start_time = time.time()
    discovered_urls: list[str] = []

    with sync_playwright() as p:
        browser_args = []
        if proxy_url:
            browser_args.append(f"--proxy-server={proxy_url}")
        browser = p.chromium.launch(
            headless=args.headless,
            args=browser_args,
        )
        context = browser.new_context(
            viewport={"width": 1920, "height": 1080},
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        )
        page = context.new_page()

        # ── Phase 1: Discover URLs ───────────────────────────────────────
        if args.query:
            discovered_urls = _discover_urls_via_search(page, args.query, MAX_PAGES, limit)
            src_url_base = SEARCH_URL_PATTERN.replace("{query}", args.query)
        elif args.category_url:
            discovered_urls = _discover_urls_via_category(page, args.category_url, MAX_PAGES, limit)
            src_url_base = args.category_url
        elif args.listing_url:
            discovered_urls = _discover_urls_via_category(page, args.listing_url, MAX_PAGES, limit)
            src_url_base = args.listing_url
        else:
            logger.error("No --query, --category-url, or --listing-url provided")
            browser.close()
            sys.exit(1)

        if not discovered_urls:
            logger.warning("No item URLs discovered")
            browser.close()
            sys.exit(0)

        # ── Phase 2: Extract data from each URL ────────────────────────
        logger.info("Phase 2: Extracting data from %d items", len(discovered_urls))
        items: list[dict] = []
        total = len(discovered_urls)

        for i, url in enumerate(discovered_urls, 1):
            logger.info("Progress: [%d/%d] (%.1f%%", i, total, (i / total) * 100)
            logger.info("Scraping: %s", url[:100])

            try:
                item = _extract_item_data(page, url, src_url_base)
                items.append(item)
            except Exception as exc:
                logger.error("Failed to extract %s: %s", url[:80], exc)
                items.append(_error_item(url, src_url_base, str(exc)))

            if i < total:
                time.sleep(DELAY_BETWEEN_REQUESTS)

        browser.close()

    # ── Write output ────────────────────────────────────────────────────
    output = {
        "site": {
            "name": SITE_NAME,
            "url": SITE_URL,
            "platform": PLATFORM,
            "scraping_method": "playwright_navigation",
            "scraped_at": datetime.now(timezone.utc).isoformat(),
        },
        OUTPUT_KEY: items,
        "metadata": {
            "scraping_duration_seconds": round(time.time() - start_time, 1),
            "discovered_urls": len(discovered_urls),
            "extracted_items": len(items),
        },
    }

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d_%H%M%S")
    output_filename = os.path.join(SCRIPT_DIR, f"output_{timestamp}.json")

    with open(output_filename, "w", encoding="utf-8") as f:
        json.dump(output, f, indent=2, ensure_ascii=False, default=str)

    logger.info(
        "Done: %d/%d items in %.1fs → %s",
        len([i for i in items if i.get("title")]),
        total,
        time.time() - start_time,
        output_filename,
    )


if __name__ == "__main__":
    main()
