#!/usr/bin/env python3
"""
Playwright Browser Scraper Template

Uses Playwright for JavaScript-rendered ecommerce sites.
Generated by Code Writer Agent for Universal Ecommerce Scraper.

The scraper reads input_urls.json from its own directory by default.
Can also accept URLs via --urls or --input flags.

Usage:
    python3 scraper.py                    # reads input_urls.json from same folder
    python3 scraper.py --input urls.json  # explicit input file
    python3 scraper.py --urls url1 url2     # URLs as CLI arguments
    python3 scraper.py --headless          # headless mode
"""

import argparse
import json
import logging
import os
import re
import sys
import time
from datetime import datetime, timezone
from html import unescape
from typing import Optional

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from src.proxy import ProxyConfig, build_proxy_url

# ═══════════════════════════════════════════════════════════════════════════════
# CONFIGURATION - Update these values
# ═══════════════════════════════════════════════════════════════════════════════

SITE_NAME = "{SITE_NAME}"
SITE_URL = "{SITE_URL}"
PLATFORM = "{PLATFORM}"
SCRAPING_METHOD = "playwright"
SITE_SLUG = "{SITE_SLUG}"

PRODUCT_LISTING_URL = "{PRODUCT_LISTING_URL}"
SRC_URL = "{PRODUCT_LISTING_URL}"
DELAY_BETWEEN_REQUESTS = {DELAY_BETWEEN_REQUESTS}
PAGE_LOAD_TIMEOUT = 30000

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
TIMESTAMP = datetime.now(timezone.utc).strftime("%Y-%m-%d_%H%M%S")
OUTPUT_FILE = os.path.join(SCRIPT_DIR, f"output_{TIMESTAMP}.json")
INPUT_FILE = os.path.join(SCRIPT_DIR, "input_urls.json")
LOG_FILE = os.path.join(os.path.dirname(SCRIPT_DIR), "logs", f"{SITE_SLUG}.log")

# ═══════════════════════════════════════════════════════════════════════════════
# LOGGING
# ═══════════════════════════════════════════════════════════════════════════════

os.makedirs(os.path.dirname(LOG_FILE), exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[
        logging.FileHandler(LOG_FILE),
        logging.StreamHandler(),
    ],
)
logger = logging.getLogger(__name__)

proxy_config = ProxyConfig.get_instance()


# ═══════════════════════════════════════════════════════════════════════════════
# HELPERS
# ═══════════════════════════════════════════════════════════════════════════════

def clean_html(html_str: str) -> str:
    if not html_str:
        return ""
    text = re.sub(r"<[^>]+>", " ", html_str)
    text = unescape(text)
    return re.sub(r"\s+", " ", text).strip()


def get_browser(pw, headless=True, proxy=None):
    """Connect to browser — remote CDP if available, local launch otherwise."""
    cdp_endpoint = os.environ.get("BROWSER_CDP_ENDPOINT", "")
    if cdp_endpoint:
        logger.info(f"Connecting to remote browser via CDP: {cdp_endpoint}")
        return pw.chromium.connect_over_cdp(cdp_endpoint)

    launch_args = {"headless": headless, "args": ["--no-sandbox", "--disable-dev-shm-usage",
                "--disable-blink-features=AutomationControlled", "--disable-infobars",
                "--no-first-run"]}
    if proxy:
        launch_args["proxy"] = {"server": proxy}
    return pw.chromium.launch(**launch_args)


# ═══════════════════════════════════════════════════════════════════════════════
# EXTRACTION JS - CUSTOMIZE selectors below
# ═══════════════════════════════════════════════════════════════════════════════

EXTRACT_PRODUCT_JS = """
(src_url) => {
    const product = {
        title: '',
        price: '',
        availability: '',
        original_price: '',
        currency: '',
        url: window.location.href,
        src_url: src_url || '',
        location: '',
        remarks: ''
    };

    // JSON-LD
    const jsonldScripts = document.querySelectorAll('script[type="application/ld+json"]');
    let jsonld = null;
    for (const script of jsonldScripts) {
        try {
            const data = JSON.parse(script.textContent);
            if (data['@type'] === 'Product') { jsonld = data; break; }
            if (Array.isArray(data)) {
                for (const item of data) {
                    if (item['@type'] === 'Product') { jsonld = item; break; }
                }
            }
            if (jsonld) break;
        } catch(e) {}
    }

    // Title
    product.title = jsonld?.name ||
        document.querySelector('{TITLE_SELECTOR}')?.textContent?.trim() || '';

    // Price
    if (jsonld?.offers) {
        const offers = Array.isArray(jsonld.offers) ? jsonld.offers[0] : jsonld.offers;
        product.price = offers?.price || '';
        const highPrice = offers?.highPrice || '';
        if (highPrice && parseFloat(highPrice) > parseFloat(product.price || 0)) {
            product.original_price = highPrice;
        }
        product.currency = offers?.priceCurrency || 'USD';
        const avail = offers?.availability || '';
        product.availability = avail.includes('InStock') ? 'In Stock' : 'Out of Stock';
    } else {
        const priceEl = document.querySelector('{PRICE_SELECTOR}');
        product.price = priceEl?.textContent?.trim() || '';
        const origEl = document.querySelector('{ORIGINAL_PRICE_SELECTOR}');
        product.original_price = origEl?.textContent?.trim() || '';
        const stockEl = document.querySelector('{AVAILABILITY_SELECTOR}');
        if (stockEl) {
            const t = stockEl.textContent.toLowerCase();
            product.availability = t.includes('in stock') ? 'In Stock' : 'Out of Stock';
        }
    }

    return product;
}
"""

EXTRACT_PRODUCT_URLS_JS = """
() => {
    const links = document.querySelectorAll('{PRODUCT_LINK_SELECTOR}');
    const unique = new Set();
    links.forEach(a => {
        let href = a.getAttribute('href');
        if (href) {
            if (!href.startsWith('http')) {
                href = window.location.origin + href;
            }
            unique.add(href);
        }
    });
    return Array.from(unique);
}
"""


def scrape_product(page, url: str, src_url: str, index: int) -> dict:
    page.goto(url, wait_until="networkidle", timeout=PAGE_LOAD_TIMEOUT)
    page.wait_for_timeout(2000)

    data = page.evaluate(EXTRACT_PRODUCT_JS, src_url)

    return {
        "id": index,
        "title": data.get("title", ""),
        "price": data.get("price", ""),
        "availability": data.get("availability", ""),
        "original_price": data.get("original_price", ""),
        "currency": data.get("currency", ""),
        "url": url,
        "src_url": src_url,
        "location": data.get("location", ""),
        "status_code": 200,
        "scraped_at": datetime.now(timezone.utc).isoformat(),
        "remarks": data.get("remarks", ""),
    }


def discover_product_urls(page) -> list[str]:
    page.goto(PRODUCT_LISTING_URL, wait_until="networkidle", timeout=PAGE_LOAD_TIMEOUT)
    page.wait_for_timeout(3000)
    return page.evaluate(EXTRACT_PRODUCT_URLS_JS) or []


# ═══════════════════════════════════════════════════════════════════════════════
# INPUT HANDLING
# ═══════════════════════════════════════════════════════════════════════════════

def load_urls_from_file(filepath: str) -> list[str]:
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data.get("urls", [])


def save_urls_to_file(filepath: str, urls: list[str]) -> None:
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump({"urls": urls}, f, indent=2, ensure_ascii=False)
    logger.info(f"Saved {len(urls)} URLs to {filepath}")


# ═══════════════════════════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(description=f"Playwright scraper for {SITE_NAME}")
    parser.add_argument("--sample", action="store_true", help="Scrape only 5 products")
    parser.add_argument("--limit", type=int, default=None, help="Max products to scrape")
    parser.add_argument("--input", type=str, default=None, help="Path to input URLs JSON file")
    parser.add_argument("--urls", nargs="+", default=None, help="Product URLs as arguments")
    parser.add_argument("--headless", action="store_true", help="Run in headless mode")
    args = parser.parse_args()

    from playwright.sync_api import sync_playwright

    start_time = time.time()

    logger.info("=" * 80)
    logger.info(f"Starting Playwright scraper for {SITE_NAME}")
    logger.info(f"Site: {SITE_URL}")
    logger.info(f"Output: {OUTPUT_FILE}")
    logger.info("=" * 80)

    product_urls = []

    if args.urls:
        product_urls = args.urls
    elif args.input:
        product_urls = load_urls_from_file(args.input)
    elif os.path.exists(INPUT_FILE):
        product_urls = load_urls_from_file(INPUT_FILE)

    if args.sample:
        product_urls = product_urls[:5]
    if args.limit:
        product_urls = product_urls[: args.limit]

    if not product_urls:
        logger.info("No input URLs found. Discovering products via browser...")
        with sync_playwright() as p:
            browser = get_browser(p)
            context = browser.new_context(
                user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
                viewport={"width": 1920, "height": 1080},
            )
            page = context.new_page()
            product_urls = discover_product_urls(page)
            browser.close()
        save_urls_to_file(INPUT_FILE, product_urls)

    logger.info(f"Total products to scrape: {len(product_urls)}")

    results = []
    failed = 0

    proxy_server = build_proxy_url("datacenter", proxy_config) or None
    launch_args = {
        "headless": args.headless,
        "args": [
            "--disable-blink-features=AutomationControlled",
            "--disable-infobars",
            "--no-first-run",
        ],
    }
    if proxy_server:
        launch_args["proxy"] = {"server": proxy_server}

    with sync_playwright() as p:
        browser = get_browser(p, headless=args.headless, proxy=proxy_server)
        context = browser.new_context(
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
            viewport={"width": 1920, "height": 1080},
        )
        page = context.new_page()

        logger.info("Warming up session...")
        page.goto(SITE_URL, wait_until="networkidle", timeout=PAGE_LOAD_TIMEOUT)
        page.wait_for_timeout(5000)

        for i, url in enumerate(product_urls):
            try:
                product = scrape_product(page, url, SRC_URL, i + 1)
                if product.get("title"):
                    results.append(product)
                else:
                    logger.warning(f"No title extracted from: {url}")
                    failed += 1
            except Exception as e:
                logger.error(f"Error processing {url}: {e}")
                failed += 1

            if (i + 1) % 25 == 0:
                percent = ((i + 1) / len(product_urls)) * 100
                logger.info(f"Progress: [{i + 1}/{len(product_urls)}] ({percent:.1f}%)")

            time.sleep(DELAY_BETWEEN_REQUESTS)

        browser.close()

    output = {
        "site": {
            "name": SITE_NAME,
            "url": SITE_URL,
            "platform": PLATFORM,
            "scraping_method": SCRAPING_METHOD,
            "scraped_at": datetime.now(timezone.utc).isoformat(),
        },
        "products": results,
        "metadata": {
            "scraping_duration_seconds": round(time.time() - start_time, 2),
            "failed_products": failed,
            "rate_limit_delay": DELAY_BETWEEN_REQUESTS,
        },
    }

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(output, f, indent=2, ensure_ascii=False)

    logger.info("=" * 80)
    logger.info("EXTRACTION COMPLETE")
    logger.info(f"Total: {len(results)}, Failed: {failed}")
    logger.info(f"Duration: {round(time.time() - start_time, 2)}s")
    logger.info(f"Output: {OUTPUT_FILE}")
    logger.info("=" * 80)


if __name__ == "__main__":
    main()
