#!/usr/bin/env python3
"""
Playwright Browser Scraper Template

Uses Playwright for JavaScript-rendered ecommerce sites.
Generated by Code Writer Agent for Universal Ecommerce Scraper.

The scraper reads input_urls.json from its own directory by default.
Can also accept URLs via --urls or --input flags.

Usage:
    python3 scraper.py                    # reads input_urls.json from same folder
    python3 scraper.py --input urls.json  # explicit input file
    python3 scraper.py --urls url1 url2     # URLs as CLI arguments
    python3 scraper.py --headless          # headless mode
"""

import argparse
import json
import logging
import os
import re
import sys
import time
from datetime import datetime, timezone
from html import unescape
from typing import Optional

from playwright.sync_api import sync_playwright

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from src.proxy import ProxyConfig, build_proxy_url
from src.geo import detect_country
from src.discovery import discover_item_urls, config_for_load_more, config_from_dict

# ═══════════════════════════════════════════════════════════════════════════════
# CONFIGURATION - Update these values
# ═══════════════════════════════════════════════════════════════════════════════

SITE_NAME = "{SITE_NAME}"
SITE_URL = "{SITE_URL}"
PLATFORM = "{PLATFORM}"
SCRAPING_METHOD = "playwright"
# OUTPUT_KEY consumed by _patch_scraper_output_filter's injected block (and the
# output filter) — without it, the patcher's output.get(OUTPUT_KEY, []) is a
# silent NameError-caught no-op on every playwright-strategy scraper.
OUTPUT_KEY = "products"
SITE_SLUG = "{SITE_SLUG}"

PRODUCT_LISTING_URL = "{PRODUCT_LISTING_URL}"
SRC_URL = "{PRODUCT_LISTING_URL}"
DELAY_BETWEEN_REQUESTS = {DELAY_BETWEEN_REQUESTS}
PAGE_LOAD_TIMEOUT = 30000

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
TIMESTAMP = datetime.now(timezone.utc).strftime("%Y-%m-%d_%H%M%S")
OUTPUT_FILE = os.path.join(SCRIPT_DIR, f"output_{TIMESTAMP}.json")
INPUT_FILE = os.path.join(SCRIPT_DIR, "input_urls.json")
LOG_FILE = os.path.join(os.path.dirname(SCRIPT_DIR), "logs", f"{SITE_SLUG}.log")

# ═══════════════════════════════════════════════════════════════════════════════
# LOGGING
# ═══════════════════════════════════════════════════════════════════════════════

os.makedirs(os.path.dirname(LOG_FILE), exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[
        logging.FileHandler(LOG_FILE),
        logging.StreamHandler(),
    ],
)
logger = logging.getLogger(__name__)

proxy_config = ProxyConfig.get_instance()


# ═══════════════════════════════════════════════════════════════════════════════
# HELPERS
# ═══════════════════════════════════════════════════════════════════════════════

def clean_html(html_str: str) -> str:
    if not html_str:
        return ""
    text = re.sub(r"<[^>]+>", " ", html_str)
    text = unescape(text)
    return re.sub(r"\s+", " ", text).strip()


def get_browser(pw, headless=True, proxy=None):
    """Connect to browser — remote CDP if available, local launch otherwise.

    NOTE: stealth is handled transparently by the browser_service
    cloak_stealth_patch (.pth) — when STEALTH_BROWSER=cloak is set for anti-bot
    sites, the launch() below drives CloakBrowser's stealth Chromium binary. Do
    NOT call cloakbrowser.launch() here (it would start a second Playwright and
    conflict with the caller's sync_playwright context).
    """
    cdp_endpoint = os.environ.get("BROWSER_CDP_ENDPOINT", "")
    if cdp_endpoint:
        logger.info(f"Connecting to remote browser via CDP: {cdp_endpoint}")
        return pw.chromium.connect_over_cdp(cdp_endpoint)

    launch_args = {"headless": headless, "args": ["--no-sandbox", "--disable-dev-shm-usage",
                "--disable-blink-features=AutomationControlled", "--disable-infobars",
                "--no-first-run"]}
    if proxy:
        launch_args["proxy"] = {"server": proxy}
    return pw.chromium.launch(**launch_args)


# ═══════════════════════════════════════════════════════════════════════════════
# EXTRACTION JS - CUSTOMIZE selectors below
# ═══════════════════════════════════════════════════════════════════════════════

EXTRACT_PRODUCT_JS = """
(src_url) => {
    const product = {
        title: '',
        price: '',
        availability: '',
        original_price: '',
        currency: '',
        url: window.location.href,
        src_url: src_url || '',
        location: '',
        remarks: ''
    };

    // JSON-LD
    const jsonldScripts = document.querySelectorAll('script[type="application/ld+json"]');
    let jsonld = null;
    for (const script of jsonldScripts) {
        try {
            const data = JSON.parse(script.textContent);
            // Content-type-agnostic: accept any typed JSON-LD entity with a name/title
            // (Product, Person, JobPosting, Article, etc.) — not just 'Product'.
            if (data['@type'] && (data.name || data.title)) { jsonld = data; break; }
            if (Array.isArray(data)) {
                for (const item of data) {
                    if (item['@type'] === 'Product') { jsonld = item; break; }
                }
            }
            if (jsonld) break;
        } catch(e) {}
    }

    // Title
    product.title = jsonld?.name ||
        document.querySelector('{TITLE_SELECTOR}')?.textContent?.trim() || '';

    // Price
    if (jsonld?.offers) {
        const offers = Array.isArray(jsonld.offers) ? jsonld.offers[0] : jsonld.offers;
        product.price = offers?.price || '';
        const highPrice = offers?.highPrice || '';
        if (highPrice && parseFloat(highPrice) > parseFloat(product.price || 0)) {
            product.original_price = highPrice;
        }
        product.currency = offers?.priceCurrency || 'USD';
        const avail = offers?.availability || '';
        product.availability = avail.includes('InStock') ? 'In Stock' : 'Out of Stock';
    } else {
        const priceEl = document.querySelector('{PRICE_SELECTOR}');
        product.price = priceEl?.textContent?.trim() || '';
        const origEl = document.querySelector('{ORIGINAL_PRICE_SELECTOR}');
        product.original_price = origEl?.textContent?.trim() || '';
        const stockEl = document.querySelector('{AVAILABILITY_SELECTOR}');
        if (stockEl) {
            const t = stockEl.textContent.toLowerCase();
            product.availability = t.includes('in stock') ? 'In Stock' : 'Out of Stock';
        }
    }

    return product;
}
"""

EXTRACT_PRODUCT_URLS_JS = """
() => {
    const links = document.querySelectorAll('{PRODUCT_LINK_SELECTOR}');
    const unique = new Set();
    links.forEach(a => {
        let href = a.getAttribute('href');
        if (href) {
            if (!href.startsWith('http')) {
                href = window.location.origin + href;
            }
            unique.add(href);
        }
    });
    return Array.from(unique);
}
"""


def scrape_product(page, url: str, src_url: str, index: int) -> dict:
    page.goto(url, wait_until="networkidle", timeout=PAGE_LOAD_TIMEOUT)
    page.wait_for_timeout(2000)

    data = page.evaluate(EXTRACT_PRODUCT_JS, src_url)

    return {
        "id": index,
        "title": data.get("title", ""),
        "price": data.get("price", ""),
        "availability": data.get("availability", ""),
        "original_price": data.get("original_price", ""),
        "currency": data.get("currency", ""),
        "url": url,
        "src_url": src_url,
        "location": data.get("location", ""),
        "status_code": 200,
        "scraped_at": datetime.now(timezone.utc).isoformat(),
        "remarks": data.get("remarks", ""),
    }


# SHARED DISCOVERY: pagination is imported from src/discovery.py, NOT defined
# inline. This prevents code_writer from rewriting/breaking the pagination loop
# (the root cause of the 20+ run whack-a-mole: code_writer treated the loop as
# editable prose and altered selectors, thresholds, and control flow every run).
# code_writer copies what it SEES — an import + call — so pagination stays
# deterministic. Only the extract_urls callback (EXTRACT_PRODUCT_URLS_JS) is
# site-specific and remains in this file for code_writer to adapt.
MAX_DISCOVER_PAGES = 200

# Last Phase-1 outcome, for the output's metadata.discovery_coverage block
# (discovery-coverage-gate contract §1). Module-level so BOTH discovery call
# sites in main() feed the same block without changing this function's
# list[str] contract. Skipped-state defaults are what a run that never
# discovered reports (url_list mode / checkpoint resume).
LAST_DISCOVERY: dict = {
    "ran_phase1": False,
    "skipped_reason": None,
    "stop_reason": "skipped",
    "discovered_urls": 0,
    "pages_visited": 0,
    "max_pages_hit": False,
}


def discover_product_urls(page) -> list[str]:
    def _extract(p):
        try:
            return p.evaluate(EXTRACT_PRODUCT_URLS_JS) or []
        except Exception:
            return []

    # Discovery config: read from sibling discovery_config.json (written by
    # scraper_analyzer → _invoke_code_writer) if present, else default to
    # load_more. This makes the pagination type DETERMINISTIC — driven by the
    # navigator's observation, not code_writer's guess. Falls back to
    # config_for_load_more when no config file exists (backward compat).
    import json as _dj
    _cfg = None
    _cfg_path = os.path.join(SCRIPT_DIR, "discovery_config.json")
    try:
        if os.path.isfile(_cfg_path):
            with open(_cfg_path) as _cf:
                _cfg = config_from_dict(_dj.load(_cf))
    except Exception:
        pass
    if _cfg is None:
        _cfg = config_for_load_more(max_pages=MAX_DISCOVER_PAGES)
    else:
        _cfg.max_pages = _cfg.max_pages or MAX_DISCOVER_PAGES

    result = discover_item_urls(page, PRODUCT_LISTING_URL, _extract, _cfg)
    logger.info(
        "discovery: stop_reason=%s pages=%d urls=%d param=%s strategies=%s",
        result.stop_reason, result.pages_visited, len(result.urls),
        result.param_used, _cfg.strategies,
    )
    LAST_DISCOVERY.update({
        "ran_phase1": True,
        "skipped_reason": None,
        "stop_reason": str(result.stop_reason),
        "discovered_urls": len(result.urls),
        "pages_visited": result.pages_visited,
        "max_pages_hit": result.max_pages_hit,
    })
    return result.urls


# ═══════════════════════════════════════════════════════════════════════════════
# INPUT HANDLING
# ═══════════════════════════════════════════════════════════════════════════════

def load_urls_from_file(filepath: str) -> list[str]:
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data.get("urls", [])


def save_urls_to_file(filepath: str, urls: list[str]) -> None:
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump({"urls": urls}, f, indent=2, ensure_ascii=False)
    logger.info(f"Saved {len(urls)} URLs to {filepath}")


# ═══════════════════════════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════════════════════════

# ── CLI CONTRACT — keep every line below when adapting ───────────────────────
# The pipeline launches this scraper with EXACTLY these names. A flag missing
# from the argparse below is STRIPPED at launch and discovery silently falls
# back to the seed file (input_urls.json). Same for the SCRAPER_LISTING_URL
# env read in main(). ADD flags if you need them; NEVER remove or rename:
#   --fresh-discovery  always (execution)     --listing-url  navigation/list_page
#   --query            search_term            --input/--sample/--limit  testing
#   --discover-only    Phase-1 probe          (+ SCRAPER_LISTING_URL env read)
# Source of truth: webapp/agents/constants.py
# ──────────────────────────────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser(description=f"Playwright scraper for {SITE_NAME}")
    parser.add_argument("--sample", action="store_true", help="Scrape only 5 products")
    parser.add_argument("--limit", type=int, default=None, help="Max products to scrape")
    parser.add_argument("--input", type=str, default=None, help="Path to input URLs JSON file")
    parser.add_argument("--urls", nargs="+", default=None, help="Product URLs as arguments")
    parser.add_argument("--headless", action="store_true", help="Run in headless mode")
    parser.add_argument("--listing-url", type=str, default=None,
                        help="Listing page URL for Phase 1 discovery (pagination)")
    parser.add_argument("--fresh-discovery", action="store_true",
                        help="Force Phase 1 discovery even if input_urls.json exists")
    parser.add_argument("--discover-only", action="store_true",
                        help="Run Phase 1 discovery only (capped), skip Phase 2 extraction")
    args = parser.parse_args()

    start_time = time.time()

    logger.info("=" * 80)
    logger.info(f"Starting Playwright scraper for {SITE_NAME}")
    logger.info(f"Site: {SITE_URL}")
    logger.info(f"Output: {OUTPUT_FILE}")
    logger.info("=" * 80)

    product_urls = []

    # DETERMINISTIC DISCOVERY GATE (env-var driven, bypasses argparse/codegen):
    # run_execution sets SCRAPER_LISTING_URL=<url> for nav/list_page/search_term
    # jobs. When set, ALWAYS run Phase 1 discovery from that URL — regardless of
    # CLI flags (which code_writer may or may not declare) or input_urls.json
    # (which always exists with seed URLs and suppresses discovery in the old
    # `if not product_urls:` gate). This makes discovery DETERMINISTIC — not
    # dependent on code_writer faithfully copying --listing-url/--fresh-discovery
    # into argparse (it doesn't — verified across lw.com + uindex runs).
    _env_listing = os.environ.get("SCRAPER_LISTING_URL", "").strip()
    _env_force = os.environ.get("SCRAPER_FORCE_DISCOVERY", "").strip().lower() in ("1", "true", "yes")
    if _env_listing or _env_force or args.fresh_discovery or args.listing_url:
        global PRODUCT_LISTING_URL
        _listing = _env_listing or (args.listing_url if args.listing_url else "") or PRODUCT_LISTING_URL
        logger.info("Phase 1 discovery triggered (env/flag). Listing URL: %s", _listing)
        PRODUCT_LISTING_URL = _listing
        with sync_playwright() as p:
            browser = get_browser(p)
            context = browser.new_context(
                user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
                viewport={"width": 1920, "height": 1080},
            )
            page = context.new_page()
            product_urls = discover_product_urls(page)
            browser.close()
        if product_urls:
            save_urls_to_file(INPUT_FILE, product_urls)
    elif args.urls:
        product_urls = args.urls
        LAST_DISCOVERY["skipped_reason"] = "url_list_mode"
    elif args.input:
        product_urls = load_urls_from_file(args.input)
        LAST_DISCOVERY["skipped_reason"] = "url_list_mode"
    elif os.path.exists(INPUT_FILE):
        product_urls = load_urls_from_file(INPUT_FILE)
        # input_urls.json is this template's persisted discovery output; reusing
        # it means Phase 1 did not run this invocation.
        LAST_DISCOVERY["skipped_reason"] = "checkpoint_loaded"

    if not product_urls:
        logger.info("No input URLs found. Discovering products via browser...")
        with sync_playwright() as p:
            browser = get_browser(p)
            context = browser.new_context(
                user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
                viewport={"width": 1920, "height": 1080},
            )
            page = context.new_page()
            product_urls = discover_product_urls(page)
            browser.close()
        save_urls_to_file(INPUT_FILE, product_urls)

    # --discover-only: run a CAPPED Phase 1 discovery (5 pages max) for testing,
    # then exit without Phase 2. This lets _probe_phase1_discovery verify that
    # discovery actually works (finds >0 URLs, paginates past page 1) without
    # needing the full ~800s for 200 pages. The probe has a 180s budget — plenty
    # for 5 pages × ~4s = ~20s.
    # NOTE: opens its OWN browser page — the discovery gate above may have
    # already closed its browser (browser.close() at the end of the gate's
    # with-block), and a `page` handle from a closed browser makes every
    # navigation fail silently ("target closed" is swallowed by
    # _discovery_goto) → always found=0 / stop_reason=navigate_error with
    # exit 0 (the pre-fix bug: two rmwilliams probe artifacts proved it).
    if args.discover_only:
        _dcfg = None
        try:
            import json as _dj2
            _dcfg_path2 = os.path.join(SCRIPT_DIR, "discovery_config.json")
            if os.path.isfile(_dcfg_path2):
                with open(_dcfg_path2) as _cf2:
                    _dcfg = config_from_dict(_dj2.load(_cf2))
        except Exception:
            pass
        if _dcfg is None:
            _dcfg = config_for_load_more(max_pages=5)
        else:
            _dcfg.max_pages = 5  # cap for testing

        def _extract_probe(p):
            try:
                return p.evaluate(EXTRACT_PRODUCT_URLS_JS) or []
            except Exception:
                return []

        with sync_playwright() as p:
            browser = get_browser(p)
            context = browser.new_context(
                user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
                viewport={"width": 1920, "height": 1080},
            )
            probe_page = context.new_page()
            _probe_result = discover_item_urls(probe_page, PRODUCT_LISTING_URL, _extract_probe, _dcfg)
            browser.close()
        logger.info(
            "discover-only: stop_reason=%s pages=%d urls=%d",
            _probe_result.stop_reason, _probe_result.pages_visited, len(_probe_result.urls),
        )
        # discovery_coverage — contract §1, same 9 keys the full run emits below
        # (plus the pages_visited diagnostic), so a probe output and an
        # execution output are read by the same code path.
        _probe_coverage = {
            "ran_phase1": True,
            "skipped_reason": None,
            "stop_reason": str(_probe_result.stop_reason),
            "found": 0,  # Phase 2 skipped by design
            "discovered_urls": len(_probe_result.urls),
            "expected_total": None,
            "dimensions_iterated": 0,
            "dimensions_total": 0,
            "max_pages_hit": _probe_result.max_pages_hit,
            "pages_visited": _probe_result.pages_visited,
        }
        output = {
            "site": {
                "name": SITE_NAME,
                "url": SITE_URL,
                "platform": PLATFORM,
                "scraping_method": SCRAPING_METHOD,
                "scraped_at": datetime.now(timezone.utc).isoformat(),
            },
            "products": [],
            "metadata": {
                "total_discovered": len(_probe_result.urls),
                "discovery_coverage": _probe_coverage,
            },
        }
        with open(OUTPUT_FILE, "w") as _of:
            json.dump(output, _of, indent=2)
        logger.info("discover-only: wrote %d discovered URLs to %s", len(_probe_result.urls), OUTPUT_FILE)
        return

    if args.sample:
        product_urls = product_urls[:20]
    if args.limit:
        product_urls = product_urls[: args.limit]

    logger.info(f"Total products to scrape: {len(product_urls)}")

    results = []
    failed = 0

    proxy_server = build_proxy_url("datacenter", proxy_config, country=detect_country(SITE_URL)) or None
    launch_args = {
        "headless": args.headless,
        "args": [
            "--disable-blink-features=AutomationControlled",
            "--disable-infobars",
            "--no-first-run",
        ],
    }
    if proxy_server:
        launch_args["proxy"] = {"server": proxy_server}

    with sync_playwright() as p:
        browser = get_browser(p, headless=args.headless, proxy=proxy_server)
        context = browser.new_context(
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
            viewport={"width": 1920, "height": 1080},
        )
        page = context.new_page()

        logger.info("Warming up session...")
        page.goto(SITE_URL, wait_until="networkidle", timeout=PAGE_LOAD_TIMEOUT)
        page.wait_for_timeout(5000)

        for i, url in enumerate(product_urls):
            try:
                product = scrape_product(page, url, SRC_URL, i + 1)
                # Content-type-agnostic validity: accept if ANY substantive field
                # (not just 'title') is present — rescues Person/job/article items.
                _BK = {"url", "src_url", "scraped_at", "status_code", "remarks", "id", "title"}
                if any(v for k, v in product.items() if k not in _BK):
                    results.append(product)
                else:
                    logger.warning(f"No substantive data extracted from: {url}")
                    failed += 1
            except Exception as e:
                logger.error(f"Error processing {url}: {e}")
                failed += 1

            if (i + 1) % 25 == 0:
                percent = ((i + 1) / len(product_urls)) * 100
                logger.info(f"Progress: [{i + 1}/{len(product_urls)}] ({percent:.1f}%)")

            time.sleep(DELAY_BETWEEN_REQUESTS)

        browser.close()

    # discovery_coverage — discovery-coverage-gate contract §1. Always emitted
    # (even when Phase 1 was skipped) so the gate reads a uniform schema.
    if LAST_DISCOVERY.get("ran_phase1"):
        _stop_reason = LAST_DISCOVERY.get("stop_reason", "no_next_link")
    else:
        _stop_reason = "skipped"
    discovery_coverage = {
        "ran_phase1": LAST_DISCOVERY.get("ran_phase1", False),
        "skipped_reason": LAST_DISCOVERY.get("skipped_reason"),
        "stop_reason": _stop_reason,
        "found": len(results),
        "discovered_urls": LAST_DISCOVERY.get("discovered_urls", 0),
        "expected_total": None,
        "dimensions_iterated": 0,
        "dimensions_total": 0,
        "max_pages_hit": LAST_DISCOVERY.get("max_pages_hit", False),
        # Extra diagnostic (not part of §1; no consumer reads it today).
        "pages_visited": LAST_DISCOVERY.get("pages_visited", 0),
    }

    output = {
        "site": {
            "name": SITE_NAME,
            "url": SITE_URL,
            "platform": PLATFORM,
            "scraping_method": SCRAPING_METHOD,
            "scraped_at": datetime.now(timezone.utc).isoformat(),
        },
        "products": results,
        "metadata": {
            "scraping_duration_seconds": round(time.time() - start_time, 2),
            "failed_products": failed,
            "rate_limit_delay": DELAY_BETWEEN_REQUESTS,
            "discovered_urls": LAST_DISCOVERY.get("discovered_urls", 0),
            "discovery_coverage": discovery_coverage,
        },
    }

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(output, f, indent=2, ensure_ascii=False)

    logger.info("=" * 80)
    logger.info("EXTRACTION COMPLETE")
    logger.info(f"Total: {len(results)}, Failed: {failed}")
    logger.info(f"Duration: {round(time.time() - start_time, 2)}s")
    logger.info(f"Output: {OUTPUT_FILE}")
    logger.info("=" * 80)


if __name__ == "__main__":
    main()
