#!/usr/bin/env python3
"""
HTTP Requests Scraper Template

Uses requests + BeautifulSoup for static HTML ecommerce sites.
Generated by Code Writer Agent for Universal Ecommerce Scraper.

The scraper reads input_urls.json from its own directory by default.
Can also accept URLs via --urls or --input flags.

Usage:
    python3 scraper.py                    # reads input_urls.json from same folder
    python3 scraper.py --input urls.json  # explicit input file
    python3 scraper.py --urls url1 url2     # URLs as CLI arguments
"""

import argparse
import json
import logging
import os
import re
import sys
import time
from datetime import datetime, timezone
from html import unescape
from typing import Optional
from urllib.parse import urljoin

import requests
from bs4 import BeautifulSoup

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from src.proxy import ProxyConfig, should_warn_residential, warn_residential_usage

# ═══════════════════════════════════════════════════════════════════════════════
# CONFIGURATION - Update these values
# ═══════════════════════════════════════════════════════════════════════════════

SITE_NAME = "{SITE_NAME}"
SITE_URL = "{SITE_URL}"
PLATFORM = "{PLATFORM}"
SCRAPING_METHOD = "http_requests"
SITE_SLUG = "{SITE_SLUG}"

PRODUCT_LISTING_URL = "{PRODUCT_LISTING_URL}"
SRC_URL = "{PRODUCT_LISTING_URL}"
# Pagination query param name (page, pgNum, p, offset, ...). code_writer
# replaces the placeholder with the site's actual param (from
# navigation_analysis.pagination.page_param_name); if left unfilled,
# defaults to "page" (back-compat with single-listing sites).
PAGE_PARAM_NAME = "{PAGE_PARAM_NAME}"
if PAGE_PARAM_NAME.startswith("{") and PAGE_PARAM_NAME.endswith("}"):
    PAGE_PARAM_NAME = "page"
# Multi-listing enumeration: for sites with multiple category/listing pages,
# code_writer edits this list to add each listing URL (e.g. 20 specialty
# pages). Default: single listing — back-compat (single-listing sites behave
# exactly as before: one URL, ?page=N).
PRODUCT_LISTING_URLS = [PRODUCT_LISTING_URL]
DELAY_BETWEEN_REQUESTS = {DELAY_BETWEEN_REQUESTS}
MAX_RETRIES = 3
# Safety cap on listing pagination (None = unlimited). code_writer may set this
# to bound discovery on very large sites; hitting it yields stop_reason="max_pages_hit".
MAX_PAGES = None
# Fail-fast wall-clock deadline for Phase 1 discovery. A blocked strategy (e.g.
# bare requests against an anti-bot site) can iterate many listings, each
# retrying for ~100s, running unbounded. Exceeding this deadline yields
# stop_reason="navigate_error" (the gate treats it as "gave up, not exhausted"
# → strategy switch) instead of a multi-hour hang. Bounds discovery regardless
# of the failure mode (blocking, infinite pagination, slow proxy escalation).
DISCOVERY_DEADLINE_SECONDS = 300
# [job-58 birkenstock] One-shot re-enumeration delay when Phase 1 ends with
# ZERO discovered URLs and no hard navigate_error — the "200-but-blocked"
# signature: an anti-bot challenge or consent wall served with HTTP 200
# selects zero product links, which used to be classified as a genuine
# "short_page" end-of-catalog. Backing off once and re-fetching rides out the
# block window (the tester's run 90s earlier had discovered 15 URLs). Healthy
# runs never pay this cost. 0 disables the retry.
EMPTY_DISCOVERY_RETRY_DELAY_S = 45

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
}

# [job-58 birkenstock] Persistent session — cookies round-trip across every
# request and the connection pool is reused. Bare requests.get() is a
# cookieless one-shot per call: Akamai never sees the consent/_abck cookie a
# real browser carries, every hit re-raises the bot score, and the test
# phase's ~10 rapid draft runs in 45 minutes burned the worker IP's
# reputation right before execution ran. A session both looks more human
# and lets the 45s discovery retry ride out a challenge window with the
# cookies it was handed.
SESSION = requests.Session()
SESSION.headers.update(HEADERS)

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
TIMESTAMP = datetime.now(timezone.utc).strftime("%Y-%m-%d_%H%M%S")
OUTPUT_FILE = os.path.join(SCRIPT_DIR, f"output_{TIMESTAMP}.json")
INPUT_FILE = os.path.join(SCRIPT_DIR, "input_urls.json")
LOG_FILE = os.path.join(os.path.dirname(SCRIPT_DIR), "logs", f"{SITE_SLUG}.log")

# ═══════════════════════════════════════════════════════════════════════════════
# LOGGING
# ═══════════════════════════════════════════════════════════════════════════════

os.makedirs(os.path.dirname(LOG_FILE), exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[
        logging.FileHandler(LOG_FILE),
        logging.StreamHandler(),
    ],
)
logger = logging.getLogger(__name__)

proxy_config = ProxyConfig.get_instance()


# ═══════════════════════════════════════════════════════════════════════════════
# HELPERS
# ═══════════════════════════════════════════════════════════════════════════════

def clean_html(html_str: str) -> str:
    if not html_str:
        return ""
    text = re.sub(r"<[^>]+>", " ", html_str)
    text = unescape(text)
    return re.sub(r"\s+", " ", text).strip()


def make_absolute_url(url: str, base: str = SITE_URL) -> str:
    if not url:
        return ""
    if url.startswith("http"):
        return url
    if url.startswith("//"):
        return f"https:{url}"
    return urljoin(base, url)


def fetch_page(url: str) -> Optional[tuple[BeautifulSoup, int]]:
    ssl_verify = proxy_config.config.get("strategy", {}).get("ssl_verify", False)
    escalation = proxy_config.get_escalation_tier()

    for tier in ["none", *escalation]:
        if should_warn_residential(tier):
            warn_residential_usage(url)

        proxies = proxy_config.get_proxy_dict(tier) if tier != "none" else None
        max_retries = proxy_config.get_max_retries(tier) if tier != "none" else MAX_RETRIES
        cooldown = proxy_config.get_cooldown(tier) if tier != "none" else DELAY_BETWEEN_REQUESTS * 2

        for attempt in range(max_retries):
            try:
                time.sleep(DELAY_BETWEEN_REQUESTS)
                response = SESSION.get(url, proxies=proxies, timeout=proxy_config.get_timeout(), verify=ssl_verify)
                if response.status_code == 200:
                    response.raise_for_status()
                    return BeautifulSoup(response.text, "html.parser"), response.status_code
                if proxy_config.is_banned(response.status_code, response.text):
                    logger.warning(f"Ban detected ({response.status_code}) on tier '{tier}', escalating...")
                    break
                response.raise_for_status()
                return BeautifulSoup(response.text, "html.parser"), response.status_code
            except requests.RequestException as e:
                logger.error(f"Failed to fetch {url} (attempt {attempt + 1}/{max_retries}, tier={tier}): {e}")
                if attempt < max_retries - 1:
                    time.sleep(cooldown)

    return None


# ═══════════════════════════════════════════════════════════════════════════════
# EXTRACTION - CUSTOMIZE selectors below
# ═══════════════════════════════════════════════════════════════════════════════

def extract_jsonld(soup: BeautifulSoup) -> Optional[dict]:
    for script in soup.find_all("script", type="application/ld+json"):
        try:
            data = json.loads(script.string)
            if isinstance(data, dict) and data.get("@type") == "Product":
                return data
            if isinstance(data, list):
                for item in data:
                    if isinstance(item, dict) and item.get("@type") == "Product":
                        return item
        except (json.JSONDecodeError, TypeError):
            continue
    return None


def extract_product_from_page(soup: BeautifulSoup, url: str, status_code: int, src_url: str) -> dict:
    product = {
        "id": 0,
        "title": "",
        "price": "",
        "availability": "",
        "original_price": "",
        "currency": "",
        "url": url,
        "src_url": src_url,
        "location": "",
        "status_code": status_code,
        "scraped_at": datetime.now(timezone.utc).isoformat(),
        "remarks": "",
    }

    jsonld = extract_jsonld(soup)

    # Title
    if jsonld:
        product["title"] = jsonld.get("name", "")
    else:
        el = soup.select_one("{TITLE_SELECTOR}")
        product["title"] = el.get_text(strip=True) if el else ""

    # Price
    if jsonld:
        offers = jsonld.get("offers", [{}])
        if isinstance(offers, list):
            offers = offers[0] if offers else {}
        product["price"] = offers.get("price", "")
        high_price = offers.get("highPrice", "")
        if high_price and float(high_price) > float(product["price"] or 0):
            product["original_price"] = high_price
    else:
        price_el = soup.select_one("{PRICE_SELECTOR}")
        product["price"] = price_el.get_text(strip=True) if price_el else ""
        orig_el = soup.select_one("{ORIGINAL_PRICE_SELECTOR}")
        product["original_price"] = orig_el.get_text(strip=True) if orig_el else ""

    # Currency
    product["currency"] = jsonld.get("offers", {}).get("priceCurrency", "USD") if jsonld else "USD"

    # Availability
    if jsonld:
        avail = jsonld.get("offers", {}).get("availability", "")
        product["availability"] = "In Stock" if "InStock" in avail else "Out of Stock"
    else:
        stock_el = soup.select_one("{AVAILABILITY_SELECTOR}")
        if stock_el:
            stock_text = stock_el.get_text(strip=True).lower()
            product["availability"] = "In Stock" if "in stock" in stock_text else "Out of Stock"

    return product


# ═══════════════════════════════════════════════════════════════════════════════
# DISCOVERY
# ═══════════════════════════════════════════════════════════════════════════════

def discover_product_urls() -> tuple[list[str], dict]:
    """Phase 1: discover product URLs by paginating through listing pages.

    Returns ``(urls, discovery_meta)`` where ``discovery_meta`` carries the
    signals required by the discovery-coverage gate (contract §1/§2):

    - ``stop_reason``: why the loop terminated. ``navigate_error`` is sticky
      across listings and distinguishable from exhaustion (H4).
    - ``max_pages_hit``: True only when the loop stopped due to a non-None
      ``MAX_PAGES`` cap.
    - ``discovered_urls``: raw pre-filter URL count (== len(urls)).
    """
    all_urls = []
    seen = set()
    # Default per contract §2: a loop that completes without an explicit break
    # is treated as "ran off the end of pagination" (no next link).
    stop_reason = "no_next_link"
    saw_navigate_error = False
    _deadline_start = time.monotonic()

    # Enumerate every listing/category URL, paginating each until exhausted.
    # Dedupe across listings via `seen`. For a single-listing site this is
    # identical to the old ?page=N loop.
    for listing_url in PRODUCT_LISTING_URLS:
        page = 1
        while True:
            # Fail-fast: a blocked/slow discovery must not run unbounded.
            if time.monotonic() - _deadline_start > DISCOVERY_DEADLINE_SECONDS:
                logger.warning(
                    "Discovery exceeded %ss deadline — stopping (navigate_error). "
                    "A blocked strategy should fail fast so the gate switches.",
                    DISCOVERY_DEADLINE_SECONDS,
                )
                saw_navigate_error = True
                stop_reason = "navigate_error"
                break
            sep = "&" if "?" in listing_url else "?"
            paginated_url = f"{listing_url}{sep}{PAGE_PARAM_NAME}={page}"
            logger.info(f"Fetching listing page {page}: {paginated_url}")

            result = fetch_page(paginated_url)
            if not result:
                # HTTP error / 429-502-503 / connection failure / rate-limit bail.
                # This is NOT exhaustion — the loop gave up (H4). navigate_error
                # is sticky: if any listing failed, the gate must FAIL.
                saw_navigate_error = True
                stop_reason = "navigate_error"
                break

            soup, _ = result
            links = soup.select("{PRODUCT_LINK_SELECTOR}")
            new_on_page = 0
            for link in links:
                href = link.get("href", "")
                absolute_url = make_absolute_url(href)
                if absolute_url and absolute_url not in seen:
                    seen.add(absolute_url)
                    all_urls.append(absolute_url)
                    new_on_page += 1

            logger.info(
                f"Listing {listing_url} page {page}: {len(links)} products "
                f"found (total: {len(all_urls)})"
            )

            # Short page: fewer items than expected → genuine end of results.
            if len(links) == 0:
                stop_reason = "short_page"
                break

            # Dedup worked: page returned items but none were new → exhausted.
            if new_on_page == 0:
                stop_reason = "no_new_items"
                break

            # MAX_PAGES safety cap (only fires when MAX_PAGES is non-None).
            if MAX_PAGES is not None and page >= MAX_PAGES:
                stop_reason = "max_pages_hit"
                logger.info(f"Hit MAX_PAGES cap ({MAX_PAGES}) at {listing_url}, stopping")
                break

            page += 1

    # navigate_error takes priority over later successes so the classifier sees FAIL.
    if saw_navigate_error:
        stop_reason = "navigate_error"
    elif not all_urls and stop_reason in ("short_page", "no_next_link", "no_new_items"):
        # [job-58 birkenstock] Ending every listing with ZERO discovered URLs
        # and no hard error is the "200-but-blocked" signature: an anti-bot
        # challenge or consent wall served with HTTP 200 selects zero product
        # links, which "short_page" would misreport as a genuine end-of-catalog.
        # A real catalog-end requires having seen items. Reclassify so the
        # discovery-coverage gate FAILs the run instead of declaring exhaustion.
        stop_reason = "empty_first_page"

    discovery_meta = {
        "stop_reason": stop_reason,
        "max_pages_hit": stop_reason == "max_pages_hit",
        "discovered_urls": len(all_urls),
    }
    return all_urls, discovery_meta


def discover_product_urls_with_retry() -> tuple[list[str], dict]:
    """[job-58 birkenstock] One-shot retry around Phase 1 discovery.

    A zero-URL discovery with no hard navigate_error is the "200-but-blocked"
    signature (see the reclassification in ``discover_product_urls``): the
    listing fetch SUCCEEDS but yields zero product links. Back off once and
    re-enumerate — the block window is often shorter than the gap between the
    test phase's runs (birkenstock's tester run discovered 15 URLs 90s before
    the blocked execution run). Healthy runs never enter the retry path.
    """
    urls, meta = discover_product_urls()
    if urls or not EMPTY_DISCOVERY_RETRY_DELAY_S:
        return urls, meta
    if meta.get("stop_reason") in ("navigate_error", "navigate_throttled"):
        return urls, meta
    logger.warning(
        "Phase 1 discovered 0 URLs (stop_reason=%s, likely 200-but-blocked) — "
        "retrying once after %ss", meta.get("stop_reason"),
        EMPTY_DISCOVERY_RETRY_DELAY_S,
    )
    time.sleep(EMPTY_DISCOVERY_RETRY_DELAY_S)
    urls, meta = discover_product_urls()
    meta["retried_empty_discovery"] = True
    if not urls and meta.get("stop_reason") not in ("navigate_error", "navigate_throttled"):
        meta["stop_reason"] = "empty_first_page"
    return urls, meta


# ═══════════════════════════════════════════════════════════════════════════════
# INPUT HANDLING
# ═══════════════════════════════════════════════════════════════════════════════

def load_urls_from_file(filepath: str) -> list[str]:
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data.get("urls", [])


def save_urls_to_file(filepath: str, urls: list[str]) -> None:
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump({"urls": urls}, f, indent=2, ensure_ascii=False)
    logger.info(f"Saved {len(urls)} URLs to {filepath}")


# ═══════════════════════════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════════════════════════

# ── CLI CONTRACT — keep every line below when adapting ───────────────────────
# The pipeline launches this scraper with EXACTLY these names. A flag missing
# from the argparse below is STRIPPED at launch and discovery silently falls
# back to the seed file (input_urls.json). Same for the SCRAPER_LISTING_URL
# env read in main(). ADD flags if you need them; NEVER remove or rename:
#   --fresh-discovery  always (execution)     --listing-url  navigation/list_page
#   --query            search_term            --input/--sample/--limit  testing
#   --discover-only    Phase-1 probe          (+ SCRAPER_LISTING_URL env read)
# Source of truth: webapp/agents/constants.py
# ──────────────────────────────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser(description=f"HTTP scraper for {SITE_NAME}")
    parser.add_argument("--sample", action="store_true", help="Scrape only 5 products")
    parser.add_argument("--limit", type=int, default=None, help="Max products to scrape")
    parser.add_argument("--input", type=str, default=None, help="Path to input URLs JSON file")
    parser.add_argument("--urls", nargs="+", default=None, help="Product URLs as arguments")
    parser.add_argument(
        "--discover-only",
        action="store_true",
        help="Run Phase 1 discovery only; emit discovery_coverage, skip Phase 2 extraction",
    )
    parser.add_argument(
        "--fresh-discovery",
        action="store_true",
        help="Ignore any discovery cache and re-run Phase 1 (accepted as a no-op here: "
        "requests_scraper has no checkpoint file to skip)",
    )
    args = parser.parse_args()

    start_time = time.time()

    logger.info("=" * 80)
    logger.info(f"Starting scraper for {SITE_NAME}")
    logger.info(f"Site: {SITE_URL}")
    logger.info(f"Listing URL: {PRODUCT_LISTING_URL}")
    logger.info(f"Output: {OUTPUT_FILE}")
    logger.info("=" * 80)

    if args.fresh_discovery:
        logger.info(
            "--fresh-discovery accepted (no-op: requests_scraper has no "
            "discovered_urls_checkpoint.json to ignore; input_urls.json is rewritten on every discovery)"
        )

    product_urls = []
    discovered_urls_raw = 0
    ran_phase1 = False
    skipped_reason: Optional[str] = None
    discovery_meta: dict = {"stop_reason": "skipped", "max_pages_hit": False}

    # Phase 1: URL discovery (or load from input).
    # F6 DETERMINISTIC DISCOVERY GATE (env-var): run_execution injects
    # SCRAPER_LISTING_URL because the LLM-adapted argparse may drop
    # --listing-url/--fresh-discovery (the CLI-contract guard then strips
    # them). Without this gate the seed-file branch below ALWAYS wins (the
    # seed file exists — run_execution stages input_urls.json) and discovery
    # never runs (prod 285: 1 item from 4 seeds; pagination dead). In-place
    # [:] mutation so LLM-copied drafts that alias the list stay coherent.
    _env_listing = os.environ.get("SCRAPER_LISTING_URL", "").strip()
    if _env_listing:
        PRODUCT_LISTING_URLS[:] = [_env_listing]
        logger.info("Env gate: SCRAPER_LISTING_URL set — forcing Phase 1 discovery on %s",
                    _env_listing[:80])

    if args.discover_only or _env_listing:
        logger.info("Discovery mode (%s): running Phase 1, skipping Phase 2 extraction",
                    "env-gate" if _env_listing else "--discover-only")
        product_urls, discovery_meta = discover_product_urls_with_retry()
        discovered_urls_raw = len(product_urls)
        ran_phase1 = True
        save_urls_to_file(INPUT_FILE, product_urls)
    elif args.urls:
        product_urls = args.urls
        skipped_reason = "url_list_mode"
    elif args.input:
        product_urls = load_urls_from_file(args.input)
        skipped_reason = "url_list_mode"
    elif os.path.exists(INPUT_FILE):
        logger.info(f"Loading previously discovered URLs from {INPUT_FILE}")
        product_urls = load_urls_from_file(INPUT_FILE)
        # input_urls.json is this template's persisted discovery output; reusing it
        # means Phase 1 did not run this invocation.
        skipped_reason = "checkpoint_loaded"
    else:
        logger.info("No input_urls.json found. Discovering products from listing page...")
        product_urls, discovery_meta = discover_product_urls_with_retry()
        discovered_urls_raw = len(product_urls)
        ran_phase1 = True
        save_urls_to_file(INPUT_FILE, product_urls)

    # Raw discovered count is captured BEFORE any sample/limit slicing so it
    # reflects true discovery yield (contract §1: "raw pre-filter discovered URL count").
    if not ran_phase1:
        discovered_urls_raw = len(product_urls)

    # Sample/limit only apply when Phase 2 extraction will run.
    if not args.discover_only:
        if args.sample:
            product_urls = product_urls[:5]
        if args.limit:
            product_urls = product_urls[: args.limit]

    logger.info(f"Total products to scrape: {len(product_urls)}")

    results = []
    failed = 0

    if not args.discover_only:
        # Phase 2: extract fields from each discovered item page.
        for i, url in enumerate(product_urls):
            result = fetch_page(url)
            if result:
                soup, status_code = result
                product = extract_product_from_page(soup, url, status_code, SRC_URL)
                product["id"] = i + 1
                results.append(product)
            else:
                logger.error(f"Failed to fetch: {url}")
                failed += 1

            if (i + 1) % 25 == 0:
                percent = ((i + 1) / len(product_urls)) * 100
                logger.info(f"Progress: [{i + 1}/{len(product_urls)}] ({percent:.1f}%)")
    else:
        logger.info("--discover-only: skipping Phase 2 extraction (results list left empty)")

    # discovery_coverage block — contract §1. Always emitted so the gate can read
    # a uniform schema regardless of which path produced the output.
    if ran_phase1:
        stop_reason = discovery_meta.get("stop_reason", "no_next_link")
    else:
        stop_reason = "skipped"

    discovery_coverage = {
        "stop_reason": stop_reason,
        "found": len(results),  # post-filter extracted item count (0 when Phase 2 skipped)
        "discovered_urls": discovered_urls_raw,  # raw pre-filter count (diagnostic)
        "expected_total": None,  # no baked-in coverage_target for this template
        # No category/specialty enumeration in this strategy — listing URLs are
        # not treated as a coverage dimension. Tier 2 is a no-op here.
        "dimensions_iterated": 0,
        "dimensions_total": 0,
        "max_pages_hit": discovery_meta.get("max_pages_hit", False),
        "ran_phase1": ran_phase1,
        "skipped_reason": skipped_reason,
    }

    output = {
        "site": {
            "name": SITE_NAME,
            "url": SITE_URL,
            "platform": PLATFORM,
            "scraping_method": SCRAPING_METHOD,
            "scraped_at": datetime.now(timezone.utc).isoformat(),
        },
        "products": results,
        "metadata": {
            "scraping_duration_seconds": round(time.time() - start_time, 2),
            "failed_products": failed,
            "rate_limit_delay": DELAY_BETWEEN_REQUESTS,
            "discovered_urls": discovered_urls_raw,
            "discovery_coverage": discovery_coverage,
        },
    }

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(output, f, indent=2, ensure_ascii=False)

    logger.info("=" * 80)
    logger.info("DISCOVERY COMPLETE (--discover-only)" if args.discover_only else "EXTRACTION COMPLETE")
    logger.info(f"Total: {len(results)}, Failed: {failed}")
    logger.info(
        f"Discovery coverage: stop_reason={stop_reason}, found={len(results)}, "
        f"discovered_urls={discovered_urls_raw}, ran_phase1={ran_phase1}, "
        f"skipped_reason={skipped_reason}"
    )
    logger.info(f"Duration: {round(time.time() - start_time, 2)}s")
    logger.info(f"Output: {OUTPUT_FILE}")
    logger.info("=" * 80)


if __name__ == "__main__":
    main()
