#!/usr/bin/env python3
"""
HTTP Requests Scraper Template

Uses requests + BeautifulSoup for static HTML ecommerce sites.
Generated by Code Writer Agent for Universal Ecommerce Scraper.

The scraper reads input_urls.json from its own directory by default.
Can also accept URLs via --urls or --input flags.

Usage:
    python3 scraper.py                    # reads input_urls.json from same folder
    python3 scraper.py --input urls.json  # explicit input file
    python3 scraper.py --urls url1 url2     # URLs as CLI arguments
"""

import argparse
import json
import logging
import os
import re
import sys
import time
from datetime import datetime, timezone
from html import unescape
from typing import Optional
from urllib.parse import urljoin

import requests
from bs4 import BeautifulSoup

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from src.proxy import ProxyConfig, should_warn_residential, warn_residential_usage

# ═══════════════════════════════════════════════════════════════════════════════
# CONFIGURATION - Update these values
# ═══════════════════════════════════════════════════════════════════════════════

SITE_NAME = "{SITE_NAME}"
SITE_URL = "{SITE_URL}"
PLATFORM = "{PLATFORM}"
SCRAPING_METHOD = "http_requests"
SITE_SLUG = "{SITE_SLUG}"

PRODUCT_LISTING_URL = "{PRODUCT_LISTING_URL}"
SRC_URL = "{PRODUCT_LISTING_URL}"
DELAY_BETWEEN_REQUESTS = {DELAY_BETWEEN_REQUESTS}
MAX_RETRIES = 3

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
}

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
TIMESTAMP = datetime.now(timezone.utc).strftime("%Y-%m-%d_%H%M%S")
OUTPUT_FILE = os.path.join(SCRIPT_DIR, f"output_{TIMESTAMP}.json")
INPUT_FILE = os.path.join(SCRIPT_DIR, "input_urls.json")
LOG_FILE = os.path.join(os.path.dirname(SCRIPT_DIR), "logs", f"{SITE_SLUG}.log")

# ═══════════════════════════════════════════════════════════════════════════════
# LOGGING
# ═══════════════════════════════════════════════════════════════════════════════

os.makedirs(os.path.dirname(LOG_FILE), exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[
        logging.FileHandler(LOG_FILE),
        logging.StreamHandler(),
    ],
)
logger = logging.getLogger(__name__)

proxy_config = ProxyConfig.get_instance()


# ═══════════════════════════════════════════════════════════════════════════════
# HELPERS
# ═══════════════════════════════════════════════════════════════════════════════

def clean_html(html_str: str) -> str:
    if not html_str:
        return ""
    text = re.sub(r"<[^>]+>", " ", html_str)
    text = unescape(text)
    return re.sub(r"\s+", " ", text).strip()


def make_absolute_url(url: str, base: str = SITE_URL) -> str:
    if not url:
        return ""
    if url.startswith("http"):
        return url
    if url.startswith("//"):
        return f"https:{url}"
    return urljoin(base, url)


def fetch_page(url: str) -> Optional[tuple[BeautifulSoup, int]]:
    ssl_verify = proxy_config.config.get("strategy", {}).get("ssl_verify", False)
    escalation = proxy_config.get_escalation_tier()

    for tier in ["none", *escalation]:
        if should_warn_residential(tier):
            warn_residential_usage(url)

        proxies = proxy_config.get_proxy_dict(tier) if tier != "none" else None
        max_retries = proxy_config.get_max_retries(tier) if tier != "none" else MAX_RETRIES
        cooldown = proxy_config.get_cooldown(tier) if tier != "none" else DELAY_BETWEEN_REQUESTS * 2

        for attempt in range(max_retries):
            try:
                time.sleep(DELAY_BETWEEN_REQUESTS)
                response = requests.get(url, headers=HEADERS, proxies=proxies, timeout=proxy_config.get_timeout(), verify=ssl_verify)
                if response.status_code == 200:
                    response.raise_for_status()
                    return BeautifulSoup(response.text, "html.parser"), response.status_code
                if proxy_config.is_banned(response.status_code, response.text):
                    logger.warning(f"Ban detected ({response.status_code}) on tier '{tier}', escalating...")
                    break
                response.raise_for_status()
                return BeautifulSoup(response.text, "html.parser"), response.status_code
            except requests.RequestException as e:
                logger.error(f"Failed to fetch {url} (attempt {attempt + 1}/{max_retries}, tier={tier}): {e}")
                if attempt < max_retries - 1:
                    time.sleep(cooldown)

    return None


# ═══════════════════════════════════════════════════════════════════════════════
# EXTRACTION - CUSTOMIZE selectors below
# ═══════════════════════════════════════════════════════════════════════════════

def extract_jsonld(soup: BeautifulSoup) -> Optional[dict]:
    for script in soup.find_all("script", type="application/ld+json"):
        try:
            data = json.loads(script.string)
            if isinstance(data, dict) and data.get("@type") == "Product":
                return data
            if isinstance(data, list):
                for item in data:
                    if isinstance(item, dict) and item.get("@type") == "Product":
                        return item
        except (json.JSONDecodeError, TypeError):
            continue
    return None


def extract_product_from_page(soup: BeautifulSoup, url: str, status_code: int, src_url: str) -> dict:
    product = {
        "id": 0,
        "title": "",
        "price": "",
        "availability": "",
        "original_price": "",
        "currency": "",
        "url": url,
        "src_url": src_url,
        "location": "",
        "status_code": status_code,
        "scraped_at": datetime.now(timezone.utc).isoformat(),
        "remarks": "",
    }

    jsonld = extract_jsonld(soup)

    # Title
    if jsonld:
        product["title"] = jsonld.get("name", "")
    else:
        el = soup.select_one("{TITLE_SELECTOR}")
        product["title"] = el.get_text(strip=True) if el else ""

    # Price
    if jsonld:
        offers = jsonld.get("offers", [{}])
        if isinstance(offers, list):
            offers = offers[0] if offers else {}
        product["price"] = offers.get("price", "")
        high_price = offers.get("highPrice", "")
        if high_price and float(high_price) > float(product["price"] or 0):
            product["original_price"] = high_price
    else:
        price_el = soup.select_one("{PRICE_SELECTOR}")
        product["price"] = price_el.get_text(strip=True) if price_el else ""
        orig_el = soup.select_one("{ORIGINAL_PRICE_SELECTOR}")
        product["original_price"] = orig_el.get_text(strip=True) if orig_el else ""

    # Currency
    product["currency"] = jsonld.get("offers", {}).get("priceCurrency", "USD") if jsonld else "USD"

    # Availability
    if jsonld:
        avail = jsonld.get("offers", {}).get("availability", "")
        product["availability"] = "In Stock" if "InStock" in avail else "Out of Stock"
    else:
        stock_el = soup.select_one("{AVAILABILITY_SELECTOR}")
        if stock_el:
            stock_text = stock_el.get_text(strip=True).lower()
            product["availability"] = "In Stock" if "in stock" in stock_text else "Out of Stock"

    return product


# ═══════════════════════════════════════════════════════════════════════════════
# DISCOVERY
# ═══════════════════════════════════════════════════════════════════════════════

def discover_product_urls() -> list[str]:
    all_urls = []
    seen = set()
    page = 1

    while True:
        paginated_url = f"{PRODUCT_LISTING_URL}?page={page}"
        logger.info(f"Fetching listing page {page}: {paginated_url}")

        result = fetch_page(paginated_url)
        if not result:
            break

        soup, _ = result
        links = soup.select("{PRODUCT_LINK_SELECTOR}")
        for link in links:
            href = link.get("href", "")
            absolute_url = make_absolute_url(href)
            if absolute_url and absolute_url not in seen:
                seen.add(absolute_url)
                all_urls.append(absolute_url)

        logger.info(f"Page {page}: {len(links)} products found (total: {len(all_urls)})")

        if len(links) == 0:
            break

        page += 1

    return all_urls


# ═══════════════════════════════════════════════════════════════════════════════
# INPUT HANDLING
# ═══════════════════════════════════════════════════════════════════════════════

def load_urls_from_file(filepath: str) -> list[str]:
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data.get("urls", [])


def save_urls_to_file(filepath: str, urls: list[str]) -> None:
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump({"urls": urls}, f, indent=2, ensure_ascii=False)
    logger.info(f"Saved {len(urls)} URLs to {filepath}")


# ═══════════════════════════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(description=f"HTTP scraper for {SITE_NAME}")
    parser.add_argument("--sample", action="store_true", help="Scrape only 5 products")
    parser.add_argument("--limit", type=int, default=None, help="Max products to scrape")
    parser.add_argument("--input", type=str, default=None, help="Path to input URLs JSON file")
    parser.add_argument("--urls", nargs="+", default=None, help="Product URLs as arguments")
    args = parser.parse_args()

    start_time = time.time()

    logger.info("=" * 80)
    logger.info(f"Starting scraper for {SITE_NAME}")
    logger.info(f"Site: {SITE_URL}")
    logger.info(f"Listing URL: {PRODUCT_LISTING_URL}")
    logger.info(f"Output: {OUTPUT_FILE}")
    logger.info("=" * 80)

    product_urls = []

    if args.urls:
        product_urls = args.urls
    elif args.input:
        product_urls = load_urls_from_file(args.input)
    elif os.path.exists(INPUT_FILE):
        product_urls = load_urls_from_file(INPUT_FILE)
    else:
        logger.info("No input_urls.json found. Discovering products from listing page...")
        product_urls = discover_product_urls()
        save_urls_to_file(INPUT_FILE, product_urls)

    if args.sample:
        product_urls = product_urls[:5]
    if args.limit:
        product_urls = product_urls[: args.limit]

    logger.info(f"Total products to scrape: {len(product_urls)}")

    results = []
    failed = 0

    for i, url in enumerate(product_urls):
        result = fetch_page(url)
        if result:
            soup, status_code = result
            product = extract_product_from_page(soup, url, status_code, SRC_URL)
            product["id"] = i + 1
            results.append(product)
        else:
            logger.error(f"Failed to fetch: {url}")
            failed += 1

        if (i + 1) % 25 == 0:
            percent = ((i + 1) / len(product_urls)) * 100
            logger.info(f"Progress: [{i + 1}/{len(product_urls)}] ({percent:.1f}%)")

    output = {
        "site": {
            "name": SITE_NAME,
            "url": SITE_URL,
            "platform": PLATFORM,
            "scraping_method": SCRAPING_METHOD,
            "scraped_at": datetime.now(timezone.utc).isoformat(),
        },
        "products": results,
        "metadata": {
            "scraping_duration_seconds": round(time.time() - start_time, 2),
            "failed_products": failed,
            "rate_limit_delay": DELAY_BETWEEN_REQUESTS,
        },
    }

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(output, f, indent=2, ensure_ascii=False)

    logger.info("=" * 80)
    logger.info("EXTRACTION COMPLETE")
    logger.info(f"Total: {len(results)}, Failed: {failed}")
    logger.info(f"Duration: {round(time.time() - start_time, 2)}s")
    logger.info(f"Output: {OUTPUT_FILE}")
    logger.info("=" * 80)


if __name__ == "__main__":
    main()
