#!/usr/bin/env python3
"""
HTTP Requests Scraper — bose.com (Salesforce Commerce Cloud)

Two-phase architecture:
  Phase 1: discover PDP URLs by paginating/enumerating the category listings
           (https://www.bose.com/c/headphones first, per navigation_analysis).
           Measured: bose category grids are FULLY server-rendered on page 1
           (offset params ?start=&sz= are ignored, probe-verified) — the shared
           discovery module's no-progress termination handles that correctly.
  Phase 2: fetch each PDP and extract fields from the embedded JSON-LD
           ProductGroup (hasVariant[] per color) with verified CSS fallbacks.

Generated by Code Writer Agent for Universal Ecommerce Scraper.

Usage:
    python3 scraper_draft.py                    # full run: Phase 1 discovery + Phase 2
    python3 scraper_draft.py --input urls.json  # explicit input file
    python3 scraper_draft.py --urls url1 url2   # URLs as CLI arguments
    python3 scraper_draft.py --sample           # 5 products only
"""

import argparse
import json
import logging
import os
import re
import sys
import time
from datetime import datetime, timezone
from html import unescape
from typing import Optional
from urllib.parse import unquote, urljoin, urlparse  # Code Writer fix: unquote lives in urllib.parse, not html

import requests  # noqa: F401 -- drafts' Phase-2 helpers commonly need it
from bs4 import BeautifulSoup

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))

import urllib3  # noqa: E402

# The shared fetch ladder verifies TLS against a bundle that trips urllib3's
# InsecureRequestWarning on this host; silence the noise (fetch behavior itself
# is the shared module's, untouched).
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# ═══════════════════════════════════════════════════════════════════════════════
# CONFIGURATION
# ═══════════════════════════════════════════════════════════════════════════════

SITE_NAME = "Bose"
SITE_URL = "https://www.bose.com"
PLATFORM = "salesforce_commerce_cloud"
SCRAPING_METHOD = "http_requests"
SITE_SLUG = "bose-com"

# Promoted listing URL from navigation_analysis.search (the page where the
# analyzer's 8 headphone products were found).
PRODUCT_LISTING_URL = "https://www.bose.com/c/headphones"
SRC_URL = PRODUCT_LISTING_URL

# Code Writer adapted: multi-listing enumeration. bose category grids are
# fully server-rendered on their first page (probe: ?start=24&sz=24 added ZERO
# new URLs vs the baseline), so full-catalog coverage comes from enumerating
# EVERY category listing rather than deep pagination. Headphones first — it is
# the promoted listing from navigation_analysis.
PRODUCT_LISTING_URLS = [
    "https://www.bose.com/c/headphones",
    "https://www.bose.com/c/new-arrivals",
    "https://www.bose.com/c/earbuds",
    "https://www.bose.com/c/speakers",
    "https://www.bose.com/c/home-theater",
    "https://www.bose.com/c/portable-pa",
    "https://www.bose.com/c/aviation-headsets",
    "https://www.bose.com/c/sale",
]
# Known-good listing shape for the zero-URL self-heal retry (job-310 class).
DEFAULT_LISTING_URL = PRODUCT_LISTING_URL

# SFCC page param. Placeholder left unfilled on purpose: bose ignores
# offset/page params on category HTML (probe-verified), so the shared module
# terminates after the one server-rendered page per listing via no-progress.
PAGE_PARAM_NAME = "{PAGE_PARAM_NAME}"
if PAGE_PARAM_NAME.startswith("{") and PAGE_PARAM_NAME.endswith("}"):
    PAGE_PARAM_NAME = "page"
PAGE_SIZE = None
OFFSET_MODE = False
EXTRA_PAGE_PARAMS: dict = {}
DELAY_BETWEEN_REQUESTS = 1.5
MAX_PAGES = None  # unlimited — never cap the catalog
DISCOVERY_DEADLINE_SECONDS = 300
EMPTY_DISCOVERY_RETRY_DELAY_S = 45

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
}

# ── HTTP FETCH — SHARED MODULE, NOT YOURS TO REIMPLEMENT (CRITICAL) ──────────
# Probe-verified wiring for this site: proxy tier "none", direct HTTP reaches
# both listing and PDP pages (200 + full server-rendered body). The ladder
# stays wired regardless — it is a no-op on tier 0 for this site and remains
# the recovery path if bose starts throttling.
from src.http_fetch import create_fetch_page
from src.page_analysis import phase2_instant_fail

fetch_page = create_fetch_page(delay_s=DELAY_BETWEEN_REQUESTS, headers=HEADERS)

# ── LISTING DISCOVERY — SHARED MODULE, NOT YOURS TO REIMPLEMENT (CRITICAL) ───
from src.listing_discovery import discover_listing_urls_with_retry
from src.discovery import discover_item_urls, config_for_load_more  # _DISCOVERY_IMPORT_APPLIED (enforced — do not remove)

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
TIMESTAMP = datetime.now(timezone.utc).strftime("%Y-%m-%d_%H%M%S_%f")
OUTPUT_FILE = os.path.join(SCRIPT_DIR, f"output_{TIMESTAMP}_{os.getpid()}.json")
INPUT_FILE = os.path.join(SCRIPT_DIR, "input_urls.json")
# Code Writer fix: output-contract key for this job — previously referenced
# undefined inside main()'s save-time filter (F821); now defined module-level.
OUTPUT_KEY = "products"
LOG_FILE = os.path.join(os.path.dirname(SCRIPT_DIR), "logs", f"{SITE_SLUG}.log")

# ═══════════════════════════════════════════════════════════════════════════════
# LOGGING
# ═══════════════════════════════════════════════════════════════════════════════

os.makedirs(os.path.dirname(LOG_FILE), exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[
        logging.FileHandler(LOG_FILE),
        logging.StreamHandler(),
    ],
)
logger = logging.getLogger(__name__)


# ═══════════════════════════════════════════════════════════════════════════════
# HELPERS
# ═══════════════════════════════════════════════════════════════════════════════

def clean_html(html_str: str) -> str:
    if not html_str:
        return ""
    text = re.sub(r"<[^>]+>", " ", html_str)
    text = unescape(text)
    return re.sub(r"\s+", " ", text).strip()


def make_absolute_url(url: str, base: str = SITE_URL) -> str:
    if not url:
        return ""
    if url.startswith("http"):
        return url
    if url.startswith("//"):
        # Protocol-relative: only keep as https: when a plausible netloc follows;
        # "/p/x.html" style paths must join against the site root instead.
        if "." in url[2:].split("/", 1)[0]:
            return f"https:{url}"
        return urljoin(base, url.lstrip("/").insert(0, "/") if False else "/" + url.lstrip("/"))
    return urljoin(base, url)


# ── FIELD NORMALIZERS — inline on purpose, NOT a src import ──────────────────

def _norm_price(value) -> Optional[float]:
    """Strip currency symbols/whitespace → float, or None when no digits."""
    if value is None:
        return None
    cleaned = re.sub(r"[^\d.,-]", "", str(value).strip())
    if not re.search(r"\d", cleaned):
        return None
    if "," in cleaned and "." in cleaned:
        if cleaned.rfind(",") > cleaned.rfind("."):
            cleaned = cleaned.replace(".", "").replace(",", ".")
        else:
            cleaned = cleaned.replace(",", "")
    elif "," in cleaned:
        cleaned = re.sub(r",(?=\d{3}(?:\D|$))", "", cleaned).replace(",", ".")
    try:
        return float(cleaned)
    except ValueError:
        return None


def _norm_availability(value) -> Optional[str]:
    """Normalize to ``in_stock`` / ``out_of_stock`` (schema.org URIs included)."""
    if value is None:
        return None
    if isinstance(value, bool):
        return "in_stock" if value else "out_of_stock"
    text = str(value).strip().lower()
    if not text:
        return None
    if "://" in text:  # e.g. https://schema.org/InStock
        text = text.rsplit("/", 1)[-1]
    compact = text.replace("-", "_").replace(" ", "")
    if compact in ("in_stock", "instock", "available"):
        return "in_stock"
    if compact in ("out_of_stock", "outofstock", "unavailable", "sold_out", "soldout"):
        return "out_of_stock"
    return text


# Code Writer adapted: user contract for THIS site — price carries the currency
# symbol ("$359.00"), currency stays its own ISO field.
_CURRENCY_SYMBOLS = {"USD": "$", "EUR": "€", "GBP": "£", "CAD": "CA$", "AUD": "A$"}


def _fmt_price(value, currency: str) -> str:
    number = _norm_price(value)
    if number is None:
        return ""
    code = (currency or "USD").upper()
    symbol = _CURRENCY_SYMBOLS.get(code)
    if symbol:
        return f"{symbol}{number:,.2f}"
    return f"{code} {number:,.2f}"


# ═══════════════════════════════════════════════════════════════════════════════
# EXTRACTION — JSON-LD ProductGroup + verified CSS fallbacks
# ═══════════════════════════════════════════════════════════════════════════════

def extract_product_ld(soup: BeautifulSoup):
    """Code Writer adapted: return (product_ld, variants).

    bose.com PDPs embed a JSON **array** of LD objects whose commerce data
    lives in a `ProductGroup` — naive `@type == 'Product'` extraction finds
    NOTHING at the group level (probe-verified). Prefer ProductGroup with its
    hasVariant[] array; fall back to a plain Product item (treated as its own
    single variant) for PDPs that use the simpler shape.
    """
    product_groups, plain_products = [], []
    for script in soup.find_all("script", type="application/ld+json"):
        raw = script.string or script.get_text() or ""
        if not raw.strip():
            continue
        try:
            data = json.loads(raw)
        except json.JSONDecodeError:
            continue  # one malformed block must not kill the other blocks
        items = data if isinstance(data, list) else [data]
        for item in items:
            if not isinstance(item, dict):
                continue
            types = item.get("@type")
            types = types if isinstance(types, list) else [types]
            if "ProductGroup" in types:
                product_groups.append(item)
            elif "Product" in types:
                plain_products.append(item)
    if product_groups:
        group = product_groups[0]
        return group, group.get("hasVariant") or []
    if plain_products:
        single = plain_products[0]
        return single, [single]
    return None, []


def _match_variant(variants: list, url: str) -> Optional[dict]:
    """Pick the hasVariant[] item matching the URL's dwvar_*_color param."""
    if not variants:
        return None
    match = re.search(r"dwvar_[^=]+_color=([^&]+)", url or "")
    if match:
        wanted = unquote(match.group(1)).strip().upper()
        for variant in variants:
            if str(variant.get("color", "")).strip().upper() == wanted:
                return variant
    return variants[0]  # documented fallback: first variant (site default)


def _offers_of(variant: Optional[dict]) -> dict:
    offers = (variant or {}).get("offers", {})
    if isinstance(offers, list):
        offers = offers[0] if offers else {}
    return offers if isinstance(offers, dict) else {}


_SOFT_404_MARKERS = ("not found", "unavailable", "discontinued", "no longer available")


def _soft_404_reason(soup: BeautifulSoup, url: str) -> Optional[str]:
    """Detect 200-but-missing product pages (redirects, discontinued PDPs)."""
    title_text = (soup.title.string or "") if (soup.title and soup.title.string) else ""
    h1 = soup.select_one("h1")
    h1_text = h1.get_text(" ", strip=True) if h1 else ""
    blob = f"{title_text} {h1_text}".lower()
    for marker in _SOFT_404_MARKERS:
        if marker in blob:
            return f"Soft 404: page signals '{marker}'"
    canonical = soup.select_one("link[rel='canonical']")
    if canonical and canonical.get("href"):
        requested_path = urlparse(url).path
        canonical_path = urlparse(urljoin(url, canonical["href"])).path
        if requested_path and canonical_path and requested_path != canonical_path:
            return "Soft 404: redirected to a different page"
    return None


def extract_product_from_page(soup: BeautifulSoup, url: str, status_code: int, src_url: str) -> dict:
    """Fields requested by the user: name, price, currency, availability, description."""
    product = {
        "id": 0,
        "title": "",
        "price": "",
        "availability": "",
        "original_price": "",
        "currency": "",
        "url": url,
        "src_url": src_url,
        "location": "",
        "status_code": status_code,
        "scraped_at": datetime.now(timezone.utc).isoformat(),
        "remarks": "",
        "description": "",  # Code Writer adapted: user-requested field
    }

    product_ld, variants = extract_product_ld(soup)
    if product_ld is None:
        reason = _soft_404_reason(soup, url)
        if reason:
            logger.warning("%s → %s", url, reason)
            product["remarks"] = reason
            return product  # leave title/price empty on non-product pages

    variant = _match_variant(variants, url)
    offers = _offers_of(variant)

    # ── title: ProductGroup.name → variant name → h1 ──
    product["title"] = (
        (product_ld or {}).get("name")
        or (variant or {}).get("name")
        or (soup.select_one("h1").get_text(strip=True) if soup.select_one("h1") else "")
        or ""
    ).strip()

    # ── description: variant-specific → group → verified CSS fallback ──
    # (meta[name=description] is SEO marketing copy — deliberately NOT used)
    description = (
        (variant or {}).get("description")
        or (product_ld or {}).get("description")
        or ""
    )
    if not description:
        css_el = soup.select_one(".product-description")
        description = css_el.get_text(" ", strip=True) if css_el else ""
    product["description"] = clean_html(description) if "<" in description else str(description).strip()

    # ── price / currency / availability: variant offers → CSS fallbacks ──
    currency = str(offers.get("priceCurrency") or "").strip().upper()
    raw_price = offers.get("price")
    if _norm_price(raw_price) is None:
        price_el = soup.select_one(".price .sales .value")  # first match = buy-box (verified)
        if price_el:
            css_price = price_el.get_text(strip=True)
            raw_price = css_price
            if not currency and "$" in css_price:
                currency = "USD"
    product["price"] = _fmt_price(raw_price, currency or "USD")
    product["currency"] = currency or ("USD" if product["price"] else "")

    availability = _norm_availability(offers.get("availability"))
    if availability is None:
        add_btn = soup.select_one("button[class*='add-to-cart']")
        if add_btn is not None:
            availability = "out_of_stock" if add_btn.has_attr("disabled") else "in_stock"
    product["availability"] = availability or ""

    # original_price: bose carries no second (list) price in variant offers —
    # stay empty rather than duplicating the current price.
    return product


# ═══════════════════════════════════════════════════════════════════════════════
# DISCOVERY - adapt ONLY the callback below; the loop itself is the shared module
# ═══════════════════════════════════════════════════════════════════════════════

# Strict product-tile anchors: on bose category pages the ONLY /p/ links are
# product tiles (probe-verified — no nav/footer/category anchor carries /p/).
PRODUCT_LINK_SELECTOR = "a[href*='/p/']"
if PRODUCT_LINK_SELECTOR.startswith("{"):
    PRODUCT_LINK_SELECTOR = "a[href]"  # unfilled placeholder → permissive default

# Code Writer adapted: bose PDP URLs are /p/[category/]<slug>/<SKU>.html.
PRODUCT_URL_RE = re.compile(r"^https?://www\.bose\.com/p/[^?]+\.html")


def _extract_listing_links(soup: BeautifulSoup) -> list[str]:
    """This page's product URLs (absolute). Contract: [] when none, never raise."""
    urls = []
    for link in soup.select(PRODUCT_LINK_SELECTOR):
        absolute_url = make_absolute_url(link.get("href", ""))
        if not absolute_url:
            continue
        if PRODUCT_URL_RE is not None and not PRODUCT_URL_RE.search(absolute_url):
            continue
        # Code Writer adapted: strip variation/cart params (?dwvar_*_color=..,
        # &quantity=1) so each PDP is discovered once — the anchor set carries
        # both the bare and the color-parameterized form of the same product.
        urls.append(absolute_url.split("?", 1)[0])
    return urls


# ═══════════════════════════════════════════════════════════════════════════════
# INPUT HANDLING
# ═══════════════════════════════════════════════════════════════════════════════

def load_urls_from_file(filepath: str) -> list[str]:
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data.get("urls", [])


def save_urls_to_file(filepath: str, urls: list[str]) -> None:
    # A 0-URL discovery must not DESTROY an existing seed file.
    if not urls and os.path.exists(filepath):
        logger.warning(f"Refusing to overwrite {filepath} with an empty URL list")
        return
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump({"urls": urls}, f, indent=2, ensure_ascii=False)
    logger.info(f"Saved {len(urls)} URLs to {filepath}")


# ═══════════════════════════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════════════════════════

# ── CLI CONTRACT — keep every line below when adapting ───────────────────────
def main():
    parser = argparse.ArgumentParser(description=f"HTTP scraper for {SITE_NAME}")
    parser.add_argument("--sample", action="store_true", help="Scrape only 5 products")
    parser.add_argument("--limit", type=int, default=None, help="Max products to scrape")
    parser.add_argument("--input", type=str, default=None, help="Path to input URLs JSON file")
    parser.add_argument("--urls", nargs="+", default=None, help="Product URLs as arguments")
    parser.add_argument(
        "--discover-only",
        action="store_true",
        help="Run Phase 1 discovery only; emit discovery_coverage, skip Phase 2 extraction",
    )
    parser.add_argument(
        "--fresh-discovery",
        action="store_true",
        help="Ignore any discovery cache and re-run Phase 1 (accepted as a no-op here: "
        "requests_scraper has no checkpoint file to skip)",
    )
    # Code Writer adapted (added per this job's flag contract; template flags
    # above are untouched): navigation/list_page jobs are launched with this name.
    parser.add_argument(
        "--listing-url",
        type=str,
        default=None,
        help="Listing page to discover from (overrides the built-in PRODUCT_LISTING_URLS)",
    )
    args = parser.parse_args()

    if args.input:
        # Relative seed-file values resolve against the scraper's own directory.
        args.input = os.path.join(SCRIPT_DIR, args.input)

    start_time = time.time()

    logger.info("=" * 80)
    logger.info(f"Starting scraper for {SITE_NAME}")
    logger.info(f"Site: {SITE_URL}")
    logger.info(f"Listing URL: {PRODUCT_LISTING_URL}")
    logger.info(f"Output: {OUTPUT_FILE}")
    logger.info("=" * 80)

    if args.fresh_discovery:
        logger.info(
            "--fresh-discovery accepted (no-op: requests_scraper has no "
            "discovered_urls_checkpoint.json to ignore; input_urls.json is rewritten on every discovery)"
        )

    product_urls = []
    discovered_urls_raw = 0
    ran_phase1 = False
    skipped_reason: Optional[str] = None
    discovery_meta: dict = {"stop_reason": "skipped", "max_pages_hit": False}

    # Shared-module discovery config (data, not code — see the import banner).
    _discovery_cfg = {
        "page_param": PAGE_PARAM_NAME,
        "page_size": PAGE_SIZE,
        "offset_mode": OFFSET_MODE,
        "extra_page_params": EXTRA_PAGE_PARAMS,
        "url_filter": PRODUCT_URL_RE,
        "max_pages": MAX_PAGES,
        "deadline_s": DISCOVERY_DEADLINE_SECONDS,
        "retry_delay_s": EMPTY_DISCOVERY_RETRY_DELAY_S,
    }

    # Phase 1: URL discovery (or load from input).
    # F6 DETERMINISTIC DISCOVERY GATE (env-var): run_execution injects
    # SCRAPER_LISTING_URL because the LLM-adapted argparse may drop
    # --listing-url/--fresh-discovery (the CLI-contract guard then strips
    # them). Without this gate the seed-file branch below ALWAYS wins and
    # discovery never runs. In-place [:] mutation keeps list aliases coherent.
    _env_listing = os.environ.get("SCRAPER_LISTING_URL", "").strip()
    if _env_listing:
        PRODUCT_LISTING_URLS[:] = [_env_listing]
        logger.info("Env gate: SCRAPER_LISTING_URL set — forcing Phase 1 discovery on %s",
                    _env_listing[:80])
    elif args.listing_url:
        PRODUCT_LISTING_URLS[:] = [args.listing_url]
        logger.info("--listing-url set — discovering from %s", args.listing_url[:80])

    def _discover_with_zero_heal(tag: str):
        """Code Writer adapted: shared-module call kept verbatim; if the
        supplied listing(s) yield ZERO item URLs, retry ONCE against the
        known-good promoted listing (job-310: harness may pass a listing whose
        card markup the selectors miss) instead of succeeding emptily."""
        urls, meta = discover_listing_urls_with_retry(
            fetch_page, PRODUCT_LISTING_URLS, _extract_listing_links,
            **_discovery_cfg,
        )
        if not urls and PRODUCT_LISTING_URLS != [DEFAULT_LISTING_URL]:
            logger.warning("%s: 0 item URLs discovered — retrying with default listing %s",
                           tag, DEFAULT_LISTING_URL)
            urls, meta = discover_listing_urls_with_retry(
                fetch_page, [DEFAULT_LISTING_URL], _extract_listing_links,
                **_discovery_cfg,
            )
        return urls, meta

    if args.discover_only or _env_listing:
        logger.info("Discovery mode (%s): running Phase 1, skipping Phase 2 extraction",
                    "env-gate" if _env_listing else "--discover-only")
        product_urls, discovery_meta = _discover_with_zero_heal("discover-only/env-gate")
        discovered_urls_raw = len(product_urls)
        ran_phase1 = True
        save_urls_to_file(INPUT_FILE, product_urls)
    elif args.urls:
        product_urls = args.urls
        skipped_reason = "url_list_mode"
    elif args.input:
        product_urls = load_urls_from_file(args.input)
        skipped_reason = "url_list_mode"
    elif os.path.exists(INPUT_FILE):
        # Code Writer adapted (this is a list_page navigation job): the default
        # branch must NEVER fall back to input_urls.json when it holds LISTING
        # pages (the tester's seed) — that would scrape category pages as
        # products. Reuse it only when it holds item URLs from a prior
        # discovery; otherwise run Phase 1 discovery.
        cached = load_urls_from_file(INPUT_FILE)
        cached_items = [u for u in cached if PRODUCT_URL_RE.search(u or "")]
        if cached_items:
            logger.info(f"Loading {len(cached_items)} previously discovered item URLs from {INPUT_FILE}")
            product_urls = cached_items
            skipped_reason = "checkpoint_loaded"
        else:
            logger.info("input_urls.json holds listing pages, not item URLs — discovering products...")
            product_urls, discovery_meta = _discover_with_zero_heal("default-no-cache")
            discovered_urls_raw = len(product_urls)
            ran_phase1 = True
            save_urls_to_file(INPUT_FILE, product_urls)
    else:
        logger.info("No input_urls.json found. Discovering products from listing page...")
        product_urls, discovery_meta = _discover_with_zero_heal("cold-start")
        discovered_urls_raw = len(product_urls)
        ran_phase1 = True
        save_urls_to_file(INPUT_FILE, product_urls)

    # Raw discovered count is captured BEFORE any sample/limit slicing.
    if not ran_phase1:
        discovered_urls_raw = len(product_urls)

    # Sample/limit only apply when Phase 2 extraction will run.
    if not args.discover_only:
        if args.sample:
            product_urls = product_urls[:5]
        if args.limit:
            product_urls = product_urls[: args.limit]

    logger.info(f"Total products to scrape: {len(product_urls)}")

    results = []
    failed = 0

    if not args.discover_only:
        # Phase 2: extract fields from each discovered item page.
        # (Sequential on purpose: fetch_page is the shared proxy-ladder module
        # with tier state a thread pool would race; at delay=1.5s the full
        # catalog is a minutes-long run, not hours.)
        phase2_start = time.monotonic()
        for i, url in enumerate(product_urls):
            result = fetch_page(url)
            if result:
                soup, status_code = result
                product = extract_product_from_page(soup, url, status_code, SRC_URL)
                product["id"] = i + 1
                # Emission filter: a row with NO substantive field beyond the
                # boilerplate keys is a page that rendered nothing.
                _BK = {"url", "src_url", "scraped_at", "status_code", "remarks", "id", "title"}
                if any(v for k, v in product.items() if k not in _BK):
                    results.append(product)
                else:
                    logger.warning(f"No substantive data extracted from: {url}")
                    failed += 1
            else:
                logger.error(f"Failed to fetch: {url}")
                failed += 1

            if (i + 1) % 25 == 0:
                percent = ((i + 1) / len(product_urls)) * 100
                logger.info(f"Progress: [{i + 1}/{len(product_urls)}] ({percent:.1f}%)")
    else:
        logger.info("--discover-only: skipping Phase 2 extraction (results list left empty)")

    # Mechanical "fetch actually happened" detector (template bookkeeping).
    phase2_instant = False
    if not args.discover_only and product_urls:
        phase2_elapsed = time.monotonic() - phase2_start
        phase2_instant = phase2_instant_fail(
            phase2_elapsed, len(product_urls), DELAY_BETWEEN_REQUESTS
        )
        if phase2_instant:
            logger.warning(
                "PHASE2 INSTANT FAIL: %s items in %.2fs (< %.2fs floor at "
                "delay=%ss) — fetches never actually happened",
                len(product_urls), phase2_elapsed,
                len(product_urls) * DELAY_BETWEEN_REQUESTS * 0.5,
                DELAY_BETWEEN_REQUESTS,
            )

    # discovery_coverage block — always emitted.
    if ran_phase1:
        stop_reason = discovery_meta.get("stop_reason", "no_next_link")
    else:
        stop_reason = "skipped"

    discovery_coverage = {
        "stop_reason": stop_reason,
        "found": len(results),
        "discovered_urls": discovered_urls_raw,
        "expected_total": None,
        "dimensions_iterated": len(PRODUCT_LISTING_URLS) if ran_phase1 else 0,
        "dimensions_total": len(PRODUCT_LISTING_URLS) if ran_phase1 else 0,
        "max_pages_hit": discovery_meta.get("max_pages_hit", False),
        "ran_phase1": ran_phase1,
        "skipped_reason": skipped_reason,
        "soft_block_escalations": discovery_meta.get("soft_block_escalations", 0),
        "retried_empty_discovery": discovery_meta.get("retried_empty_discovery", False),
        "jsonld_fallback_pages": discovery_meta.get("jsonld_fallback_pages", 0),
        "phase2_instant_fail": phase2_instant,
    }

    output = {
        "site": {
            "name": SITE_NAME,
            "url": SITE_URL,
            "platform": PLATFORM,
            "scraping_method": SCRAPING_METHOD,
            "scraped_at": datetime.now(timezone.utc).isoformat(),
        },
        "products": results,
        "metadata": {
            "phase": "discovery" if args.discover_only else "extraction",
            "scraping_duration_seconds": round(time.time() - start_time, 2),
            "failed_products": failed,
            "rate_limit_delay": DELAY_BETWEEN_REQUESTS,
            "discovered_urls": discovered_urls_raw,
            "discovery_coverage": discovery_coverage,
        },
    }

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        # _OUTPUT_FILTER_APPLIED — drop non-item pages (content-type aware)
        _FILTER_FIELDS = ['product name', 'price', 'currency', 'avaliability', 'description']
        try:
            # Code Writer fix: OUTPUT_KEY is a defined module constant; the
            # old `X if 'X' in dir()` form was an F821 crash and a no-op for
            # module-level names anyway.
            _OUTPUT_KEY = OUTPUT_KEY if OUTPUT_KEY in output else next(
                (k for k, v in output.items() if isinstance(v, list)
                 and v and isinstance(v[0], dict)), None)
            if _OUTPUT_KEY:
                _before = len(output[_OUTPUT_KEY])
                output[_OUTPUT_KEY] = [p for p in output[_OUTPUT_KEY] if p.get('product name') or p.get('price') or p.get('currency') or p.get('avaliability') or p.get('description')]
                _after = len(output[_OUTPUT_KEY])
                if _before != _after:
                    logger.info('output filter: %d → %d items (removed %d without any of product name,price,currency,avaliability,description)',
                                 _before, _after, _before - _after)
        except Exception:
            pass


        json.dump(output, f, indent=2, ensure_ascii=False)

    logger.info("=" * 80)
    logger.info("DISCOVERY COMPLETE (--discover-only)" if args.discover_only else "EXTRACTION COMPLETE")
    logger.info(f"Total: {len(results)}, Failed: {failed}")
    logger.info(
        f"Discovery coverage: stop_reason={stop_reason}, found={len(results)}, "
        f"discovered_urls={discovered_urls_raw}, ran_phase1={ran_phase1}, "
        f"skipped_reason={skipped_reason}"
    )
    logger.info(f"Duration: {round(time.time() - start_time, 2)}s")
    logger.info(f"Output: {OUTPUT_FILE}")
    logger.info("=" * 80)


if __name__ == "__main__":
    main()
